.travis.yml
Will also update clang for macOS in a later PR. There are some issues with macOS since vanilla clang-3.8 has build-in OpenMP support which uses the Intel OpenMP library (libomp) instead of the GCC implementation (libgomp) which would be used otherwise. This doesn't work since `#include <parallel/algorithm>` for example will fail since it is apparently not supported in the Intel OpenMP implementation. That is at least my conclusion after some testing. Let me know if you have thoughts on that.
=> Update clang for Linux

setup.py
The setup script currently only checks if the Mercurial directory (.hg) is present to determine whether to use the pre-cythonized _NetworKit.cpp. Therefore, the Cython wrapper is never re-built if you checked out NetworKit in Git.
=> Update setup.py to cythonize in a Git environment

networkit/GraphMLIO.py
Now, every attribute without values is written as integer attribute. An example is when your code wants to export edge attributes for a graph without edges.
=> GraphML: fix writing of empty attributes

networkit/cpp/centrality/LocalPartitionCoverage.cpp
This sets the local partition coverage for nodes with degree 0 to 0 (as they cover nothing). Of course one could also define it as 1, as all of their neighbors are within their own partition, it's just that I found 0 to be the more consistent solution.
=> LocalPartitionCoverage: fix for nodes with degree 0

networkit/_NetworKit.pyx, networkit/cpp/scd/GCE.cpp, networkit/cpp/scd/GCE.h, networkit/cpp/scd/PageRankNibble.cpp, networkit/cpp/scd/PageRankNibble.h, networkit/cpp/scd/SelectiveCommunityDetector.h, networkit/cpp/scd/test/SelectiveCDGTest.cpp
Previously, unsigned int was used because the automatic conversion in Cython was not properly working. However, the Cython issue has been fixed in the meantime and other code in NetworKit relies on the fixed Cython version, too.
=> SCD: use node type for seeds and add some const qualifiers

networkit/cpp/io/EdgeListReader.cpp
Before, empty lines were only skipped in the first pass but not in the second pass.
=> EdgeListReader: skip empty lines consistently

networkit/cpp/io/PartitionReader.cpp
This makes it possible to read partitions e.g. of graphs with deleted nodes.
=> PartitionReader: allow to read partitions with none values

networkit/cpp/graph/GraphBuilder.cpp
This disables the parallelism in two loops in GraphBuilder for small graphs. Both of them are simple loops over the nodes with only sequential memory access. I actually doubt that parallelism is of any use here at all as this should be bound by RAM speeds. This change disables the parallelism at least for graphs with less than 1Mi nodes. For me, the parallelism lead to significant slow-downs when I created a large amount of small (less than 100 nodes) graphs.
=> GraphBuilder: enable some parallelism only for large graphs

networkit/cpp/centrality/TopCloseness.cpp, networkit/cpp/centrality/test/CentralityGTest.cpp, networkit/cpp/generators/quadtree/test/QuadTreeGTest.cpp
This contains a few fixes related to #6 and #14 but they don't fix the real problems. Further, a compiler warning is fixed and another seed is set in `QuadTreeGTest`.
=> Closeness fixes

networkit/__init__.py, networkit/cpp/centrality/LocalClusteringCoefficient.cpp
Won't show the clustering coefficient information for graphs that are directed or have self-loops since the clustering coefficient implementation is not designed to handle those graphs.
Resolves #29.
=> Not showing clustering coefficient for unsuited graphs in overview(G)

networkit/cpp/generators/DynamicHyperbolicGenerator.cpp, networkit/cpp/generators/quadtree/QuadNode.h, networkit/cpp/graph/Graph.h, networkit/cpp/numerics/LAMG/Level/Level.h, networkit/cpp/numerics/LAMG/Level/LevelAggregation.h, networkit/cpp/numerics/LAMG/MultiLevelSetup.h
When compiling code linking the C++ library of networkit, there are many different unused variable warnings. This fixes the ones I found. There are no other changes.
The code should merge cleanly both into master and into dev.
=> Fixes many different unused warnings.

networkit/cpp/viz/Octree.h
GCC 7 gives a warning about a signed bit-shift in Octree.h, which (in my opinion) poses a possible bug:
0 is signed by default, therefore ~0 is not (signed 0) and implementation specific, first comment here:
https://stackoverflow.com/a/2999588/2419265
The intended value here, if I understand correctly, is UINT_MAX or 0xffffffff, therefore it should be 0U, however in the bitness of index: therefore static_cast<index>(0). Thoroughly check this commit before merging.
=> Signed 0 default in Octree

networkit/cpp/auxiliary/Parallel.h
This adds the `functional` header for `std::greater` and `std::less`.
=> auxiliary/Parallel.h: add missing include

networkit/cpp/graph/Graph.h
This prevents some compiler warnings for unused parameters by removing their names.
=> Graph: remove unused parameters

networkit/cpp/distance/Diameter.cpp
This avoids some duplicate BFS by ensuring that the BFS from more central nodes start from nodes that have a positive distance from the last start node. If the previous start node is a degree-1-node, this also ensures that the next start node is away from the first node with a higher degree as otherwise we also would not get any new information.
=> Diameter: Avoid duplicate BFS

networkit/_NetworKit.pyx, networkit/cpp/generators/RmatGenerator.cpp, networkit/cpp/io/EdgeListWriter.cpp, networkit/cpp/io/EdgeListWriter.h, networkit/graphio.py
This fixes several issues and improves the fitting to generate graphs with a better fit to the graph that shall be replicated. In particular this contains the following changes:
* EdgeListWriter is extended to support writing symmetric directed graphs.
* The R-MAT generator does not produce graphs with deleted nodes anymore as they create problems in so many places.
* The R-MAT generator for undirected graphs produces graphs with exactly the requested edge factor. The graphs also do not contain any self-loops anymore.
* The R-MAT generator for weighted graphs produces more edges when nodes shall be deleted to compensate for the edges that are lost due to deleting nodes. Here, self-loops are still possible.
* kronfit (for fitting) is called with an explicit output file (the previous …
=> R-MAT generator: several fixes and improvements

networkit/_NetworKit.pyx, networkit/cpp/generators/LFRGenerator.cpp
This fixes several issues in the LFR generator:
* In some cases, there was an infinite loop when communities had very special degree distributions
* The fitting of the mu value for the "vanilla" LFR generator was wrong, this has been corrected
* The maximum community size is now adjusted if necessary to fit the largest degree
* The parameters for the reference implementation are slightly adjusted to make sure the external implementation fails less (however, additional changes in the external code are required to support minimum degrees of 1).
=> Several fixes for the LFR generator

SConstruct
These changes to SConstruct allow a simple way to include external projects with custom include / library paths by extending the `[libraries]` and `[includes]` sections of the `build.conf` file:
```
[libraries]
expro = /home/user/share/expro/lib
[includes]
expro = /home/user/share/expro/include
```
Effects:
* `-I/home/user/share/expro/include` is added to all compiler calls
* `-L/home/user/share/expro/lib` is added to all linker calls
* `-lexpro` is added to all linker calls (determined by the `expro` key in the `[libraries]` section).
The inclusion of `gest`, `std` and `tbb` works as before.
I'd propose including these in the main repository as they streamline the integration of external projects for all contributors (and all forks).
Backported from …
=> SConstruct: Improved reading external library paths from build.conf

networkit/nxadapter.py
nxG.edge is removed from NetworkX 2.0, to compatable with boath NetworkX 2.0 and Network 1.1X, we can just use nxG[u_][v_][weightAttr] instead.
=> Compatibility with NetworkX 2.0

.travis.yml, SConstruct
This fixes the indentation for Python 3 and migrates from (Python 2) `ConfigParser` to (Python 3) `configparser`. This allows building with scons 3.0 with Python 3 (yes, this means no more dependency on Python 2). For Python 2 support, installing the `configparser` backport from pip is necessary now. I fixed this for Travis, but probably this should also be documented or automated somewhere?
=> SConstruct: fixes for SCons 3

networkit/cpp/graph/Graph.cpp
=> Throw exception when sampling random edges from empty graph

networkit/cpp/centrality/Closeness.cpp
Resolves incorrect `maximum` method mentioned in #81.
=> Fix maximum for closeness scores

.travis.yml, SConstruct
Reverts kit-parco/networkit#77.
**Issues:**
- Automatically installing the configparser compatibility package on Python2 doesn't work reliably for some of our test systems. We're unable to install the package during runtime and import it afterwards. A restart of the scons script would be needed.
- There seems to be an internal issue with scons3. When installed through pip3 it won't work out of the box since it won't look in the python3 package folders to find additional scripts. A manual symlink seems to be needed.
=> Revert "SConstruct: fixes for SCons 3"

.travis.yml, SConstruct, requirements.txt, setup_util.py
If the user is running SCons3 on Python3 it will automatically use the respective configparser module from Python3. Otherwise it will default to using the old ConfigParser package on Python 2.
This is still not ideal since we're not able to use the new configparser features on Python 2.
=> Backwards compatible configparser

.travis.yml
It is no longer possible to build inside the /runtime folder. Have to execute cmake on top-level CMakeLists.txt.
=> Fix build paths for openmp

.travis.yml
Should use pip2 instead of pip for newer xcode images.
=> Fix install through pip on travis osx

.travis.yml
Travis updated their macOS images to include `oclint` which will provide a default gcc binary. This leads to failure during installation of a custom gcc binary through Homebrew.
This PR addresses the issue by uninstalling oclint beforehand.
=> Travis: Fix custom gcc installation on macOS images

networkit/cpp/auxiliary/test/AuxGTest.cpp
testTimer causes Travis CI to fail sporadically.
We cannot rely on the OS' scheduler to wake up the test within a certain time frame. This is especially unreliable on busy systems (like the Travis servers).
Turning this test into a benchmark allows us to still run it manually without causing CI failures.
@kolja-esders Please check if this makes sense.
=> Fix travis failures due to testTimer

networkit/profiling/profiling.py
This fixes a minor spelling bug, which led to a `NameError` instead of the actual one.
Thanks for considering this!
=> fix error message for profiling

SConstruct
Exception emerges from the fact that we are appending (unhashable) `dict_keys` and `dict_values` under Python3 instead of expected (hashable) lists to the environment.
=> Prevent 'unhashable type' exception when running SCons with Python3

networkit/cpp/numerics/test/LAMGGTest.cpp
Timeouts on tests are problematic as tests might take much longer
on shared CI servers than they do locally.
Fixes #125
=> Remove timeout from LAMG test

networkit/_NetworKit.pyx
Previously, the callback has always been deleted even if the instantiation succeeded (no idea why it ever worked).
=> MaximalCliques: fix callback handling

networkit/_NetworKit.pyx, networkit/cpp/dynamics/GraphDifference.cpp, networkit/cpp/dynamics/GraphDifference.h, networkit/cpp/dynamics/GraphEvent.cpp, networkit/cpp/dynamics/GraphEvent.h, networkit/cpp/dynamics/GraphUpdater.cpp, networkit/cpp/dynamics/GraphUpdater.h, networkit/cpp/dynamics/test/DynamicsGTest.cpp, networkit/dynamic.py
The GraphDifference algorithm computes a series of graph events that transform one given graph into another given graph. This makes it possible to construct a series of events from a given series of graphs.
Further, this marks `GraphEvent::toString()` as `const` and marks event stream passed to `GraphUpdater` as `const`.
=> Add algorithm to compute the difference of two graphs

networkit/cpp/algebraic/algorithms/test/AlgebraicPageRankGTest.cpp, networkit/cpp/algebraic/algorithms/test/AlgebraicTriangleCountingGTest.cpp, networkit/cpp/centrality/test/CentralityGTest.cpp, networkit/cpp/centrality/test/DynBetweennessGTest.cpp, networkit/cpp/centrality/test/DynTopHarmonicClosenessGTest.cpp, networkit/cpp/clique/test/CliqueGTest.cpp, networkit/cpp/components/test/ConnectedComponentsGTest.cpp, networkit/cpp/distance/test/CommuteTimeDistanceGTest.cpp, networkit/cpp/distance/test/DistanceGTest.cpp, networkit/cpp/distance/test/DynSSSPGTest.cpp, networkit/cpp/generators/quadtree/test/QuadTreeGTest.cpp, networkit/cpp/generators/test/GeneratorsGTest.cpp, networkit/cpp/geometric/test/GeometricGTest.cpp, networkit/cpp/numerics/test/LAMGGTest.h
As discussed (#7 here too), this PR aims at reducing the testsuite runtime. #
As a start, I took the runtime on Travis and selected all tests with >1s (26 of 849 tests). 
All in all, most tests used too many or too great graphs for their algorithms complexity. With addressing these reasons I was able to reduce the runtime of the whole testsuite from 100s to 23s on my machine.
The first commit aims at improving the runtime of tests which are well written and which use gtest effectively. 
The tests improved in the second commit do NOT use gtest, while consuming a lot of runtime (longest test alone took 25s on travis). The runtime of these tests have been reduced drastically.
=> Reducing the runtime of the test suite

networkit/cpp/io/KONECTGraphReader.h
The default constructor in the KONECTGraphReader class did not
properly initialize all member variables. Remove the default
constructor and assign default values to the non-default
constructor so that it can be called without arguments.
This commit also cleans up unused variables from the class.
=> io/KONECTGraphReader: Fix default constructor

networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/test/GraphBuilderDirectSwapGTest.cpp
As proposed by @michitux here #160, i implemented a more efficient hasEdge function. There is no reason this feature should be limited to Graph Readers alone so i applied the changes to the Graph.cpp itself.
Nevertheless, the changes do not really speed up the performance of graph readers, but are efficient in other use cases - especially under power law conditions. For example the LFRGenerator uses the hasEdge method very extensively. I benchmarked the generation of a graph with power law degrees and recognized performance increases of around 10%.
=> faster hasEdge() for undirected graphs

networkit/cpp/structures/Partition.cpp, networkit/cpp/structures/test/PartitionGTest.cpp
This uses parallel sorting instead of a `std::map`. From a theoretical perspective, the total work is unchanged but while previously the sequential part was O(n log(n)), it is now only O(n) - a single sequential scan to determine unique ids.
`Partition::compact()` is the main bottleneck when comparing partitions using e.g. normalized mutual information or the adjusted rand index.
Apart from this optimization I also tried to simply replace the  `std::map` by a `std::unordered_map`. While this causes less total work than the implementation proposed in this PR, this implementation is faster  than the `std::unordered_map` variant when using multiple cores even on my laptop.
=> Faster Partition::compact() implementation

networkit/cpp/overlap/test/OverlapGTest.cpp
Fixes the issue raised in https://github.com/kit-parco/networkit/issues/175.
The issue is fixed by comparing if the output vector is a permutation of the desired one.
=> fix assertion in testHashingOverlapperForCorrectness

networkit/_NetworKit.pyx, networkit/community.py, networkit/cpp/io/BinaryEdgeListPartitionReader.cpp, networkit/cpp/io/BinaryEdgeListPartitionReader.h, networkit/cpp/io/BinaryEdgeListPartitionWriter.cpp, networkit/cpp/io/BinaryEdgeListPartitionWriter.h, networkit/cpp/io/BinaryPartitionReader.cpp, networkit/cpp/io/BinaryPartitionReader.h, networkit/cpp/io/BinaryPartitionWriter.cpp, networkit/cpp/io/BinaryPartitionWriter.h, networkit/cpp/io/ThrillGraphBinaryReader.cpp, networkit/cpp/io/ThrillGraphBinaryReader.h, networkit/cpp/io/ThrillGraphBinaryWriter.cpp, networkit/cpp/io/ThrillGraphBinaryWriter.h, networkit/cpp/io/test/IOGTest.cpp, networkit/graphio.py
This adds some readers and writers for binary graph and partition files. Basically, this is the code we used for the evaluation of our paper [Distributed Graph Clustering using Modularity and Map Equation](https://arxiv.org/abs/1710.09605) (code available at [kit-algo/distributed_clustering_thrill](https://github.com/kit-algo/distributed_clustering_thrill)). The [external memory LFR implementation](https://github.com/massive-graphs/extmem-lfr) supports the same formats, too.
The binary partition formats are straightforward generalizations of the standard partition formats, just using binary integers. In [Thrill](http://project-thrill.org/), this corresponds to a DIA of integers or pairs of integers. The graph format consists of one entry per node. Each node begins with its degree as …
=> Add various binary partition and graph readers and writers

networkit/cpp/centrality/GroupCloseness.cpp, networkit/cpp/centrality/GroupCloseness.h, networkit/cpp/centrality/test/CentralityGTest.cpp
GroupCloseness now uses a BucketPQ instead of a PrioQueueForInts which was deprecated. 
Also, added a new test suite for GroupCloseness which was missing.
Signed-off-by: Eugenio Angriman <angriman@informatik.uni-koeln.de>
=> Fixes for GroupCloseness

networkit/cpp/centrality/ApproxGroupBetweenness.cpp
Slightly increased the accuracy, since we only need to add the internal nodes of a shortest path to the hyperedge.
=> Improved ApproxGroupBetweenness.cpp

benchmark/nk.py, networkit/profiling/profiling.py
Until now, measuring the approximated effective diameter in profiling always failed due to an incorrect function call.
This fixes #199.
=> Fix usage of EffectiveDiameterApproximation

.travis.yml, CMakeLists.txt, networkit/_NetworKit.pyx, networkit/cpp/randomization/CurveballImpl.cpp, setup.py
This PR combines several improvements which I consider okay, since it's not targeting the Dev-branch yet.
- Rather than using OpenFlags as an parameter to `LINK_FLAGS` directly, this PR introduces the `NETWORKIT_LINK_FLAGS` proxy. This is partly to make MSVC porting easier, which treats the Flags subtle differently.
- Introduce `NETWORKIT_CXX_STANDARD` as parameter to make it possible to test NetworKit against higher standards during CI.
- `setup.py` now only invokes Cython if `_Networkit.cpp` is either missing or out-dated (its timestamp is older than `_Networkit.pyx`). This significantly speeds up recompilation.
- In monolithic builds define two tests with correctly set working path, to avoid the necessity of symlinks to the input/output directories in the build directory. Consequently, …
=> Cumulative Updates to CMake-PR

.travis.yml, README.md, version.py
Despite the whole documentation needs a cleanup / rewrite at some point, this PR updates at least the  `README.md` in order to match the new build environment.
Documentation regarding the tests are intentionally left out because this should be documented in the `DevGuide.md`.
**NOTE** : This PR also removes cython from the install_requires field in `version.py`, because it is not required anymore if a `_NetworKit.cpp` is provided.
=> CMake environment - Documentation

.travis.yml, setup.py
Apparently, NetworKit hits an internal LLVM error with LLVM 3.7. Upgrade the macOS build to LLVM 4 to fix this issue.
=> Fix macOS clang build on Travis

.travis.yml, networkit/cpp/community/CoverHubDominance.cpp, networkit/cpp/community/PartitionHubDominance.cpp, networkit/cpp/sparsification/LocalDegreeScore.cpp, networkit/cpp/sparsification/LocalFilterScore.h, networkit/cpp/structures/Partition.cpp, setup.py
While the macOS clang build was broken because of LLVM bugs, the Linux clang build was broken because of NetworKit bugs. In particular, NetworKit relied on the undefined `std::vector<std::atomic<...>>` pattern. This PR fixes this issue.
Based on #203.
=> Fix Linux clang build on Travis

.travis.yml
This PR introduces `travis_wait` in favor of `pip3 -v` to prevent no-output timeouts on Travis.
=> Remove pip3 -v from Travis scripts

networkit/cpp/randomization/Curveball.h, networkit/cpp/randomization/GlobalCurveball.h, networkit/cpp/scd/PageRankNibble.h, networkit/cpp/scd/SelectiveCommunityDetector.h
Clang rightfully complains, that the virtual abstract class `SelectiveCommunityDetector` inherited by `PageRankNibble` does not contain a virtual destructor despite it's required in the Unit Test. This PR adds it.
Also, Clang thinks `Curveball::isParallel` should be annotated with `override`. So why not ;)
=> Fix virtual warnings

.travis.yml
The High Sierra image on Travis is broken. Just fix the xcode (and macOS) version to xcode 8 for now to work around the problem.
=> travis: Fix build by avoiding High Sierra

networkit/cpp/auxiliary/Random.cpp, networkit/cpp/auxiliary/Random.h, networkit/cpp/auxiliary/test/AuxRandomBenchmark.cpp, networkit/cpp/auxiliary/test/AuxRandomBenchmark.h, networkit/cpp/auxiliary/test/CMakeLists.txt
This is a duplicate of the initial closed #215 
Aux::Random offers `thread_local` references to random number generators and distributions. If the code does not recognize that the compiler supports the `thread_local` keyword, it silently uses non-`thread_local` instances. The test however only checked for GCC>4.8, Clang never used thread_local!
If a user assumes (for a good reason) that its references are thread-local and the detection fails, we get race-conditions and false-sharing, i.e. slow code broken code. I did not check which algorithms are affected, but my new code certainly was.
IMHO we should expect `thread_local` from a compiler nowadays. If its not supported we should be very verbose about it, and have a compile-time error.
Another issue in `Aux::Random` was the treatment of …
=> Fix race-condition and false-sharing in Aux::Random

.travis.yml
As discussed in #236, currently Travis builds take way too long. This PR aims to reduce the latency of the CI pipeline by breaking the Travis script into multiple smaller configurations.
As a result, the total build time decreases from [5 h 13 min](https://travis-ci.org/kit-parco/networkit/builds/435527511) to [3h 18 min](https://travis-ci.org/kit-parco/networkit/builds/435585051). The maximal time for a single configuration decreases from 47 min to 32 min.
=> Break Travis tests into individual configurations

.travis.yml
Travis macos image seems to have been fixed so we shall not allow those builds to fail anymore.
=> Removed allowed failures on Travis

networkit/cpp/centrality/KadabraBetweenness.cpp, networkit/cpp/centrality/KadabraBetweenness.h, networkit/cpp/components/ConnectedComponents.h
In undirected graphs Kadabra looks if a sampled pair is within the same CC. If not, it skips the computation of the shortest path because it would lead to an empty path anyway.
This does not affect the distribution of the sampled pairs.
=> Kadabra: skip useless shortest-path computations

.travis.yml, CMakeLists.txt, appveyor.yml, setup.py
This is another PR to reduce Travis' build times (see #236); however, the functionality implemented in this PR might also be interesting on its own:
We extend the build system to allow building the Python extention without building the NetworKit core (i.e. C++) library. This is done by passing -DNETWORKIT_BUILD_CORE=OFF to cmake and requires an external prebuilt copy of the core library. Our Travis script is modified to take advantage of this feature.
I should remark that after this PR, NetworKit is built as a shared library by default. This can be deactivated using -DNETWORKIT_STATIC but is no longer coupled to -DNETWORKIT_PYTHON.
This PR reduces Travis build times from [3 h 50 min](https://travis-ci.org/kit-parco/networkit/builds/436732224) to [3 h 5 …
=> Support Python build with external NetworKit core library

networkit/_NetworKit.pyx
Note that the documentation of the method actually already promised the return value, just that no value was returned.
=> Partition.mergeSubsets: return id of merged part in Python

networkit/_NetworKit.pyx
This PR is based on #156 from @michitux. As discussed with @avdgrinten, it would be safer to only provide an equality method for graph events.
=> Implement equality for graph events

.travis.yml
Add functionality to `.travis.yml` to build the documentation and push it to the https://networkit.github.io/dev-docs GitHub Pages repository. This is done by the @networkit-ci account via a secret access key that is stored in the Travis settings of this `kit-parco/networkit` repository.
After this PR is merged, the documentation will automatically be updated whenever we push to `Dev`.
=> Deploy documentation from this repository to networkit.github.io/dev-docs

.travis.yml
Now the travis script for osx builds on osx 10.13/12 (xcode 10.1 and 9.2), with gcc 8, llvm 7, and Apple clang.
=> Fix/travis allowed failures and new macOS builds

.travis.yml
By default travis clones the repository with a depth of 50 commits. Builds may be a bit faster if it does a shallow clone.
=> NetworKit shallow clone on travis

requirements.txt, version.py
Seaborn and sklearn are not strictly required so we should move them to the `requirements.txt` file. Also, `ipython` seems to be necessary so we should include it in the `version.py` file.
=> Seaborn and sklearn are now optional requirements

.travis.yml
Avoid to update homebrew and python saves a few minutes on every osx build. Removed macOS 10.12 build with Apple Clang as it required cmake to be updated.
=> Avoid travis python update

CMakeLists.txt
This PR adds the missing dependency of `networkit_gtest_main` to `gtest`.
=> Add missing dependency to GTest

networkit/cpp/generators/quadtree/test/QuadTreeGTest.cpp
Sometimes the build on Windows timeouts because of `QuadTreeGTest.testEuclideanCircle`. Trying to solve this issue by setting a fixed random seed for this test.
=> Setting a fixed random seed in testEuclideanCircle

networkit/_NetworKit.pyx, networkit/community.py, networkit/cpp/community/CMakeLists.txt, networkit/cpp/community/CoverF1Similarity.cpp, networkit/cpp/community/CoverF1Similarity.h, networkit/cpp/community/test/CommunityGTest.cpp
This adds an algorithm to compare two covers using the F1 score. This is a typical similarity measure used to compare the found overlapping community structure to a ground truth community structure. Each cluster is compared to the best-matching reference cluster (in terms of highest F1 score). A value of 1 indicates perfect agreement while a while of 0 indicates complete disagreement. An example where this measure is used is the following paper:
Alessandro Epasto, Silvio Lattanzi, and Renato Paes Leme. 2017. Ego-Splitting Framework: from Non-Overlapping to Overlapping Clusters. In Proceedings of the 23rd ACM SIGKDD International Conference on Knowledge Discovery and Data Mining (KDD '17). ACM, New York, NY, USA, 145-154. DOI: https://doi.org/10.1145/3097983.3098054
Note that this breaks …
=> Add community.CoverF1Similarity

README.md
In order to avoid to maintain two lists of contributors, we refer to the credits page on the NetworKit website.
=> Credits: redirecting to the networkit website credits page.

CMakeLists.txt, setup.py
As suggested by @rbange, installing into a flat directory hierarchy is not intuitive. This PR aims to fix that. We still need the possibility to install into a flat hierarchy to build the Python package.
=> Install to PREFIX/lib by default

CMakeLists.txt
Install the NetworKit headers to the install prefix. In addtiion, allow the user to specify installation paths relative to CMAKE_INSTALL_PREFIX.
=> Install NetworKit headers

.travis.yml
Switched to xenial distribution and Python 3.5 for all Linux builds on Travis.
=> Travis: switch to xenial Linux distribution and Python 3.5

CMakeLists.txt
Tlx files could not be linked to the Python build if they were included from NetworKit `.hpp` files.
This fixes the issue.
=> Linking tlx to networkit python build

include/networkit/centrality/GroupDegree.hpp, include/networkit/graph/Graph.hpp, networkit/cpp/centrality/GroupDegree.cpp, networkit/cpp/centrality/KadabraBetweenness.cpp, networkit/cpp/clique/test/MaximalCliquesGTest.cpp, networkit/cpp/community/SampledGraphStructuralRandMeasure.cpp, networkit/cpp/components/BiconnectedComponents.cpp, networkit/cpp/components/test/BiconnectedComponentsGTest.cpp, networkit/cpp/distance/Volume.cpp, networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/test/GraphGTest.cpp, networkit/cpp/linkprediction/NeighborhoodUtility.cpp
This removes the `neighbors(v)` method from the graph class; the method creates a copy of the `outEdges[v]` vector which is not an efficient way to iterate over neighbors.
Declared the getter methods of the neighbor iterators of the `Graph` class as `const` so they can be also be used by const refs of Graph objects.
=> Removed neighbors() method from Graph and fixed affected classes

.travis.yml
This adds two new builds to travis: macOS 10.12/13 with the newly released llvm 8.
=> Add macOS builds with llvm 8

networkit/_NetworKit.pyx
`neighbors` method now uses iterators; added also `inNeighors` method.
=> Python: fixed deprecated neighbors methods

.travis.yml, CMakeLists.txt
This PR incorporates the new macOS travis config introduced here: https://github.com/kit-parco/networkit/pull/310
Also `CMakeLists.txt` is adapted to manually set compile and linking flags for clang-like compiler.
Regarding https://github.com/kit-parco/networkit/pull/310#issuecomment-481229629:
We could get rid of the `find_library` and `find_path` parts by assuming the installed libomp is properly linked (as e.g. homebrew does by default), but that might be less robust.
Also, the OpenMP::OpenMP_CXX target is manually created if it does not exist, although that's never tested in CI. The travis linux images got a package update and cmake has version 3.12.4 now.
=> MacOS 10.14

include/networkit/graph/Graph.hpp, networkit/_NetworKit.pyx, networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/test/GraphGTest.cpp
New method that deletes all nodes and edges not in the largest connected component of a graph. Only works for undirected graphs.
=> New Graph method: toLargestConnectedComponent()

networkit/cpp/distance/AllSimplePaths.cpp
As pointed out by @michitux in #308
=> AllSimplePaths: Removed unused vector and std::move that prevents RVO

include/networkit/distance/APSP.hpp, networkit/cpp/distance/APSP.cpp
This improves the memory footprint of APSP by avoid dynamic allocations when running BFS/Dijkstra
(all the necessary space is allocated once). The new implementation is now 1.5x to 4x faster than the original one.
=> More efficient memory allocation for APSP

include/networkit/graph/GraphTools.hpp, networkit/_NetworKit.pyx, networkit/cpp/graph/GraphTools.cpp, networkit/cpp/graph/test/GraphToolsGTest.cpp
Even though `extractLargestComponent` already exists in `workflows.py`, this algorithm is not available in C++. This commit brings a more efficient C++ implementation of the same algorithm, which can additionally "compact" the graph.
=> New method: extractLargestConnectedComponent

CMakeLists.txt, README.md
This facilitates compiling NetworKit with address/leak sanitizers. The `NETWORKIT_WITH_SANITIZERS` flag can be set to `address` or `leak` to enable the address or address+leak sanitizers. In both cases, the undefined sanitizer is also used.
=> CMake flags for sanitizers

CMakeLists.txt
Non-monolithic build fails using default OSX compiler. While this is clearly a bug on our part, I like to blame the accessory manufacturer (the one selling monitor stands for 1k USD) for not shipping OpenMP ;)
=> Add missing OpenMP dependency for non-monolith tests

include/networkit/distance/SSSP.hpp, networkit/_NetworKit.pyx, networkit/cpp/centrality/EstimateBetweenness.cpp, networkit/cpp/distance/AffectedNodes.cpp, networkit/cpp/distance/SSSP.cpp
The `getDistances()` method of `SSSP` allows the distances vector to be moved out without a clear reason apart from avoiding to copy the vector. This can be done more safely by returning a const ref. The only class using this feature is `AffectedNodes`, which just reads the data.
=> Refactor SSSP getDistances()

include/networkit/distance/BFS.hpp, include/networkit/distance/Dijkstra.hpp, include/networkit/distance/DynBFS.hpp, include/networkit/distance/DynDijkstra.hpp, include/networkit/distance/SSSP.hpp, networkit/cpp/distance/BFS.cpp, networkit/cpp/distance/DynBFS.cpp, networkit/cpp/distance/DynDijkstra.cpp
Removed `virtual` from `run()` methods, removed `@return` docstring from a method returning `void`.
=> Removed useless virtual methods, and misleading docstring

include/networkit/components/ConnectedComponents.hpp, include/networkit/graph/GraphTools.hpp, networkit/_NetworKit.pyx, networkit/cpp/components/ConnectedComponents.cpp, networkit/cpp/components/test/ConnectedComponentsGTest.cpp, networkit/cpp/graph/GraphTools.cpp, networkit/cpp/graph/test/GraphToolsGTest.cpp, networkit/test/test_algorithms.py
Fixes issue #340 by moving `extractLargestComponent` from `GraphTools` to `ConnectedComponent`. As a bonus, there are now also Python Test for the interface and const methods in `ConnectedComponent`.
CI Homebrew issue still causing one test to fail.
=> Move extractLargestConnectedComponent to component

docs/DevGuide.rst, docs/notebooks.rst, extrafiles/sphinx-style/_templates/layout.html, networkit/__init__.py
This updates all the links from the previous networkit github address `kit-parco/networkit` to `networkit/networkit`.
=> Update links: 'kit-parco' -> 'networkit'

.travis.yml, CMakeLists.txt, appveyor.yml
As discussed in issue #340, we should build (and execute) non-monolithic tests. This PR introduces these tests of Linux, OSX and Windows. On Travis we have one more configuration in the matrix, on AppVeyor two more.
=> Include building of non-monolithic test in CI

include/networkit/centrality/DynBetweenness.hpp, networkit/cpp/centrality/DynBetweenness.cpp
As pointed out in https://github.com/kit-parco/networkit/issues/339#issuecomment-503593708 the input graph of `DynBetweenness` is a (non-const) reference, but it should be const.
=> DynBetweenness: Take graph as a const ref

networkit/cpp/io/test/IOGTest.cpp
Tests for the `NetworkitBinaryReader/Writer` are not executed due to wrong naming.
This fixes the test names so they are executed with the `ctest` command.
=> Fix IOGTests

CMakeLists.txt
As discussed in #347, symlinks are not required anymore. Since they're not supported on all platforms anyhow, let's not create them anymore.
=> Remove creation of symlinks

include/networkit/graph/Graph.hpp, include/networkit/io/NetworkitBinaryGraph.hpp, include/networkit/io/NetworkitBinaryReader.hpp, include/networkit/io/NetworkitBinaryWriter.hpp, networkit/cpp/graph/Graph.cpp, networkit/cpp/io/NetworkitBinaryGraph.md, networkit/cpp/io/NetworkitBinaryReader.cpp, networkit/cpp/io/NetworkitBinaryWriter.cpp
1. The file format needed to be changed, as we need to save two prefix sums per directed graphs; one for the in edges and one for the out edges.
2. Directed graphs are now supported
3. We can now read in parallel
=> Support for directed graphs in NetworkitBinaryGraph file format

CMakeLists.txt, networkit/cpp/Unittests-X.cpp
Printing the source location of all debugging messages is incredibly annoying when developing code via TDD in NetworKit, leading to very long lines:
```
[...]
[INFO ][/home/avdgrinten/Projects/networkit/networkit/cpp/centrality/GroupCloseness.cpp, 130: virtual void NetworKit::GroupCloseness::run()]: maxD = 3
[INFO ][/home/avdgrinten/Projects/networkit/networkit/cpp/centrality/GroupCloseness.cpp, 176: virtual void NetworKit::GroupCloseness::run()]: Extracted node 7 with prio 0
[INFO ][/home/avdgrinten/Projects/networkit/networkit/cpp/centrality/GroupCloseness.cpp, 176: virtual void NetworKit::GroupCloseness::run()]: Extracted node 2 with prio 0
[INFO ][/home/avdgrinten/Projects/networkit/networkit/cpp/centrality/GroupCloseness.cpp, 192: virtual void NetworKit::GroupCloseness::run()]: New …
```
=> gtest wrapper: Do not print source location by default

include/networkit/generators/EdgeSwitchingMarkovChainGenerator.hpp, include/networkit/generators/HyperbolicGenerator.hpp, include/networkit/generators/LFRGenerator.hpp, include/networkit/generators/PubWebGenerator.hpp, include/networkit/generators/RegularRingLatticeGenerator.hpp, include/networkit/generators/StaticDegreeSequenceGenerator.hpp, include/networkit/generators/StochasticBlockmodel.hpp, include/networkit/generators/WattsStrogatzGenerator.hpp
The `@ingroup` attribute was missing for a number of generators. Hence they were not listed in the documentation in the Generator module.
I also added two ToDo requesting code clean up out-of-scope for this PR.
=> Add InGroup annotations to generators

networkit/cpp/io/test/IOGTest.cpp
In `IOGTest` the `NetworkitBinaryWriter` should write the output files in `output` instead of `input`, as files in `input` are tracked.
=> IOGtest: NetworkitBinaryWriter writes in outpu/ instead of input/

include/networkit/centrality/Betweenness.hpp, networkit/cpp/centrality/Betweenness.cpp
As already done with `Closeness` and `APSP`, this improves the memory efficiency of `Betweenness` by allocating the necessary memory once per each thread.
=> Refactor betweenness

networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/test/GraphGTest.cpp
This fixes a bug in the `Graph::removeNode` method, which sometimes fails to remove all incident edges to the node to be removed. The new tests included in this PR failed with the old `removeNode` method.
=> Fix removeNode

include/networkit/Globals.hpp, include/networkit/algebraic/MatrixTools.hpp, include/networkit/algebraic/Vector.hpp, include/networkit/algebraic/algorithms/AlgebraicSpanningEdgeCentrality.hpp, include/networkit/numerics/LAMG/MultiLevelSetup.hpp, include/networkit/numerics/LAMG/SolverLamg.hpp, include/networkit/viz/Octree.hpp, networkit/cpp/viz/MaxentStress.cpp
This PR does the following:
- Move `PI` from global namespace into `NetworKit`
- Remove case distinction for the definition of `PI` and always use constant
- Use "using" rather than "typedef"
- Define constexpr debug to be used rather than `NDEBUG`. It also has the advantage that we can shadowing to selectively put module into debug mode.
- Remove now unused `#include <cmath>` from Globals and add it to headers where it's actually used.
=> Modernize Globals.hpp

networkit/_NetworKit.pyx
If you read the implementation for the second time to understand the parameters, it's time to add a docstring.
(also fixes the documentation of `ThrillGraphBinaryWriter.write`)
=> Add docstring to EdgeListReader

include/networkit/auxiliary/Log.hpp, include/networkit/auxiliary/Timer.hpp, networkit/cpp/auxiliary/Log.cpp, networkit/cpp/auxiliary/Timer.cpp, networkit/cpp/auxiliary/test/AuxGTest.cpp, networkit/cpp/distance/test/DistanceGTest.cpp
Clang rightfully complained about `Aux::Timer` not having a virtual destructor.While fixing this, I spotted a number of additional issues, justifying a PR on its own.
This PR includes:
- A virtual destructor for Timer
- Most of Timer's methods are now `const` and `nothrow` (where applicable)
- A unit test for Timer
- A bug fix for `elapsedMicroseconds()` and `elapsedNanoseconds()`: The documentation stated that `elapsed*()` methods returned the time elapsed since the start and now (if Timer is still running) or
between start and stop if the Timer was stopped. `elapsed()` and `elapsedMilliseconds()` behaved that way, while `elapsedMicroseconds()` and `elapsedNanoseconds()` only considered the latter case.
- Timer defined the macro `my_steady_clock`. While this should have been a `using` …
=> Fix issues in Aux::Timer

include/networkit/graph/Graph.hpp, include/networkit/io/NetworkitBinaryGraph.hpp, include/networkit/io/NetworkitBinaryWriter.hpp, networkit/cpp/graph/Graph.cpp, networkit/cpp/io/NetworkitBinaryGraph.md, networkit/cpp/io/NetworkitBinaryReader.cpp, networkit/cpp/io/NetworkitBinaryWriter.cpp, networkit/cpp/io/test/IOGTest.cpp
This PR adds support for weights in the NetworkitBinaryGraph format. 
Unsigned, signed, float and double weights are supported, and can be passed to the writer as a constructor parameter. If none is passed, the writer tries to detect the type of the weights.
The `addPartial*Edge` functions of the graph were slightly modified too i.e., the order of the function parameters `uint64_t index = 0, edgeweight ew = defaultEdgeWeight` was exchanged. This was necessary because the NetworkitBinaryGraph format does not support indexes, and therefore, the default `index` value should be used.
=> Add support for weights in the NetworkitBinaryGraph format. 

include/networkit/graph/Graph.hpp, networkit/cpp/graph/Graph.cpp
This PR adds the following slight modifications to the `Graph` class:
- `Graph::addPartialOutEdge` now uses the passed `index` parameter.
- Add the `index` parameter to the doxygen documents of all `Graph::addPartial*Edge` functions.
=> Resolve issue #364

networkit/graphio.py
When the `SNAPGraphReader` or `SNAPGraphWriter` are called from Python, `graphio.py` calls the `EdgeListReader` or `EdgeListWriter`.
This PR changes that, and `graphio.py` now calls the `SNAPGraphReader` and `SNAPGraphWriter`.
=> Use SNAPGraphReader/Writer

networkit/_NetworKit.pyx, networkit/cpp/generators/ErdosRenyiGenerator.cpp
This fixes an oversight on my part in PR #221. Amongst others, #221 added the `selfLoop` flag to the CPP interface of the `ErdosRenyiGenerator`, but did not adapt the Cython interface accordingly. It defaults to `False` which was the previous behaviour. 
The core library now also throws an exception if self-loops are requested for undirected graphs -- which is not supported by the generator.
=> Add selfLoops flag to Python's ErdosRenyiGenerator

networkit/cpp/centrality/ApproxGroupBetweenness.cpp
This improves the implementation of `ApproxGroupBetweenness`. It avoids the expensive call to `getPaths`, and samples a random path with backtracking.
=> Refactor: ApproxGroupBetweenness

.travis.yml
Both sanitizers and coverage need the default gcc version to work. Instead of having two different builds for the same compiler, it could make sense having a single build for both.
=> Travis: same build for sanitizers and coverage 

networkit/cpp/io/NetworkitBinaryReader.cpp, networkit/cpp/io/NetworkitBinaryWriter.cpp, networkit/cpp/io/test/IOGTest.cpp
This PR fixes a bug in the NetworkitBinaryGraph format in which self loops where counted twice, instead of once, thus falsifying the number of self loops in graphs with self loops. This PR also includes tests for graphs with self loops.
=> Fix self loop bug in NetworkitBinaryGraph

include/networkit/graph/Graph.hpp, networkit/_NetworKit.pyx, networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/test/GraphGTest.cpp, networkit/test/test_graph.py
This adds a new method that removes all the multi-edges from a NetworKit graph.
The same code is also used to remove all the self-loops, as the previous implementation was using `removeNode` within a `forEdges` loop, which shall not be allowed according to #378.
=> New Graph method: remove multi-edges

networkit/_NetworKit.pyx, networkit/test/test_graph.py
This fixes a bug in the `Graph.neighbors()` method. The current implementation returns the error:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "networkit/_NetworKit.pyx", line 922, in networkit._NetworKit.Graph.neighbors
self.forEdgesOf(u, lambda v : neighborList.append(v))
File "networkit/_NetworKit.pyx", line 1019, in networkit._NetworKit.Graph.forEdgesOf
self._this.forEdgesOf[EdgeCallBackWrapper](u, dereference(wrapper))
RuntimeError: An Exception occurred, aborting execution of iterator: lambda() takes exactly one argument (4 given)
```
because the lambda does not have enough parameters (1 instead of 4), and cannot be used by external users.
=> Fix number of parameters in Graph/neighbors

networkit/_NetworKit.pyx, notebooks/GraphNotebook.ipynb
This PR adds a new Jupyter-notebook for the `NetworKit::Graph` class. The notebook addresses
- creating a graph,
- modifying the graph and,
- the node/edge the iterators.
While at it, I also added some documention to the GraphTools module functions I came accross.
=> NetworKit::Graph tutorial with Jupyter-Notebook

networkit/cpp/graph/Graph.cpp, networkit/test/test_graph.py
The current  `Graph.transpose` function uses a GraphBuilder to copy the input graph into a transposed instance. By doing so it loses edge indices.
The new variant use the new awesome `preallocateDirected` and `addPartial*Edge` interface to directly create the new graph -- in parallel, without random I/O, and preserving edge ids. In one instance with ~110k nodes and ~60M edges to runtime decreased from `356s` to just under `6s`.
The PR also removes the `Graph.cpp` -> `GraphBuilder.hpp` dependency and adds a unit test for the Python interface.
=> Faster Graph::transpose

networkit/_NetworKit.pyx
`Closeness` takes a third parameter which can be either `bool` or `ClosenessVariant`. Some users did not find the documentation clear enough, this explains more clearly how this class works.
=> Better documentation for Closeness

networkit/_NetworKit.pyx, notebooks/Components.ipynb
This PR adds a new Jupyter-notebook for the `components` module; most algorithms in the module are covered. I made minor changes to the documentation too.
=> Jupyter Notebook for the components module

.travis.yml, include/networkit/io/NetworkitBinaryGraph.hpp, include/networkit/io/NetworkitBinaryReader.hpp, include/networkit/io/NetworkitBinaryWriter.hpp, networkit/cpp/io/CMakeLists.txt, networkit/cpp/io/NetworkitBinaryReader.cpp, networkit/cpp/io/NetworkitBinaryWriter.cpp, networkit/cpp/io/test/IOGTest.cpp
UBSAN was complaining about both encodings used in NKBG. As all related routines were private methods to the Reader and Writer, I first moved the implementation into the `nkgb` namespace and added unit tests -- checking that `x == decode(encode(x)`). Unfortunately both failed.
While zigzagEncode was very similar to [a GitHub gitst](https://gist.github.com/mfuerstenau/ba870a29e16536fdbaba), our implementation uses 64bit rather than 32bit integers leading to different constants. Additionally in C++ a left shift of signed ints is UB, while a right shift is implementation specific. I believe that my fix avoids both issues. Also the expression is more complicated GCC and CLANG yield the intended assembly of three instructions.
The implementation of the (de)serialization of varints had corner …
=> Fix VarInt and Zigzag coding of NKBG

include/networkit/graph/Graph.hpp, networkit/_NetworKit.pyx, networkit/test/test_graph.py
The `NeighborRange` iterator is wrapped, and we introduce an equivalent iterator in Python - `iterNeighbors(node u)`. Currently, it is only available for undirected, unweighted graphs.
The current iterators, `forEdges*` or `forNodes*`, require a callback function and are not necessarily intuitive to use for all users. The `iterNeighbors(node u)` iterator is simple to use and pythonic .
Let me briefly explain the changes made in `Graph.hpp`.
- Addition of a default no parameter constructor: Cython needed a default contructor.
- `Const node u` -> `node u`: When using the new default constructor, it should be possible to assign a value to `node u` later. This is not possible is `node u` is declared as `const`.
- `Graph& -> Graph*`: Again, this is because of the new constructor.
- …
=> Python wrapper for the C++ NeighborRange iterator

networkit/_NetworKit.pyx, notebooks/Centrality.ipynb
This PR adds a new Jupyter-notebook for the centrality module. It covers most of the algorithms on
- Betweenness Centrality,
- Closeness Centrality,
- the PageRank Centrality algorithms,
- and the Degree Centrality algorithm.
All dynamic and group centrality algorithms were intentionally excluded from this notebook.
I made minor changes to the documentation too.
=> Jupyter Notebook for the centrality module

include/networkit/graph/Graph.hpp, networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/test/GraphGTest.cpp, networkit/test/test_graph.py
This PR includes:
- Fix: Previously `Graph::randomEdges()` used `std::random_device` to seed its own `std::default_random_engine`. This obviously leads to non-reproducible tests. We now use the generator obtained via `Aux::Random::getURNG()`.
- Improvement: Previously `Graph::randomEdge()` used `Graph::randomEdges(1)` to obtain a single edge uniformly at random. This is highly suboptimal, since `Graph::randomEdges` uses `std::discrete_distribution` which builds a costly Theta(n) data structure -- this effort cannot be amortized when only sampling a single edge. This PR hence uses a single linear scan over the graph. In (maybe unrepresentative) measurements, the new implementation is more than an order of mag. faster.
- Adds CPP and Python unit tests
=> Fix Graph::randomEdges and Accelerate Graph::randomEdge

include/networkit/graph/Graph.hpp, networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/test/GraphGTest.cpp
This PR fixes a bug in `removeMultiEdges`: If a node has multiple self-loops, and the graph is undirected, `removeMultiEdges` counts self-loop removals twice, and therefore the edge count is updated wrongly.
I dislike that to do this fix the return value of `removeAdjacentEdges` is changed because we need to distinguish between removed non-self-loop edges and removed self-loops. If we want to avoid this, I am open to suggestions.
=> Handle multiple self-loops removal

CMakeLists.txt, setup.py
This adds the possibility to add rpath to both setup.py and cmake. Use case: consecutive packages (python -> C++ external-core) in build systems like spack, which make heavy usage of rpath-manipulation.
=> Added rpath support for setup.py and consequetive cmake build system.

include/networkit/centrality/KadabraBetweenness.hpp, networkit/cpp/centrality/KadabraBetweenness.cpp
This patch series applies a small fix to KADABRA (first commit), refactors memory orderings that are unnecessarily strong (second commit) and adds tuned parameters from our EUROPAR'19 paper that considerably improve performance (third commit).
=> KADABRA: Add tuned parameters from EUROPAR'19 paper

notebooks/Randomization.ipynb
This PR adds a new jupyter-notebook for the `randomization` module. There are no links to the mentioned functions because I didn't find the randomization module in the [Python documentation](https://networkit.github.io/dev-docs/python_api/modules.html).
=> Jupyter-notebook for randomization module

include/networkit/algebraic/algorithms/AlgebraicPageRank.hpp, include/networkit/algebraic/algorithms/AlgebraicTriangleCounting.hpp, include/networkit/centrality/Centrality.hpp, include/networkit/distance/SSSP.hpp, networkit/_NetworKit.pyx, networkit/cpp/algebraic/algorithms/test/AlgebraicTriangleCountingGTest.cpp, networkit/cpp/centrality/Centrality.cpp
Some NetworKit classes provide a `moveOut` parameter that, if set true, should move the content of a vector outside the class. However, as @avdgrinten commented in https://github.com/networkit/networkit/pull/334#discussion_r292924992, move-out parameters cannot work as expected.
This PR deprecates all methods using `moveOut`, and provides alternative methods that return a const ref. to the vector.
=> Fix: move out parameters

networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/test/GraphGTest.cpp
Most of the functions to remove edges did not take edge ids into account. This results in ever growing graphs and -- even worse -- changing edge ids.
=> Fix Remove Edge

networkit/cpp/auxiliary/Log.cpp
Logging to `stdout` is annoying, especially if `stdout` is piped to a consumer that programmatically extracts information from the output.
=> logging: Always log to `stderr`

include/networkit/graph/Graph.hpp, networkit/_NetworKit.pyx, networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/test/GraphGTest.cpp, networkit/test/test_graph.py
This PR includes three related changes:
- The logic of `Graph::addNode` was broken (e.g. it pushed to `inEdgeWeights` for undirected graphs) and inefficent (rather than using `outEdges.emplace_back()`, first an empty vector was created and then pushed). Both is fixed now.
- To add multiple nodes (required by next point), the method Graph::addNodes(k) was added which performs resizes rather than repeated emplace_backs.
- As discussed in #419, there are no boundary checks for Python's Graph.addEdge(u, v). Thus adding an edge to a non-existing node corrupts memory and (in the best-case) leads to a SegFault. While this is common for C++ interfaces, boundary checks are expected in Python interfaces. Hence, now an exception is thrown. Additionally `addEdge` has now the optional flag …
=> Fix Graph::addNode, Add Graph::addNodes, Guard Python Graph.addEdge

include/networkit/viz/Octree.hpp, include/networkit/viz/Point.hpp
This removes implementations of a copy constructor and an assignment
operator in viz/Octree and Point because if one implementation is
provided, the other (assignment operator/copy constructor) must be
provided, too. As far as I can see, none of the implementations did
anything non-default, so I reverted both to default implementations.
=> Fix deprecation warnings with GCC 9.2

networkit/graphio.py, networkit/test/test_graphio.py
As pointed out in the mailing list, Python's graphio interfaces `graphio.readGraph` and `graphio.writeGraph` require the user to provide arguments to the EdgeList reader/writer. Error messages get lost in an unnecessary `try ... except` block which is removed by this PR.
We also fix two bugs in the logic regarding `EdgeList`: While the `EdgeList` interface has to *optional* parameter `continuous`, it was required by the `readGraph` interface. This is not the case anymore. Additionally, the required `separator` and `firstNode` parameters have to be passed as positional arguments. Hence this PR add `*kargs` to readGraph/writeGraph.
It also adds a very simple unittest that tries for each format to write and read a graph again. This surprisingly failed for three Formats (SNAP, GEXF and MAT). …
=> Fix graphio.readGraph / graphio.writeGraph

include/networkit/centrality/Closeness.hpp, networkit/cpp/centrality/Closeness.cpp, networkit/cpp/centrality/test/CentralityGTest.cpp
This PR brings the following changes:
- Parametrization of `CentralityGTests` for weighted/directed graphs: the code for some tests was copy-pasted to test directed/undirected, weighted/unweighted graphs. With parametrization we can use the same code once for all of those cases.
- Additional tests for all `TopCloseness` heuristics.
- Fix a bug in `Closeness` for weighted graphs (wrong scores were not detected due to lack of tests).
=> Refactor: CentralityGTest and fix in Closeness

include/networkit/generators/BarabasiAlbertGenerator.hpp, networkit/cpp/generators/BarabasiAlbertGenerator.cpp, networkit/cpp/generators/test/GeneratorsGTest.cpp, notebooks/test_notebooks.py
The default implementation of the Barabasi Albert Generator (due to Batagelj and Brandes) was buggy, inefficient and unnecessarily complicated (rather than using push_back on a vector, the index was (wrongly) computed each time). This PR tries to resolve it:
- Originally the index computation miscalculated the edges from the initial seed graph. This led to reads from uninitialized memory or to overwriting the parts of the seed graph
- The original implementation maintained an vector `M` (required for constant time sampling), a set of produced edges and a graph G. The new implementation exploits the fact that only the $k$ most recent additions can lead to parallel edges and hence does not require the set.
- The original implementation removed duplicated edges, changing the degree …
=> Fix BarabasiAlbertGenerator

networkit/cpp/graph/Graph.cpp
Note that "id" is a member variable that contains the id of the graph.
=> Graph::addEdge: fix directed in-edge getting the wrong id

include/networkit/components/BiconnectedComponents.hpp, include/networkit/components/ConnectedComponents.hpp, include/networkit/components/DynConnectedComponents.hpp, include/networkit/components/DynWeaklyConnectedComponents.hpp, include/networkit/components/ParallelConnectedComponents.hpp, include/networkit/components/RandomSpanningForest.hpp, include/networkit/components/StronglyConnectedComponents.hpp, networkit/cpp/components/BiconnectedComponents.cpp, networkit/cpp/components/ConnectedComponents.cpp, networkit/cpp/components/DynConnectedComponents.cpp, networkit/cpp/components/DynWeaklyConnectedComponents.cpp, networkit/cpp/components/ParallelConnectedComponents.cpp, networkit/cpp/components/StronglyConnectedComponents.cpp
This PR brings some improvements to the C++ code of the components module. The changes include:
- All classes that are not inherited from are made final.
- The `virtual` keyword is removed from any non-base classes.
- All __member__ variables are changed from references to pointers. The point of this is to make classes assignable.
- The `override` keyword is added to functions accordingly.
=> Refactor components module

networkit/_NetworKit.pyx, notebooks/GroupCentrality.ipynb
This PR adds a new jupyter-notebook for the group centrality algorithms. I made minor changes to the documention as well as imported the `scoreOfGroup` function of the ApproxGroupBetweenness class to Python.
=> Jupyter-notebook for the group centrality algorithms

include/networkit/algebraic/CSRMatrix.hpp, include/networkit/algebraic/DenseMatrix.hpp, include/networkit/algebraic/DynamicMatrix.hpp, include/networkit/algebraic/Semirings.hpp, include/networkit/algebraic/SparseAccumulator.hpp, include/networkit/algebraic/Vector.hpp, networkit/cpp/algebraic/CSRMatrix.cpp, networkit/cpp/algebraic/DenseMatrix.cpp, networkit/cpp/algebraic/Vector.cpp
This PR brings some improvements to the C++ code of the algebraic module. The changes include:
- All classes that are not inherited from are made final.
- The virtual keyword is removed from any non-base classes.
- Public functions passing `const value types` are changed to value types.
=> Refactor algebraic module

notebooks/Distance.ipynb, notebooks/GraphNotebook.ipynb, notebooks/User-Guide.ipynb
This PR adds some examples for the `GraphTools` class in the Graph notebook.
While at it, I updated the notebooks that were using the newly deprecated functions.
=> Add GraphTools to Graph Notebook and update other notebooks

notebooks/LinkPrediction.ipynb
This PR adds a new jupyter-notebook for the `linkprediction` module.
=> Jupyter-notebook for linkprediction module

include/networkit/algebraic/algorithms/AlgebraicMatchingCoarsening.hpp, include/networkit/clique/MaximalCliques.hpp, include/networkit/coarsening/ClusteringProjector.hpp, include/networkit/coarsening/GraphCoarsening.hpp, include/networkit/coarsening/MatchingCoarsening.hpp, include/networkit/coarsening/ParallelPartitionCoarsening.hpp, include/networkit/correlation/Assortativity.hpp, networkit/cpp/clique/MaximalCliques.cpp, networkit/cpp/coarsening/ClusteringProjector.cpp, networkit/cpp/coarsening/GraphCoarsening.cpp, networkit/cpp/coarsening/MatchingCoarsening.cpp, networkit/cpp/coarsening/ParallelPartitionCoarsening.cpp, networkit/cpp/correlation/Assortativity.cpp
This PR includes:
- All classes that are not inherited from are made final.
- The `virtual` keyword is removed from any non-base classes.
- All __member__ variables are changed from references to pointers.
- The `override` keyword is added to functions accordingly.
- The access modifiers of member variables is changed from protected to private.
- The documentation in the header files is changed from `*.h` to `*.hpp`.
=> Refactor: clique, coarsening, correlation

networkit/_NetworKit.pyx, networkit/test/test_graph.py
This PR fixes the bug in the Python code of `Graph.inNeighbors` described in #469. It also includes new Python tests for `inNeighbors`.
=> Fix inNeighbors

CMakeLists.txt
Enables option -DNETWORKIT_EXT_TLX=<TLX-DIR> in case an external version of tlx is used.
=> Added cmake option for adding externally build tlx lib

include/networkit/auxiliary/Parallelism.hpp, include/networkit/numerics/LAMG/Lamg.hpp, networkit/_NetworKit.pyx, networkit/__init__.py, networkit/cpp/Unittests-X.cpp, networkit/cpp/auxiliary/Parallelism.cpp, networkit/cpp/distance/NeighborhoodFunctionApproximation.cpp
In this PR the `enableNestedParallelism` function is deprecated.
=> Address issue #489: Deprecate enabling nested parallelism

.travis.yml
PR #487 fixed travis warnings, but may have introduced an error in the documentation builds.
This PR tries to fix that by explicitly stating which version of travis should be used i.e., the most recent release.
Some relevant links:
[https://blog.travis-ci.com/2019-10-24-build-config-validation](https://blog.travis-ci.com/2019-10-24-build-config-validation)
[https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release](https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release)
=> Revert travis to skip-cleanup

CMakeLists.txt
If one is using llvm clang, this error message is wrong. This PR corrects the compiler name in the error message when libomp is not found.
=> Fix CMake error message

include/networkit/viz/GraphLayoutAlgorithm.hpp
There are appears to be a mistake in how GML is written in 3D. See https://github.com/networkit/networkit/issues/500
=> Fix inconsistency in scaling z-coordinate for writeGraphToGML

include/networkit/components/ConnectedComponents.hpp, networkit/cpp/components/ConnectedComponents.cpp, networkit/cpp/components/test/ConnectedComponentsGTest.cpp
This PR fixes a bug in `extractLargestConnectedComponents`: connected graphs are never compacted, even if `compactGraph` is set to true. Additional tests for this scenario are also included.
=> Fix extract largest cc

.travis.yml
This should fix the build-errors for travis for macOS 10.14 clang/llvm8[1]. 
[1] https://travis-ci.community/t/macos-build-fails-because-of-homebrew-bundle-unknown-command/7296/10
=> Fix travis error for macOS

CHANGES.md, CONTRIBUTING.md
In contrast to the earlier PR #330, this PR does not modify the README. Instead, we state our contribution guidelines and other policies in a `CONTRIBUTING.md` file. We also add a `CHANGES.md` file to document API breaking changes.
The `CONTRIBUTING.md` should reflect the status quo of our policies (i.e., as discussed at our meeting in Freiburg).
I plan to remove the old `DevGuide.rst` (which IMO does not contain useful information) and drop the relevant sections of the `README.md` in a separate PR.
=> Add contribution guidelines

CMakeLists.txt
This changes how OpenMP is handled during cmake-phase. Tested for cmake 3.11, 3.13 and 3.15 on Linux (Ubuntu, CentOS) and macOS for both native and conda-environments (+ brew for macOS).
=> Refactor OpenMP library import during cmake

networkit/algebraic.py
Comparing to literals with `is` issues a syntax warning in python 3.8.
```sh
/home/cqql/src/networkit/networkit/algebraic.py:32: SyntaxWarning: "is" with a literal. Did you mean "=="?
if matrixType is "sparse":
/home/cqql/src/networkit/networkit/algebraic.py:34: SyntaxWarning: "is" with a literal. Did you mean "=="?
elif matrixType is "dense":
/home/cqql/src/networkit/networkit/algebraic.py:56: SyntaxWarning: "is" with a literal. Did you mean "=="?
if matrixType is "sparse":
```
Best,
Marten
=> Use == to compare against literals

networkit/profiling/profiling.py
This PR fixes a bug that caused `ModuleNotFoundError` when IPython isn't installed. Instead, a `MissingDependencyError` is thrown as IPython is not a requirement of NetworKit.
=> Throw MissingDependencyError when IPython is not available

networkit/__init__.py
Hey,
at the moment `import networkit` modifies the global logging setup. In particular, it reduces the default logging level from `WARNING` to `INFO`. I noticed this when I imported networkit and suddenly other packages started logging. Importing a package should have no side effects. If this log level is somehow essential to networkit, `setup` should set it only for a package specific root logger.
Best,
Marten
=> Importing networkit should not modify the global logging configuration

networkit/test/test_community.py, networkit/test/test_sparsification.py
The `test_sparsification` and `test_community` unit tests lack a `main` method.
This PR just adds a `main` method so that the tests are executed.
=> Add main to Python sparsification and community unit tests

CMakeLists.txt
While this is a three-line change only, please check it careful.
The underlying issue it addresses, is that if a third-party application links against NetworKit and includes headers (e.g. for Graph), the application requires TLX in its search paths. 
The solution proposed here is to export this dependency via the `networkit` library (and it non-monolithic counterparts).
=> Include TLX as a public library

.gitignore
When building networkit a `lib64` directory is created, I think we should ignore it as well as `lib`.
=> Ignore lib64 in .gitignore

include/networkit/centrality/TopCloseness.hpp, networkit/cpp/centrality/TopCloseness.cpp, networkit/test/test_algorithms.py
This brings some improvements to `TopCloseness`:
- Instead of `Aux::PrioQueue`s (i.e., rb-trees), now it uses heaps.
- Update tlx to use `build_heap`: this allows to build `Q` in `O(n)` instead of `O(n*logn)`
- When `sec_heu` is set to `false`, the algorithm does not allocate `O(n)` memory at every iteration, but pre-allocates it beforehand.
- Uses a `unique_ptr<StronglyConnectedComponents>`  to avoid copying the `components` vector. This saves `O(n)` memory.
- Tracking of "trailing" nodes is simpler and more efficient.
- Simpler GTests.
=> Refactor: top-closeness

include/networkit/graph/Sampling.hpp
`Sampling.hpp` defines three methods that are already implemented within GraphTools, and never used in NetworKit (after we merge #421). I think we should deprecate them now, and remove `Sampling` in future releases.
=> Deprecate Sampling

.clang-tidy, .travis.yml, CMakeLists.txt
[clang-tidy](https://clang.llvm.org/extra/clang-tidy/index.html) is a very powerful tool to detect programming errors that are generally not detected by compilers, and it is easy to integrate with CMake.
I think that it would be a good idea to integrate it into our CI system: it would help us fixing existing programming errors (such as the ones fixed recently by @cndolo), and avoiding introducing new ones in future PRs.
If you agree with that, we might want to discuss about which [checks](https://clang.llvm.org/extra/clang-tidy/checks/list.html) should we use.
=> clang-tidy

include/networkit/centrality/ApproxSpanningEdge.hpp, include/networkit/graph/Graph.hpp, networkit/_NetworKit.pyx, networkit/centrality.py, networkit/cpp/centrality/ApproxSpanningEdge.cpp, networkit/cpp/centrality/CMakeLists.txt, networkit/cpp/centrality/test/CentralityGTest.cpp, networkit/test/test_algorithms.py, notebooks/Centrality.ipynb
This PR brings a parallel implementation of the [Hayashi et al. algorithm](https://www.ijcai.org/Proceedings/16/Papers/525.pdf) for spanning edge centrality approximation.
To make the algorithm more efficient, this PR also includes a new function `Graph::getIthNeighborWithId` that returns the ith neighbor of a node `u` together with the id of the edge `(u, v)`. This is faster than using `Graph::getIthNeighbor` and retrieving the edge id with `Graph::edgeId`.
=> New algorithm: Spanning Edge Centrality Approximation

networkit/workflows.py
This PR deprecates the Python function `workflows.extractLargestComponent` as the same algorithm is already implemented in C++ in `ConnectedComponents::extractLargestConnectedComponent`.
=> Deprecate workflows.extractLargestComponent

.clang-tidy, networkit/cpp/distance/EffectiveDiameter.cpp
Fix rounding by using [std::round](https://en.cppreference.com/w/cpp/numeric/math/round), which provides the same behavior but it is safer (as reported [here](https://clang.llvm.org/extra/clang-tidy/checks/bugprone-incorrect-roundings.html)).
=> warning fix: clang-tidy/bugprone-incorrect-roundings

.clang-tidy, networkit/cpp/community/CutClustering.cpp
Replace wrong behavior with an assertion, and fix `bugprone-use-after-move` warning.
=> warning fix: clang-tidy/bugprone-use-after-move

include/networkit/components/StronglyConnectedComponents.hpp, include/networkit/graph/Graph.hpp, networkit/_NetworKit.pyx, networkit/cpp/centrality/TopCloseness.cpp, networkit/cpp/centrality/TopHarmonicCloseness.cpp, networkit/cpp/centrality/test/CentralityGTest.cpp, networkit/cpp/components/StronglyConnectedComponents.cpp, networkit/cpp/components/test/ConnectedComponentsGTest.cpp, networkit/test/test_algorithms.py, notebooks/Components.ipynb
This PR brings a cleaner implementation of Tarjan's algorithm for strongly connected components.
It also removes the deprecated method `getIthNeighbor` in Graph that was designed specifically for StronglyConnectedComponents to return the (deg(v) - i)-th neighbor of a node v (using neighbor iterators this operation is not needed anymore).
Furthermore, it includes more extensive C++ tests, and basic Python tests.
=> Refactor: Strongly Connected Components

networkit/cpp/centrality/ApproxSpanningEdge.cpp
Fix clang-tidy use-after-move error in `ApproxSpanningEdge`.
=> Fix use-after-move

networkit/cpp/io/NetworkitBinaryWriter.cpp, networkit/cpp/io/test/IOGTest.cpp
The current auto detection code chooses the positive varint storage format for unweighted graphs. Fix the detection to not store weights at all.
=> NetworKit binary graphs: Fix weight auto detection for unweighted graphs

include/networkit/centrality/GedWalk.hpp, networkit/_NetworKit.pyx, networkit/centrality.py, networkit/cpp/centrality/CMakeLists.txt, networkit/cpp/centrality/GedWalk.cpp, networkit/cpp/centrality/test/CentralityGTest.cpp, networkit/test/test_algorithms.py
This PR brings the implementation of the algorithms for GedWalk centrality based on the paper [Group Centrality Maximization for Large-scale Graphs](https://arxiv.org/abs/1910.13874) (ALENEX 2020).
Updating tlx is needed because the algorithms use some features introduced in a newer tlx version.
=> Ged walk centrality

include/networkit/sparsification/GlobalThresholdFilter.hpp, networkit/cpp/edgescores/EdgeScore.cpp, networkit/cpp/sparsification/GlobalThresholdFilter.cpp, networkit/cpp/sparsification/test/CMakeLists.txt, networkit/cpp/sparsification/test/GlobalThresholdFilterGTest.cpp
This PR fixes two main issues:
- Templated methods of `EdgeScore` were implemented in the `.cpp` file. They have been moved to the header file.
- `GlobalThresholdFilter` now also support directed and weighted graphs. In the previous implementation the graph was transformed to an undirected graph with default edgeweights without throwing any warnings or errors. If the input graph is directed, this yields a discrepancy in the number of edges in the resulting graph (as reported in #499).
=> Fix GlobalThresholdFilter

networkit/cpp/randomization/DegreePreservingShuffle.cpp
Currently installing networkit with macOS Catalina 15.04 is not possible due to a bug in Apple Clang 11.03 (clang-1103.0.32.29), leading to a seq-fault in the compiler. While I already filled a bug report, there are related problems in Apple Dev from the past, where these kind of errors may also point to potential problems in the code.
After narrowing down the problem, the seq-fault occurs during `getRemappedGraph` in `DegreePreservingShuffle`. It is fixed by doing a local copy of permutation before accessing it. Should we merge this fix?
[Error on stackoverflow](https://stackoverflow.com/questions/60874746/problems-installing-networkit-with-pip3)
[Error on github](https://github.com/Homebrew/homebrew-core/pull/52078)
=> Fix for Apple Clang 11.03

networkit/cpp/generators/StaticDegreeSequenceGenerator.cpp, networkit/cpp/generators/test/GeneratorsGTest.cpp
`StaticDegreeSequenceGenerator::isRealizable()` uses the Erdős–Gallai theorem to test whether a degree sequence is graphical. The old implementation was a direct translation of the theorem, which involved a sum over all degree which needs to be calculated for each node --- this gave an Theta(n^2) algorithm, and prevented us from using it with n >~ 1e6.
This PR uses the same theorem but carries out straight-forward transformations to reduce the complexity to O(n log n). The main idea is to avoid calculating the same sums again and again. Hence, rather than storing a sorted sequence of degree, we store a their suffix-sums. 
The PR also adds unit tests for this function specifically. The PR has some overlap with the unit tests for HavelHakimi, but checks more cases that are relevant for …
=> Use O(n logn) implemention in StaticDegreeSequenceGenerator

include/networkit/distance/DynSSSP.hpp, include/networkit/distance/SSSP.hpp, include/networkit/distance/STSP.hpp
Based on #533.
Changing `DynSSSP`, `SSSP` and `STSP` to return predecessors by reference instead of by value. NetworKit-code using this function is not influenced by this change, since all occurrences involve deep-copies (if I understand the standard correctly).
=> SSSP/STSP: Changing getPredecessors() to return by-reference

.clang-tidy, include/networkit/centrality/GroupCloseness.hpp, networkit/cpp/coarsening/ParallelPartitionCoarsening.cpp, networkit/cpp/generators/ChungLuGenerator.cpp, networkit/cpp/generators/LFRGenerator.cpp
Fix possible loss of precision of `std::accumulate` due to truncation or overflow.
=> warning fix: clang-tidy/bugprone-fold-init-type

networkit/gephi/streaming.py
This fixes Gephi streaming #536. I took the opportunity to also remove some redundant code and speed up the export of edge attributes by using the iterators with callbacks that get edge ids. The new edge iterators cannot be used for this unfortunately as they do not support edge ids.
=> Fix and improve Gephi streaming client

.clang-tidy, include/networkit/numerics/LAMG/Lamg.hpp, networkit/cpp/centrality/ApproxGroupBetweenness.cpp, networkit/cpp/generators/DynamicDGSParser.cpp, networkit/cpp/io/DGSReader.cpp, networkit/cpp/structures/Partition.cpp
Avoid useless copies in range-based for loops.
=> warning fix: clang-tidy/performance-for-range-copy

.clang-tidy, networkit/cpp/community/GraphClusteringTools.cpp
Avoid implicit promotion from `float` to `double` due to calls to C math library functions.
=> warning fix: clang-tidy/performance-type-promotion-in-math-fn

.clang-tidy, networkit/cpp/distance/Volume.cpp, networkit/cpp/generators/DynamicDGSParser.cpp, networkit/cpp/generators/MocnikGenerator.cpp, networkit/cpp/io/DGSReader.cpp, networkit/cpp/structures/Partition.cpp
Avoid inefficient `push_back` operations.
=> warning fix: clang-tidy/performance-inefficient-vector-operation

.clang-tidy, networkit/cpp/centrality/Betweenness.cpp, networkit/cpp/community/AdjustedRandMeasure.cpp, networkit/cpp/distance/HopPlotApproximation.cpp
Fix integer divisions meant to be floating-point divisions.
=> warning fix: clang-tidy/bugprone-integer-division

include/networkit/distance/SSSP.hpp, networkit/cpp/distance/BFS.cpp, networkit/cpp/distance/Dijkstra.cpp, networkit/cpp/distance/SSSP.cpp
In the current state for `SSSP` (and inherited classes) there exists a `visited` vector, taking care of bookkeeping during runs. For `BFS` and `Dijkstra` this can be exchanged by comparing distances directly and removing the allocation of memory for `visited`. This saves roughly `#nodes * bytes * instances` amount of memory. 
The trade-off is comparing `double` instead of `uint_8`. Doing a quick-bench, this creates (depending on the compiler and flags) very low to none overhead in computational time. 
http://quick-bench.com/BKRXbz_iwoVyzk3W9Px_crliMLM
Thanks for @angriman to bring this up.
=> Reduce memory-footprint for BFS/Dijkstra

.clang-tidy, include/networkit/graph/Graph.hpp, networkit/cpp/graph/Graph.cpp
Remove `const` from return types of value-returning functions.
=> warning fix: clang-tidy/readability-const-return-type

.clang-tidy, include/networkit/centrality/DynApproxBetweenness.hpp, networkit/cpp/auxiliary/SignalHandling.cpp, networkit/cpp/centrality/ApproxBetweenness.cpp, networkit/cpp/centrality/ApproxGroupBetweenness.cpp, networkit/cpp/centrality/DynBetweenness.cpp, networkit/cpp/centrality/DynKatzCentrality.cpp, networkit/cpp/distance/CommuteTimeDistance.cpp, networkit/cpp/distance/EffectiveDiameter.cpp, networkit/cpp/distance/HopPlotApproximation.cpp, networkit/cpp/distance/NeighborhoodFunction.cpp, networkit/cpp/distance/NeighborhoodFunctionApproximation.cpp, networkit/cpp/distance/NeighborhoodFunctionHeuristic.cpp, networkit/cpp/io/NetworkitBinaryReader.cpp, networkit/cpp/io/test/MemoryMappedFileGTest.cpp, networkit/cpp/sparsification/LocalSimilarityScore.cpp, networkit/cpp/sparsification/test/LocalDegreeGTest.cpp, networkit/cpp/viz/test/MaxentStressGTest.cpp
Replace deprecated C standard library headers with their C++ alternatives.
=> clang-tidy auto fix: modernize-deprecated-headers

README.md, networkit/__init__.py, version.py
This brings the README.md and requirements up-to-date.
- ~~Raised min. compiler version for GCC/G++ to 5.1~~
- ~~Aligned compiler versions for testing + documentation (+ removed older versions)~~
- Raised min. Python version to 3.5. 3.4 is EOL since nearly one year and we only test against 3.5
- Raised min. Cython version to 0.29 in order to support Python 3.8 (see #535) 
~~Note: Can't say how important it is, but I could not find a feasible way to choose g++-5.1 instead of g++5 (which should be 5.4) for travis.~~
=> Update README.md and requirements for 7.0

include/networkit/distance/CommuteTimeDistance.hpp, include/networkit/graph/GraphTools.hpp, networkit/_NetworKit.pyx, networkit/cpp/distance/CommuteTimeDistance.cpp, networkit/cpp/graph/GraphTools.cpp
Fixes #447 
The volume of the graph for `distance(u,v)` was computed differently then `runSinglePair(u,v)`, leading to a difference of factor `sqrt(2)` in the results. The update also includes a warning, when the algorithm is called on directed graph.
=> Fix: Commute Time Distance

.clang-tidy, include/networkit/auxiliary/BloomFilter.hpp, include/networkit/auxiliary/BucketPQ.hpp, include/networkit/auxiliary/PrioQueue.hpp, include/networkit/community/DynamicNMIDistance.hpp, include/networkit/community/LPDegreeOrdered.hpp, include/networkit/generators/MocnikGenerator.hpp, include/networkit/linkprediction/LinkPredictor.hpp, include/networkit/sparsification/SimmelianScore.hpp, include/networkit/viz/MaxentStress.hpp, networkit/cpp/auxiliary/test/AuxGTest.cpp, networkit/cpp/centrality/ApproxCloseness.cpp, networkit/cpp/community/PLP.cpp, networkit/cpp/edgescores/EdgeScoreLinearizer.cpp, networkit/cpp/generators/DynamicForestFireGenerator.cpp, networkit/cpp/generators/HavelHakimiGenerator.cpp, networkit/cpp/simulation/EpidemicSimulationSEIR.cpp
Replace `typedef` with `using`.
=> clang-tidy: modernize-use-using

networkit/viztasks.py
The stray comma on that line causes computed node sizes to be passed as a one-tuple containing the desired list instead of the list itself. This makes networkx choke when it tries to access the list of node sizes.
=> Fix node sizes being passed as tuple-of-list

notebooks/User-Guide.ipynb
The parameter controlling node sizes in the `drawGraph` method is named `node_size`, not `nodeSizes`.
=> Fix wrong parameter in user guide

.clang-tidy, include/networkit/algebraic/CSRMatrix.hpp, include/networkit/auxiliary/SortedList.hpp, include/networkit/centrality/ApproxBetweenness.hpp, include/networkit/centrality/ApproxGroupBetweenness.hpp, include/networkit/centrality/Closeness.hpp, include/networkit/centrality/DynApproxBetweenness.hpp, include/networkit/centrality/KadabraBetweenness.hpp, include/networkit/community/CommunityDetectionAlgorithm.hpp, include/networkit/community/PLP.hpp, include/networkit/distance/DynSSSP.hpp, include/networkit/distance/EffectiveDiameterApproximation.hpp, include/networkit/distance/Volume.hpp, include/networkit/generators/DynamicDGSParser.hpp, include/networkit/io/EdgeListReader.hpp, include/networkit/numerics/GaussSeidelRelaxation.hpp, include/networkit/numerics/LAMG/MultiLevelSetup.hpp, include/networkit/numerics/Smoother.hpp, include/networkit/viz/MaxentStress.hpp
Remove `const` from top level parameters in function declarations.
=> warning fix: clang-tidy/readability-avoid-const-params-in-decls

.clang-tidy, include/networkit/auxiliary/PrioQueue.hpp, include/networkit/auxiliary/Random.hpp, include/networkit/centrality/GroupCloseness.hpp, include/networkit/generators/quadtree/QuadNode.hpp, include/networkit/numerics/LAMG/MultiLevelSetup.hpp, include/networkit/viz/GraphLayoutAlgorithm.hpp, include/networkit/viz/Octree.hpp, networkit/cpp/algebraic/CSRMatrix.cpp, networkit/cpp/algebraic/DynamicMatrix.cpp, networkit/cpp/centrality/DynApproxBetweenness.cpp, networkit/cpp/centrality/DynBetweenness.cpp, networkit/cpp/centrality/KadabraBetweenness.cpp, networkit/cpp/community/CoverF1Similarity.cpp, networkit/cpp/distance/AlgebraicDistance.cpp, networkit/cpp/distance/AllSimplePaths.cpp, networkit/cpp/distance/BidirectionalBFS.cpp, networkit/cpp/generators/DynamicDGSParser.cpp, networkit/cpp/generators/DynamicHyperbolicGenerator.cpp, networkit/cpp/generators/MocnikGenerator.cpp, networkit/cpp/graph/GraphBuilder.cpp, networkit/cpp/linkprediction/AlgebraicDistanceIndex.cpp, networkit/cpp/linkprediction/EvaluationMetric.cpp, networkit/cpp/randomization/CurveballImpl.cpp, networkit/cpp/structures/Partition.cpp
Replace calls to `size()` with `empty()` where applicable.
=> clang-tidy: readability-container-size-empty

.clang-tidy, networkit/cpp/centrality/Centrality.cpp, networkit/cpp/centrality/KadabraBetweenness.cpp, networkit/cpp/components/BiconnectedComponents.cpp, networkit/cpp/distance/AllSimplePaths.cpp, networkit/cpp/dynamics/DGSStreamParser.cpp, networkit/cpp/dynamics/GraphUpdater.cpp, networkit/cpp/generators/DynamicDorogovtsevMendesGenerator.cpp, networkit/cpp/generators/DynamicForestFireGenerator.cpp, networkit/cpp/generators/DynamicHyperbolicGenerator.cpp, networkit/cpp/generators/DynamicPathGenerator.cpp, networkit/cpp/generators/DynamicPubWebGenerator.cpp, networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/GraphBuilder.cpp, networkit/cpp/graph/GraphTools.cpp, networkit/cpp/io/METISParser.cpp, networkit/cpp/linkprediction/LinkPredictor.cpp, networkit/cpp/linkprediction/MissingLinksFinder.cpp, networkit/cpp/scd/ApproximatePageRank.cpp
Replace `push_back` with `emplace` where applicable.
=> clang-tidy: modernize-use-emplace

docs/DevGuide.rst
Hi NetworKit Developers,
I recently started looking into the project and found that the DevGuide didn't have up-to-date test instructions (See #249). I've removed the references to scons from the DevGuide and added the information on how to build the test using cmake and how to execute them.
Cheers, 
Christian
=> Remove scons from DevGuide.rst and update test instructions

.clang-tidy
`bugprone-branch-clone` produces false positives if an if-else statement contains a omp parallel loop e.g.:
```
if (something)
#pragma omp parallel
{
// some code
}
else
#pragma omp parallel
{
// some other code         
}
```
triggers the warning, even if the the parallel blocks are different.
=> Remove bugprone-branch-clone check

include/networkit/auxiliary/BucketPQ.hpp, include/networkit/centrality/ApproxGroupBetweenness.hpp, include/networkit/centrality/Closeness.hpp, include/networkit/centrality/DynBetweenness.hpp, include/networkit/centrality/GedWalk.hpp, networkit/cpp/auxiliary/BucketPQ.cpp, networkit/cpp/centrality/ApproxCloseness.cpp, networkit/cpp/centrality/Betweenness.cpp, networkit/cpp/centrality/CoreDecomposition.cpp, networkit/cpp/centrality/DegreeCentrality.cpp, networkit/cpp/centrality/DynBetweenness.cpp, networkit/cpp/centrality/DynKatzCentrality.cpp, networkit/cpp/centrality/DynTopHarmonicCloseness.cpp, networkit/cpp/centrality/EstimateBetweenness.cpp, networkit/cpp/centrality/GedWalk.cpp, networkit/cpp/centrality/HarmonicCloseness.cpp, networkit/cpp/centrality/KPathCentrality.cpp, networkit/cpp/centrality/KadabraBetweenness.cpp, networkit/cpp/centrality/LaplacianCentrality.cpp, networkit/cpp/centrality/PermanenceCentrality.cpp, networkit/cpp/centrality/Sfigality.cpp, networkit/cpp/centrality/TopCloseness.cpp, networkit/cpp/centrality/TopHarmonicCloseness.cpp
I changed the signature of the `BucketPQ::getKey` to `int64_t` because the function now returns an `int64_t`. Other than that none of the changes affect the interface.
=> Auxiliary and centrality modules: cpp-coreguideline-narrowing-conversion 

include/networkit/io/EdgeListReader.hpp, input/README.md, input/alphabet.edgelist, networkit/cpp/io/EdgeListReader.cpp, networkit/cpp/io/test/IOGTest.cpp
This PR refactors the `EdgeListReader` by using memory mapped files as suggested in #584 . The fixes from that PR are included here.
The `EdgeListReader` now handles continuous and non-continuous  edgelists in the same function, no longer needs to read the file twice and follows the style of the `KONECTGraphReader` and `SNAPGraphReader`.
=> Use Memory Mapped Files in EdgeListReader

.clang-tidy, include/networkit/io/NetworkitBinaryGraph.hpp, include/networkit/numerics/Preconditioner/DiagonalPreconditioner.hpp, networkit/cpp/global/ClusteringCoefficient.cpp, networkit/cpp/global/GlobalClusteringCoefficient.cpp, networkit/cpp/linkprediction/AdjustedRandIndex.cpp, networkit/cpp/linkprediction/EvaluationMetric.cpp, networkit/cpp/linkprediction/PrecisionRecallMetric.cpp, networkit/cpp/scd/GCE.cpp, networkit/cpp/sparsification/ChanceCorrectedTriangleScore.cpp, networkit/cpp/sparsification/LocalSimilarityScore.cpp, networkit/cpp/sparsification/MultiscaleScore.cpp, networkit/cpp/sparsification/SCANStructuralSimilarityScore.cpp, networkit/cpp/viz/MaxentStress.cpp
`cppcoreguideline-narrowing-conversion` fixes for the aforementioned modules.
This is the last batch of fixes, hence narrowing conversions are now marked as errors in the `.clang-tidy` file.
=> io, numerics, global, linkprediction, scd, sparsification, viz: cpp coreguideline narrowing conversion

include/networkit/components/ParallelConnectedComponents.hpp, networkit/components.pyx, networkit/cpp/components/ConnectedComponents.cpp, networkit/cpp/components/ParallelConnectedComponents.cpp
From #579:
Adresses missing `getComponents()` for `ParallelComponents` (other component-variants do implement/expose this functionality)
=> Added getComponents for ParallelComponents

include/networkit/randomization/GlobalTradeSequence.hpp, networkit/cpp/randomization/GlobalCurveballImpl.hpp, networkit/cpp/randomization/GlobalTradeSequence.hpp, networkit/cpp/randomization/test/GlobalCurveballBenchmark.cpp, networkit/cpp/randomization/test/GlobalTradeSequenceGTest.cpp
This PR addresses the following issues:
- `GlobalTradeSequence` produced one global trade too many. As a result, `GlobalCurveball` performed k+1 global trade if k were configured. For users this should have little implications (algorithms performs is slightly slower, but "adds more entropy" which I found when comparing the Markov Chain's mixing times)
- `FixedLinearCongruentialMap` requires ~2n bits to deal with n bit node ids, so it cannot process more than ~2 Billion nodes with 64bit arithmetic. This was previously ignored and is now explicitly checked.
- Small code improvements and deduplication.
**Question**: `randomization/GlobalTradeSequence.hpp` contains only implementation details  and only adds to the `networkit::CurveballDetails` namespace. So I suggest moving the header file …
=> Bugfix& Code Improvement: GlobalTradeSequence

include/networkit/centrality/ApproxBetweenness.hpp, networkit/cpp/centrality/ApproxBetweenness.cpp, networkit/cpp/distance/Dijkstra.cpp
This PR improves the performance of `ApproxBetweenness`:
- Atomic updates of vertex scores instead of keeping thread-local vectors (as discussed in #532)
- Preallocate memory for `SSSP` to avoid dynamic memory allocations inside the main loop
It also fixes a bug in `Dijkstra` (if `run` is called multiple times, the algorithm could start with a non-empty heap and yield wrong results).
Additional changes:
- Make `ApproxBetweenness` final
- Make member variables `epsilon` and `delta` const (they cannot be changed from outside)
- Make `numberOfSamples()` const
- Remove `const` from value parameters
=> Refactor ApproxBetweenness

networkit/generators.pyx
While `collections.Iterable` could have been replaced by `collections.abc.Iterable`, this more directly checks if the supplied value is actually iterable, which, according to the [Python documentation](https://docs.python.org/3.8/library/collections.abc.html#collections.abc.Iterable), is the only reliable way to check if a given object is iterable.
=> Generators: remove dependency on collections.Iterable

include/networkit/centrality/TopHarmonicCloseness.hpp, networkit/centrality.pyx, networkit/cpp/centrality/TopHarmonicCloseness.cpp, networkit/cpp/centrality/test/CentralityGTest.cpp, networkit/test/test_algorithms.py, notebooks/Centrality.ipynb
`TopHarmonicCloseness` yields wrong rankings with the `NBbound` variation and this bug is not caught by CI because it is not tested. Plus, the algorithms can be improved by using a heap rather than an `Aux::PrioQueue`.
This PR brings a correct and simpler implementation for TopHarmonic closeness. Plus, it provides more extensive C++ unit tests (which fail with the previous implementation), and basic Python tests.
Furthermore, it extends the `NBcut` variation to weighted graphs.
=> Refactor: top harmonic closeness

.github/workflows/ci.yml, .github/workflows/scripts/clang_tidy.sh, .github/workflows/scripts/core_sanitizers_coverage.sh, .github/workflows/scripts/cpp_only.sh, .github/workflows/scripts/documentation.sh, .github/workflows/scripts/full.sh, .github/workflows/scripts/get_core_count.py, README.md
This migrates all tests from Travis CI to Github Actions. Motivation for this PR is the recently introduced price model for Travis CI and reoccuring test errors due to (likely) image problems.
- Windows tests are still done by appveyor
- Since Actions are only triggered / visible on the default branch, here is a preview from my fork: https://github.com/fabratu/networkit/actions (The documentation build fails, since the deployment token is not added to the fork)
- Added secrets for deployments to project settings
First impressions:
- There is more caching involved. Setup time therefore takes less time for consecutive runs.
- More concurrent jobs / cores per job.
- Reduced runtime: ~2h Travis CI vs. ~25min Github Actions
=> Migration from Travis CI to Github Actions

include/networkit/centrality/KatzCentrality.hpp, networkit/centrality.pyx, networkit/cpp/centrality/KatzCentrality.cpp
This PR allows the user to count in-edges or out-edges when computing Katz centrality.
It also includes additional minor fixes.
=> Katz centrality: edge direction

include/networkit/structures/Partition.hpp, networkit/cpp/structures/Partition.cpp
Fix `performance-unnecessary-value-param` in Partition, clang-format the class.
=> Partition: warning fix and clang-format

.github/workflows/ci.yml, .github/workflows/scripts/core_sanitizers_coverage.sh, docs/conf.py
(Hopefully) the last PR for ironing out the remaining problems with github actions. The following changes were made:
- Coverage build: Switched from ninja to make, since there are some problems with folder redirection and therefore detection of code-files for `cpp-coveralls`. This problems caused a report of 0% coverage in some cases.
- Documentation build: Moved from using `JamesIves/github-pages-deploy-action` to `peaceiris/actions-gh-pages` for publishing to github pages. Even though JamesIves-plugin seems to stable and well-known (and runs a set of common git-commands), it fails to publish in our case. The new plugin works very similar, is also well known and [tests](https://github.com/fabratu/networkit/runs/1558485371?check_suite_focus=true) publishing in our case is successful. …
=> Fixes publishing of doc- and coverage-build. Temp. removes gcc-10 tests for macOS 11.0

include/networkit/algebraic/algorithms/AlgebraicPageRank.hpp, include/networkit/base/Algorithm.hpp, include/networkit/centrality/Centrality.hpp, include/networkit/centrality/Sfigality.hpp, include/networkit/community/Modularity.hpp, include/networkit/distance/AffectedNodes.hpp, include/networkit/edgescores/EdgeScore.hpp, include/networkit/global/ClusteringCoefficient.hpp, include/networkit/scoring/ModularityScoring.hpp, include/networkit/structures/UnionFind.hpp
Hi!
I'm an engineer on https://github.com/lynxkite/lynxkite. It's an open-source graph analytics tool with a GUI. For the next release we plan to make a bunch of algorithms from NetworKit available. I have wrapped 24 so far and we love everything about NetworKit. ❤️ 
My first step was to list the algorithms and figure out what is what, so I looked a lot at the docs. I found some mistakes that were easy to fix and that's this PR.
| Before | After |
|---|---|
|![image](https://user-images.githubusercontent.com/1268018/101663172-a7138f80-3a4a-11eb-928d-61f0b9d80ee5.png)|![image](https://user-images.githubusercontent.com/1268018/101663212-b4c91500-3a4a-11eb-9d62-4c7067133b88.png)|
I will make more small fixes if I find anything.
But as I wrap the algorithms I also write the LynxKite …
=> Simple doc fixes

include/networkit/centrality/DynKatzCentrality.hpp, include/networkit/centrality/KatzCentrality.hpp, networkit/centrality.pyx, networkit/cpp/centrality/DynKatzCentrality.cpp, networkit/cpp/centrality/KatzCentrality.cpp, networkit/cpp/centrality/test/CentralityGTest.cpp, networkit/profiling/html/profile.html, networkit/profiling/profiling.py, notebooks/User-Guide.ipynb
The profiling module was broken some time ago (see #241). This PR removes (temporarily) the features that cause the crashes so that this module can be used again.
Further, it corrects the default value for the `alpha` parameter in the `KatzCentrality` python interface (which did not match the one used in the C++ implementation).
=> Profiling: remove broken features

include/networkit/components/ComponentDecomposition.hpp, include/networkit/components/ConnectedComponents.hpp, include/networkit/components/DynConnectedComponents.hpp, include/networkit/components/StronglyConnectedComponents.hpp, include/networkit/components/WeaklyConnectedComponents.hpp, include/networkit/structures/Partition.hpp, networkit/cpp/community/CutClustering.cpp, networkit/cpp/components/CMakeLists.txt, networkit/cpp/components/ComponentDecomposition.cpp, networkit/cpp/components/ConnectedComponents.cpp, networkit/cpp/components/ConnectedComponentsImpl.cpp, networkit/cpp/components/ConnectedComponentsImpl.hpp, networkit/cpp/components/StronglyConnectedComponents.cpp, networkit/cpp/components/WeaklyConnectedComponents.cpp, networkit/cpp/components/test/ConnectedComponentsGTest.cpp
- `WeaklyConnectedComponents` uses the same algorithm as `ConnectedComponents`, but it is re-implemented in a different file. This PR merges the two implementations in a single one using pimpl.
- A new class `ConnectedComponentsInterface` that inherits from `Algorithm` implements all methods needed for all algorithms that compute components in a graph.
- New method to extract the largest strongly connected component from a directed graph.
=> Refactor WeaklyConnectedComponents

.github/workflows/ci.yml
Currently the macos 11.0 images (only available as preview) and pipelines from github actions produce incoherent results. Sometimes tests fail, doesn't even start at all and more. Therefore the tests are disabled until the image is final.
=> Disables CI tests for macos 11.0

include/networkit/centrality/KatzCentrality.hpp, networkit/cpp/centrality/KatzCentrality.cpp
Good news! A unit test in LynxKite caught this issue when I rebuilt after https://github.com/networkit/networkit/commit/e568f803a2862a43a514169225649bc1834e5bc7.
That commit looks super innocent. But instead of setting the `alpha` field of `KatzCentrality` it just changes the local `alpha` variable. I tried setting `this->alpha`, but it's `const`. We have to set it correctly right away in the initializer.
Without this fix, `alpha` is zero by default. This causes all the edges to be ignored and every node gets the same centrality.
=> Fix alpha default initialization in Katz centrality

include/networkit/community/IsolatedInterpartitionConductance.hpp, networkit/cpp/community/IsolatedInterpartitionConductance.cpp
I noticed that conductance came out as 1 for all clusters. Turns out #472 changed this comparison in the wrong direction by accident. (I'm surprised this even managed to run without crashing.) With this fix I'm getting reasonable-looking conductance values.
=> Fix isolated conductance algorithm

.clang-tidy, include/networkit/algebraic/DynamicMatrix.hpp, include/networkit/graph/Graph.hpp, include/networkit/io/DibapGraphReader.hpp, include/networkit/numerics/LAMG/SolverLamg.hpp, include/networkit/randomization/GlobalTradeSequence.hpp, include/networkit/viz/Point.hpp
As reported here [1], move constructors and assignment operators should be declared `noexcept` at least when used with STL containers, otherwise STL will choose copy constructors and thus there is a performance loss.
This PR adds the `noexcept` specifier to user-defined move constructors and assignment operators.
[1] https://clang.llvm.org/extra/clang-tidy/checks/performance-noexcept-move-constructor.html
=> Warning fix: performance-noexcept-move-constructor

networkit/cpp/distance/NeighborhoodFunctionApproximation.cpp, networkit/cpp/generators/HyperbolicGenerator.cpp, networkit/cpp/graph/test/GraphGTest.cpp
Fixes potential data races as reported in #622.
- `totalCandidates`: Added a reduction
- `queued`: ~~Make queued atomic~~ Since `msvc` does only support OpenMP 2.0, atomic writes are not available. Therefore a reduction for queued is used, which is equivalent to `queued = true`. Initial benchmarks on the artifical gtest graph instances also show better performance for reduction vs. atomic for this case. 
- `os_stack_trace_getter_`: This one is the most tricky one, since the error is not in NetworKit, but in googletest. From the report, the data race potentially occurs when executing `EXPECT_NE`. However from code-inspection (see https://github.com/google/googletest/blob/master/googletest/src/gtest.cc#L2670 which for every testcase calls …
=> Fix potential data races

.github/workflows/ci.yml, extrafiles/tooling/CppClangFormat.py, extrafiles/tooling/nktooling/__init__.py
Currently, `./check_code.py` checks the coding style by calling `clang-format-8` but this does not work with newer versions of clang-format and even with clang-format 8 if it can only be invoked using `clang-format`.
This PR fixes this issue and updates the coding style CI build to clang-format-11. Further, as suggested in #576, `CppClangFormat.py` will throw a `FileNotFoundError` upon failure.
=> check_code.py: check version of clang-format

include/networkit/graph/BFS.hpp
When `BFSfrom` is called from a single source, this is inserted into a `std::vector<node>` and the multi-source `BFSfrom` is called. Since we already know that we have a single source at compile time, it makes more sense to use a `std::array<node, 1>` rather than a vector.
=> BFSfrom: std::array for single source

.clang-tidy
=> Fix case configuration in clang-tidy

.github/workflows/ci.yml
Suggested changes:
- As suggested [here](https://github.com/networkit/networkit-website/pull/49), the publish branch of the documentation repository of NetworKit will now only contain the last commit.
=> Documentation deployment: Publish branch only contains last commit

networkit/cpp/centrality/ApproxElectricalCloseness.cpp
The vector that is computed as the column of the lpinv may differ by a constant from the actual column of the lpinv since L vanishes on constant vectors. This is not addressed explicitly in the part of the paper which explains how the pivot column is computed, but may affect the output centrality and diagonal entry values.
=> ApproxElectricalCloseness: Fix minor issue with pivot lpinv column

setup.py
While reviewing @fabratu PR #667 I noticed that we already check whether the candidate compiler supports C++14 features by passing the `-std=c++14` option.
=> Remove addressed TODO in setup.py

.clang-tidy, networkit/cpp/randomization/CurveballImpl.hpp
The header filter of our `.clang-tidy` does not match private headers, so private implementations are not checked.
This PR updates our configuration to also match private implementations and fixes a warning.
=> clang tidy: check private headers

extrafiles/sphinx-style/_templates/layout.html
In the current version of the documentation build, the search-feature is broken due to a missing Javascript object (`Stemmer`).
Likely an error in the bootstrap-theme. Until this is fixed, a workaround is to include `_static/language_data.js` as an additional js-file in the theme. In this way, the file is included before the js-searchlibrary. This produces a minimal overhead, since `Stemmer` is now defined on all pages, not just the search page.
=> Fixes missing Stemmer-module for doc-search

setup.py
Recognized a bug for NetworKit in macOS, which is triggered for certain types of local builds.
If more than one compiler is installed under macOS (e.g. certain versions of `g++`), `setup.py` and `cmake` detect different compilers. This can lead to missing symbols and failed builds.
If the regular `cmake` + `make` process is called, the system OS compiler is prioritized.
```
cmake -DCMAKE_BUILD_TYPE=Debug -DNETWORKIT_CXX_STANDARD=14 -DNETWORKIT_WARNINGS=ON ..
...
initializing NetworKit compilation with: 'cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/Users/fbt/Documents/maks/networkit/repos/networkit/build/lib.macosx-10.9-x86_64-3.9 -DCMAKE_CXX_COMPILER=c++ -DNETWORKIT_FLATINSTALL=ON -DNETWORKIT_PYTHON=/usr/local/anaconda3/envs/nktdoc/include/python3.9 …
```
=> Changes compiler detection to favor system default (macOS)

include/networkit/generators/ClusteredRandomGraphGenerator.hpp, include/networkit/generators/ErdosRenyiEnumerator.hpp, networkit/cpp/community/test/CommunityGTest.cpp, networkit/cpp/generators/ClusteredRandomGraphGenerator.cpp, networkit/cpp/generators/test/GeneratorsGTest.cpp, networkit/generators.pyx, networkit/test/test_generators.py
`ClusteredRandomGraphGenerator` is an O(m^2) algorithm and it is implemented sequentially.
A simple idea to parallelize it is to add all half-out edges in parallel (this is thread-safe), and then to use `GraphBuilder` to complete the work.
This already gives us some speedup, generating a graph with 15K nodes and 50 clusters took ~10s with the previous implementation and just ~130ms with the new one (on a 24 cores machine).
=> Parallelize ClusteredRandomGraphGenerator

README.md, setup.py
This PR raises minimum support for clang. 
This is 0.5 years earlier, then it would be usually done. However it is expected, that clang 3.8 is not really used anymore (See discussion #703). Blocking of needed feature-PRs (#516, #359) is the main motivation for doing the shift to 3.9.
Update PR for the website is here: https://github.com/networkit/networkit-website/pull/51
=> Raises minimum requirement for clang 3.8 -> 3.9

.github/workflows/ci.yml
Since min. version of clang is raised from 3.8 to 3.9 - CI tests have to be adjusted. This is a copy from work done in #516 by @angriman
=> Github actions: raise minimum supported clang version to 3.9

networkit/csbridge.py
This PR adds a wrapper/bridge-module for getting a graph visualization widget based on ipycytoscape[1]. With this it is possible to draw colored graphs in Jupyter Notebooks without the need for other language-based tools like graph-viz or gephi. This can be useful in environments, where only access to the webbrowser is possible. Example image (colored karate-graph with harmonic closeness scores):
[1] https://ipycytoscape.readthedocs.io/en/latest/index.html
=> Adds a new Python module: csbridge

Dockerfile, README.md
This PR adds supports for binder-integration.
In the past afaik, binder supported only direct repo integration. Additional packages would then be installed via configuration like environment.yml (conda) or requirements.txt (python). The final environment then included the complete repo, which is not minimal (since only `input` and `notebooks` are needed) and the repo2docker-build process also triggered errors due to missing Cython.
With direct Dockerfile-support we can supply a custom pre-build jupyter-notebook/lab instance with pre-defined content. This version build up on the latest release (8.0) and is a derivate of the image used for the upcoming cloud-instances.
A build (same Dockerfile, just from the fork) can be seen here: …
=> Add binder-support

include/networkit/centrality/EigenvectorCentrality.hpp, networkit/cpp/centrality/EigenvectorCentrality.cpp
Eigenvector centrality is computed iteratively and at each iteration the score vector `scoreData` is updated by copying the vector of the new scores `values`. However, we always reset `values` at the beginning of each iteration, so we can avoid a copy by swapping the two vectors.
=> Refactor Eigenvector centrality

.github/workflows/ci.yml, .github/workflows/scripts/upload_coverage.py
This PR fixes a current problem with Coveralls.
The NetworKit-coveralls [repo](https://coveralls.io/github/networkit/networkit) shows the 9.12.2020 as the last push date. New builds in Github Actions doesn't trigger new major builds in Coveralls, instead minor-builds are added to #935. Details on the progress of coverage for certain commits are therefore very much hidden in the frontend. This error happens, because pushes to the API of Coveralls are tied to a `TRAVIS_JOB_ID`, which of course isn't provided by Github Actions.
To redeem this, it not sufficient to map the Github Actions `runner_num` to `TRAVIS_JOB_ID`, since this Coveralls further matches these numbers not only against their system, but also match them against a travis-runner. Instead we have to upload a json-based …
=> Fixes coverage build number detection

networkit/viztasks.py
To address #707.
This adds a warning whenever a multi-edge is added. Furthermore, when trying to display a multi-graph using viztasks.drawGraph the graph will be converted to a simple graph for display purporses and the user will be informed.
=> Remove multiedges in drawgraph

networkit/cpp/generators/BarabasiAlbertGenerator.cpp
By using `Graph::nodeRange()` we can simplify a bit the implementation of `BarabasiAlbertGenerator` by removing a variable and a lambda function.
=> Minor refactor for BarabasiAlbert

include/networkit/distance/AdamicAdarDistance.hpp, include/networkit/graph/Graph.hpp, networkit/cpp/distance/AdamicAdarDistance.cpp
As neighbors are swapped with the last neighbor when they are removed, removing edges from within `forNeighborsOf()` is no longer safe but we also do not need to check for `none` there anymore. As `removeNode()` removes incident edges, this is also not necessary anymore in `AdamicAdarDistance`. I have briefly looked for other uses of `removeEdge()`, but on first glance they seem to be safe.
=> Follow-up fixes for neighbors being swapped with the end

include/networkit/base/Algorithm.hpp, include/networkit/centrality/CoreDecomposition.hpp, include/networkit/centrality/LocalPartitionCoverage.hpp, include/networkit/community/CoverF1Similarity.hpp, include/networkit/community/CoverHubDominance.hpp, include/networkit/community/IntrapartitionDensity.hpp, include/networkit/community/IsolatedInterpartitionConductance.hpp, include/networkit/community/IsolatedInterpartitionExpansion.hpp, include/networkit/community/PartitionFragmentation.hpp, include/networkit/community/PartitionHubDominance.hpp, include/networkit/correlation/Assortativity.hpp, include/networkit/distance/APSP.hpp, include/networkit/distance/SPSP.hpp, include/networkit/generators/LFRGenerator.hpp, include/networkit/graph/RandomMaximumSpanningForest.hpp, include/networkit/graph/UnionMaximumSpanningForest.hpp, include/networkit/randomization/Curveball.hpp, include/networkit/randomization/DegreePreservingShuffle.hpp, include/networkit/randomization/GlobalCurveball.hpp, networkit/base.pyx, networkit/cpp/distance/test/APSPGTest.cpp
As for `toString()` in #631, `isParallel()` is implemented by only a small subset of NetworKit algorithms and by default it throws a `std::runtime_error`. Internally it is never used and I do not see a use case where someone wants to find out whether an algorithm is parallel at runtime.
=> Deprecate Algorithm::isParallel()

.github/workflows/ci.yml, .github/workflows/scripts/clang_tidy.sh, .github/workflows/scripts/cpp_only.sh, .github/workflows/scripts/documentation.sh, .github/workflows/scripts/full.sh, networkit/GraphMLIO.py, networkit/flow.pyx, networkit/test/test_graphio.py
The python interface of `EdmondsKarp` does not properly inherit from `Algorithm`, and thus the `run` method is not visible (#721).
The CI has system has been fixed so that it fails when a python test fails.
Further fixes in `test_graphio.py`.
=> Make CI fail on failed python test, fix failing python tests

include/networkit/base/Algorithm.hpp, include/networkit/centrality/LocalPartitionCoverage.hpp, include/networkit/community/CommunityDetectionAlgorithm.hpp, include/networkit/community/CutClustering.hpp, include/networkit/community/IsolatedInterpartitionConductance.hpp, include/networkit/community/IsolatedInterpartitionExpansion.hpp, include/networkit/community/LPDegreeOrdered.hpp, include/networkit/community/PLM.hpp, include/networkit/community/PLP.hpp, include/networkit/community/ParallelAgglomerativeClusterer.hpp, include/networkit/correlation/Assortativity.hpp, include/networkit/distance/APSP.hpp, include/networkit/distance/Diameter.hpp, include/networkit/generators/LFRGenerator.hpp, include/networkit/graph/RandomMaximumSpanningForest.hpp, include/networkit/graph/UnionMaximumSpanningForest.hpp, include/networkit/independentset/IndependentSetFinder.hpp, include/networkit/independentset/Luby.hpp, include/networkit/randomization/Curveball.hpp, include/networkit/randomization/DegreePreservingShuffle.hpp, include/networkit/randomization/GlobalCurveball.hpp, networkit/community.pyx, networkit/cpp/base/Algorithm.cpp, networkit/cpp/community/test/CommunityGTest.cpp, networkit/cpp/graph/RandomMaximumSpanningForest.cpp, networkit/engineering.pyx, networkit/independentset.pyx
I don't see a real use case for the `toString()` method in Algorithm (an algorithm's name is already known from the class name and the parameters can be checked in the docs) and very few subclasses implement it.
In this PR:
- deprecate `toString()`
- set `hasRun` to `false` by default and use the default constructor
- other minor changes
=> Refactor Algorithm and deprecate toString()

include/networkit/auxiliary/BucketPQ.hpp, include/networkit/auxiliary/PrioQueue.hpp, networkit/cpp/auxiliary/BucketPQ.cpp, networkit/cpp/auxiliary/test/AuxGTest.cpp, networkit/cpp/centrality/ApproxCloseness.cpp, networkit/cpp/centrality/DynBetweenness.cpp, networkit/cpp/centrality/GroupCloseness.cpp, networkit/cpp/centrality/GroupDegree.cpp, networkit/cpp/distance/DynAPSP.cpp, networkit/cpp/distance/DynDijkstra.cpp, networkit/cpp/viz/MaxentStress.cpp, networkit/cpp/viz/PivotMDS.cpp
I've been working recently with `BucketPQ` and I've noticed that it does not support basic (constant time) utility methods that can simplify the usage of this data structure. This PR adds the following methods to `PrioQueue` and `BucketPQ`:
- `empty`
- `contains`: whether or not the pq contains a given element.
- `getMin`: returns the top element without removing it (only for `BucketPQ`, `PrioQueue` already has `peekMin`).
Further, it adds tests for BucketPQ.
=> New utility methods for (Bucket)PrioQueue

networkit/cpp/io/EdgeListReader.cpp, networkit/graphio.pyx
to especially tell that firstNode should be 0 if continuous = false to address the confusion in #725 .
=> Segmentation fault fix on EdgeListReader in the case of firstNode > 0 and continuous = false

networkit/cpp/centrality/test/CentralityGTest.cpp, networkit/cpp/generators/test/ErdosRenyiEnumeratorGTest.cpp, networkit/cpp/graph/test/GraphBuilderAutoCompleteGTest.cpp, networkit/cpp/graph/test/GraphBuilderDirectSwapGTest.cpp, networkit/cpp/graph/test/GraphGTest.cpp, networkit/cpp/graph/test/GraphToolsGTest.cpp, networkit/cpp/graph/test/TraversalGTest.cpp, networkit/cpp/io/test/MemoryMappedFileGTest.cpp, networkit/cpp/randomization/test/GlobalTradeSequenceGTest.cpp, networkit/cpp/reachability/test/ReachabilityGTest.cpp, networkit/cpp/sparsification/test/GlobalThresholdFilterGTest.cpp
CMake triggers some deprecation warnings in `extlibs/googletest/CMakeLists.txt`. This PR updates googletests and adapts the instantiation of test cases accordingly.
=> Update google tests

networkit/cpp/matching/Matching.cpp
`Matching::isProper` uses `forNodes` to check the matching of every vertex. However, we can use `nodeRange()` and return `false` as soon as we find a vertex that does not satisfy the matching property.
=> Faster Matching::isProper

include/networkit/auxiliary/HashUtils.hpp, include/networkit/community/OverlappingNMIDistance.hpp, networkit/community.pyx, networkit/cpp/community/CMakeLists.txt, networkit/cpp/community/OverlappingNMIDistance.cpp, networkit/cpp/community/test/CommunityGTest.cpp
This implements the Overlapping Normalized Mutual Information from [NMI13]. I'm happy to receive some feedback.
There are some points which might need to be changed.
1. Documentation. Most of the algorithm is implemented in separate functions. Some of the doc comments might be unnecessary. The inclusion of LaTeX formulas could be too much and the formatting could also be wrong.
2. Naming conventions. The public methods conform to camelCase, but the hidden functions and variable names are in snake_case. The only attribute is called `m_normalization`. The string parameters for normalization are also in snake_case.
3. Normalization (`normalize`). The current implementation allows the specification of the method used to normalize the mutual information. The authors use "max". My impression is …
=> New Algorithm: Overlapping Normalized Mutual Information

.github/workflows/scripts/documentation.sh, Dockerfile
This PR fixes the following:
- Binder-image is broken when using base-image `jupyter/base-notebook:latest` (conda not supporting kernel-version). Using last release version lab-3.0.11 works. See also [broken](https://mybinder.org/v2/gh/networkit/networkit/master?urlpath=lab/tree/notebooks/User-Guide.ipynb) vs. [works](https://mybinder.org/v2/gh/fabratu/networkit/temp-version-pinning?urlpath=lab/tree/notebooks/User-Guide.ipynb).
- `documentation build` is broken, due to the most recent version of `breathe` (used for C++ doc-site generation). Pinning to the `<=4.29.0`(last release) works. See also https://github.com/michaeljones/breathe/issues/683
=> [Fix] Binder, CI documentation-build by pinning older software-versions

include/networkit/matching/LocalMaxMatcher.hpp, include/networkit/matching/PathGrowingMatcher.hpp, networkit/cpp/matching/LocalMaxMatcher.cpp, networkit/cpp/matching/PathGrowingMatcher.cpp, networkit/cpp/matching/test/MatcherGTest.cpp, networkit/matching.pyx
`PathGrowingMatcher` does not seem to support directed graphs, when launched on a directed graph one gets an error like this ```IndexError: vector<bool>::_M_range_check: __n (which is 140354493912512) >= this->size() (which is 100)```.
I think that we should check in the constructor if the graph is undirected, and this should also be documented.
=> PathGrowingMatcher: throw if input graph is directed

.github/workflows/ci.yml, CMakeLists.txt, networkit/cpp/centrality/GroupClosenessGrowShrinkImpl.cpp, networkit/cpp/centrality/GroupClosenessGrowShrinkImpl.hpp
As discussed in #674 (and in preperation for the distribution of a wheel-package) this PR reduces the total number of tests slightly. This also changes:
- Remaining tests are renamed according to a certain scheme, which is now documented at the beginning of the `ci.yml` file. This also gives a rationale, why each test is done.
- ~~Shortening the name of each test, so that the full name is visible in the Actions-overview for a run. Hopefully the emojis are not to fancy~~
- Remove duplicating lines of code in `ci.myl` by using a "[fake ternary operator](https://github.community/t/do-expressions-support-ternary-operators-to-change-their-returned-value/18114)"
- Removing custom tests in main `CMakeLists.txt` for AVX2. `-march=native` already should enable all hardware-specific features like …
=> Github Actions documentation/opt. and AVX2-detection changes

.github/workflows/ci.yml, .github/workflows/scripts/clang_tidy.sh, .github/workflows/scripts/documentation.sh, include/networkit/centrality/GroupClosenessGrowShrink.hpp, networkit/cpp/centrality/DynTopHarmonicCloseness.cpp, networkit/cpp/graph/test/GraphBuilderAutoCompleteGTest.cpp, networkit/cpp/graph/test/GraphBuilderDirectSwapGTest.cpp, networkit/cpp/graph/test/GraphGTest.cpp, networkit/cpp/sparsification/LocalSimilarityScore.cpp, networkit/cpp/viz/MaxentStress.cpp, networkit/cpp/viz/PivotMDS.cpp
This PR introduces the following fixes:
- Introducing workarounds for clang-12 errors in `GraphGTest`, `GraphBuilderAutoCompleteGTest`and `GraphBuilderDirectSwapGTest` by rewriting the loops and removing `critical`-sections.
- Introducing workarounds for clang-12 error in `LocalSimilarityScore` by exchanging function call of `balancedParallelForNodes` by it's logic. 
- The pinning for breathe is removed, since the new release doesn't break anymore. 
- Slight changes to documentation code (see suggestions in https://github.com/michaeljones/breathe/releases/tag/v4.29.2). 
- Add explicit includes for `<limits>` due to changes in gcc-11 (errors already visible on CI for most recent Ubuntu-runners) (see #755)
Background to clang-12 errors:
The most recent version (12.0.0 & 12.0.1) crashes on …
=> Small fixes: breath-update, workaround for clang-12 errors & adding includes for gcc-11

networkit/cpp/io/CoverWriter.cpp, networkit/cpp/io/DGSReader.cpp, networkit/cpp/io/EdgeListWriter.cpp, networkit/cpp/io/GraphIO.cpp
As suggested in #754, `std::endl` may degrade the performance of graph writers. This PR replaces `std::endl` with `\n` in the `io` module,
Closes #754
=> Refactor edgelistwriter

include/networkit/auxiliary/PrioQueue.hpp, include/networkit/coarsening/ParallelPartitionCoarsening.hpp, include/networkit/structures/Partition.hpp, networkit/coarsening.pyx, networkit/cpp/algebraic/test/AlgebraicSpanningEdgeCentralityGTest.cpp, networkit/cpp/coarsening/ParallelPartitionCoarsening.cpp, networkit/cpp/coarsening/test/CoarseningBenchmark.cpp, networkit/cpp/coarsening/test/CoarseningGTest.cpp, networkit/cpp/components/ParallelConnectedComponents.cpp, networkit/cpp/structures/Partition.cpp
The algorithm generates all incident edges of a coarse vertex at the same time (on the same thread) and thus avoids linear searches in the neighbor lists.
This is the first in a potential series of pull-requests that contain the features from the 'huge' ego-splitting pull-request.
=> improved (parallel) coarsening implementation for clusterings

include/networkit/graph/Graph.hpp, networkit/graph.pxd, networkit/graph.pyx
This PR includes the following:
- Fix pre- and post-increment of `NeighborIterator` (fixes error on CI with #734)
- Change to return-by-reference for pre-increment operator of all graph-iterator types
- Add missing Cython-extension for `NeighborWeightRange`
=> Fixes pre- and post-increment of NeighborIterator + minor fixes/additions

include/networkit/auxiliary/ArrayTools.hpp, include/networkit/graph/Graph.hpp, include/networkit/graph/GraphTools.hpp, include/networkit/matching/SuitorMatcher.hpp, networkit/cpp/auxiliary/test/AuxGTest.cpp, networkit/cpp/graph/GraphTools.cpp, networkit/cpp/graph/test/CMakeLists.txt, networkit/cpp/graph/test/GraphToolsGTest.cpp, networkit/cpp/matching/CMakeLists.txt, networkit/cpp/matching/SuitorMatcher.cpp, networkit/cpp/matching/test/MatcherGTest.cpp, networkit/graphtools.pyx, networkit/matching.pyx, networkit/test/test_graphtools.py, networkit/test/test_matching_algorithms.py
This PR brings the 1/2-approximation algorithm for maximum (weighted) matching by Manne and Halappanavar (New Effective Multithreaded Matching Algorithms, IPDPS 2014).
There are two versions of the algorithm, one of which only supports graphs where the adjacency lists of every vertex are sorted by edge weight in decreasing order. To this end I also added a new `sortEdgesByWeight` method in `Graph`, which allows to sort the edges of a graph by edge weight in increasing or decreasing order. This method uses a new generic `sortEdges` method in `Graph`, which allows to sort the edges of a graph according to a custom criterion.
I am a bit hesitant to add the new sorting methods to `Graph`, they are probably too specific. An alternative idea is to implement them in `GraphTools`.
=> Suitor matcher

include/networkit/graph/GraphTools.hpp, networkit/cpp/components/ConnectedComponentsImpl.cpp, networkit/cpp/components/StronglyConnectedComponents.cpp, networkit/cpp/components/test/BiconnectedComponentsGTest.cpp, networkit/cpp/graph/GraphTools.cpp, networkit/cpp/graph/test/GraphToolsGTest.cpp, networkit/graphtools.pyx, networkit/test/test_graphtools.py
Addressing the unclarity in the function bought up in #651 . By bringing the documentation more in line with what was originally in #374 .
=> Restoring the documentation of GraphTools::subgraphFromNodes.

include/networkit/algebraic/algorithms/AlgebraicSpanningEdgeCentrality.hpp, include/networkit/numerics/ConjugateGradient.hpp, include/networkit/numerics/LAMG/Lamg.hpp, include/networkit/numerics/LinearSolver.hpp, networkit/cpp/algebraic/test/AlgebraicSpanningEdgeCentralityGTest.cpp
This PR adds an optimized parallel solution loop to ```LAMG``` and ```ConjugateGradient``` as proposed in #764. It will also solve the problem described in #761.
Changes in ```AlgebraicSpanningEdgeCentrality``` show how the new API can be used
=> Optimize memory usage in LAMG and ConjugateGradient

include/networkit/auxiliary/AlignedAllocator.hpp, include/networkit/centrality/GroupClosenessLocalSearch.hpp, networkit/centrality.pyx, networkit/cpp/centrality/CMakeLists.txt, networkit/cpp/centrality/GroupClosenessLocalSearch.cpp, networkit/cpp/centrality/test/CentralityGTest.cpp, networkit/test/test_algorithms.py, notebooks/GroupCentrality.ipynb
This PR brings the local search approximation algorithm for group closeness presented in [Group-Harmonic and Group-Closeness Maximization – Approximation and Engineering](https://epubs.siam.org/doi/10.1137/1.9781611976472.12) (ALENEX 2021).
The main benefit of the template implementation is that distances are stored as integers or floats depending on whether the graph is weighted or not (and thus we can do integer operations instead of floating point operations on unweighted graphs).
=> New Approximation Algorithm for Group Closeness

include/networkit/scd/CliqueDetect.hpp, networkit/cpp/scd/CliqueDetect.cpp
After the merge of #726, CliqueDetect can use the new GraphTools method.
=> CliqueDetect: replace duplicate subgraphFromNodes implementation

docs/python_api/csbridge.rst, docs/python_api/dynamics.rst, docs/python_api/embedding.rst, docs/python_api/reachability.rst
This adds missing modules to Python-documentation.
=> Add csbridge, dynamics, embedding and reachability-modules to doc

include/networkit/auxiliary/VectorComparator.hpp, include/networkit/centrality/TopCloseness.hpp, include/networkit/centrality/TopHarmonicCloseness.hpp, include/networkit/distance/BidirectionalDijkstra.hpp, networkit/cpp/centrality/TopCloseness.cpp, networkit/cpp/centrality/TopHarmonicCloseness.cpp, networkit/cpp/distance/BidirectionalDijkstra.cpp, networkit/cpp/graph/test/TraversalGTest.cpp, networkit/cpp/scd/LocalTightnessExpansion.cpp, networkit/cpp/scd/TCE.cpp
This PR replaces custom vector-based comparators with the ones implemented in `Aux`.
=> Refactor: use vector comparator in Aux

README.md, networkit/__init__.py
Currently several links point to `Dev/notebooks` instead of `master/notebooks`.
This PR fixes things partially as I'm unsure where https://networkit.github.io/get_started.html is in this repository.
=> link fix to notebooks Dev/notebooks -> master/notebooks

.github/workflows/ci.yml, .github/workflows/scripts/documentation.sh, CMakeLists.txt
This PR includes the following:
- Fixing the documentation build by pinning sphinx to `<4.1` due to an incompatibility with breathe. This is currently worked on: https://github.com/michaeljones/breathe/pull/711 and https://github.com/sphinx-doc/sphinx/issues/9433
- Linking `Python3_libraries` for cython-extensions is only necessary for Windows. While there seems to be no problem with Linux, on macOS this can lead to segmentation faults on certain compiler/lib-combinations (e.g. `conda`) when importing NetworKit. Therefore it is removed for the other OSes.
- Github Actions: 
- Raising minimum version of gcc to version 6. Also switching from Ubuntu 16.04 to 18.04, since packages are natively available in this distro (universe repo) and 16.04 will deprecate in September 2021.
- Raising …
=> Collection of small fixes / improvements for CMake and CI

networkit/algebraic.py, networkit/coloring.py, networkit/test/test_coloring.py
This PR fixes problems with #796. Adds also an unit test for coloring-module.
Update: During tests with new arm-specific builds of scipy, I discovered that the submodule `linalg` is not anymore imported by default. Therefore changed includes in `algebraic.py` as a drive-by.
Closes #796
=> Reduce desired number of Eigenvalues (scipy.linalg.eig), update Spectral Coloring

include/networkit/coarsening/GraphCoarsening.hpp, networkit/cpp/coarsening/GraphCoarsening.cpp
As discussed in https://github.com/networkit/networkit/issues/801
Avoids copies, and allows the graph to be moved.
Perhaps there should be a check that makes sure the graph hasnt been moved or changed if a call to `getCoarseToFineNodeMapping` is made, but im not sure how that would work.
=> Added overloaded function that returns a reference instead of copying in Graphcoarsening

networkit/sampling.py
`subgraphFromNodes()` function was moved from the `graph`-module to the `graphtools`-module [in NetworKit 8.0](https://github.com/networkit/networkit/blob/master/CHANGES.md#changes-in-python-interface). But there was one thing missing, so I fixed it.
=> Fix to call subgraphFromNodes

docs/DevGuide.rst
The old version pointed to a dead location - Googletest Primer has a new address.
=> Fix Googletest Primer link in devGuide docs.

.github/workflows/build_wheels.yaml, .github/workflows/build_wheels.yml, CMakeLists.txt, setup.py
This PR adds the following:
- Github actions based wheel-builder for Linux (x86_64 CPython 3.6-3.9, aarch64 CPython 3.9) based on Manylinux2010 for x86_64 and Manylinux2014 for aarach64, macOS (x86_64 CPython 3.6-3.9) based on toolchain 10.9 and Windows (amd64 CPython 3.9). 
- Upload as an artifact on the CI-pipeline. This makes the files available as download in the current CI-build. Downloads will be available for ~~14~~ 7 days on PR and 1 month on master.
- Pinning Python executable by providing it as a parameter from setuptools to cmake. This is necessary for Manylinux-images to work properly. Otherwise cmake and setuptools work on different Python-environments.
Remarks:
- Thanks to @nomanrz (see #451) for the initial work. I adapted the idea and especially the inside into …
=> Add cibuildwheel script to create wheel-artifacts on GHA

README.md, setup.py
This PR add support / documentation for arm64-apple-darwin when build from source.
Currently AppleClang + OpenMP (both `libomp` from brew and build from source) is not supported due to segmentation faults. This is also true for the clang-compiler package from brew. I suggest for now to officially support source build via conda environments (packages `compilers`+ `llvm-openmp` from miniforge), which is also what other data science Python packages recommend. 
Source:
https://github.com/numpy/numpy/issues/17807
https://github.com/scipy/scipy/issues/13364
https://scikit-learn.org/stable/install.html#installing-on-apple-silicon-m1-hardware
The build binary can still not be tested on CIs due to licensing problems. I can confirm however, that besides these building problems, all tests (gtests, …
=> Add support and documentation for arm64-apple-darwin

.github/workflows/build_wheels.yml, setup.py
This PR adds arm64-wheels for macOS. Besides using a nightly-build scipy wheel for this (see #799), this also adds a crossbuild-variable for osx to pass to cmake (variable: `CMAKE_OSX_ARCHITECTURES`).
=> GHA: Adding arm64-wheels for macOS

include/networkit/centrality/GroupCloseness.hpp, networkit/cpp/centrality/GroupCloseness.cpp, networkit/cpp/centrality/test/CentralityGTest.cpp
- Replace copy of `Graph` with `const Graph *`
- Remove unnecessary references to `G` since it is already a member variable
- Use algorithms implemented in `Traversal::` in `scoreOfGroup` instead of re-implementing them
- Bugfix: the algorithm discards low-degree nodes, which leads to incorrect results in small networks.
- Further performance improvements (mainly removing unnecessary variables)
=> Refactor GroupCloseness

include/networkit/algebraic/Vector.hpp, networkit/cpp/algebraic/Vector.cpp
- The inner product function is already implemented in `std`, this PR replaces the custom implementation in `Vector` with `std::inner_product`.
- The `==` operator of `std::vector` compares the content of two vectors, so we can use that instead of manually comparing each element.
- Computing the mean can be parallelized using a parallel reduction (if available).
=> Refactor Vector

include/networkit/algebraic/CSRGeneralMatrix.hpp
As the last step, the constructor of `CSRMatrix` restores the row indices to their correct values. However, this is equivalent to rotating the vector to the right by one and resetting its first value to zero, which can be implemented with just two lines of code instead of writing another loop.
=> Refactor CSRMatrix

networkit/centrality.pyx, networkit/graph.pyx
Makes clear that it does not follow the order of edges Ids addressing #830 .
=> Update IterEdges() documentation

networkit/cpp/centrality/GroupClosenessGrowShrinkImpl.cpp, networkit/cpp/centrality/GroupClosenessLocalSearch.cpp
The local-search approximation algorithm should evaluate all swaps. However, the current implementation excludes leaves of the DAG, which leads to potentially incorrect results and random failures of `CentralityGTest.testGroupClosenessLocalSearch`.
=> Bug fix: group closeness local search

include/networkit/algebraic/CSRGeneralMatrix.hpp, networkit/cpp/algebraic/test/MatricesGTest.cpp
Our CSRMatrix class uses simple quicksort and binary search implementations. This PR:
- In `sort()`: uses `std::sort` to compute a permutation of column indices and uses `ArrayTools::applyPermutation` to sort the values and column indices
- Simplifies the checks at the end of `sort()` with `std::is_sorted` and enables them only if NetworKit sanity checks are enabled, as originally intended
- Adds a simple test for `sort()`
- Uses `std::lower_bound` to search for diagonal elements in `diagonal()`
=> Refactor CSRMatrix sort() and diagonal()

include/networkit/graph/GraphTools.hpp, include/networkit/graph/TopologicalSort.hpp, networkit/cpp/graph/CMakeLists.txt, networkit/cpp/graph/GraphTools.cpp, networkit/cpp/graph/TopologicalSort.cpp, networkit/cpp/graph/test/CMakeLists.txt, networkit/cpp/graph/test/TopologicalSortGTest.cpp, networkit/graphtools.pyx, networkit/test/test_graphtools.py
This PR adds a sequential Topology Sort algorithm as requested/discussed here: https://github.com/networkit/networkit/discussions/829
=> Add topology sort for both C++ and Python interface

include/networkit/centrality/PageRank.hpp, networkit/centrality.pyx, networkit/cpp/centrality/PageRank.cpp, networkit/cpp/centrality/test/CentralityGTest.cpp
This PR includes the following concerning PageRank:
- Adds sink-handling in order to properly fulfill the Markov chain model. See (among others): https://dl.acm.org/doi/pdf/10.1145/1151087.1151090
- Fixes an error with the normalized PageRank #720 (NPR). The result of NPR was wrong due to missing sink-handling - so this fix is more a drive-by.
- Adds documentation for new PageRank behavior and results
- Adjusting gtests accordingly
=> Refactor PageRank: Add sink handling for directed graphs, fix norm-PageRank

docs/python_api/csbridge.rst, docs/python_api/modules.rst, include/networkit/community/GraphClusteringTools.hpp, include/networkit/community/PLM.hpp, networkit/community.pyx
- Addresses  #838. By adding the function header as the first line of the doc, this enables rendering of missing parameters. This PR only fixes this for the `community`-module. For the PRs to become not too big, other modules will be addressed in other PRs.
- Fix several documentation strings, which are not compliant with sphinx-automodule (`community`-module)
- Add missing function documentation (`community`-module)
- Add missing function documentation in C++ counterparts
- Add missing `csbridge`-module to Python-documentation
=> Documentation: add missing parameters in community-module, add missing csbridge-module

networkit/community.pyx
This is a follow-up to #855. While the parameters are shown by no in the documentation, the description for input and output-parameters is not shown in many cases. This is due to having ':' or too long scores for 'Returns' or 'Parameters' headings. Also fixed some minor inconsistencies in parameter-types and tags.
I did overlook this in the first PR -.- Unfortunately the documentation for `autodoc/automodule` doesn't really say something about how these headings are allowed to look like. Good news: documentation now looks as intended. Note that now most parameter-types can also be clicked.
Example from the modified documentation:
Once this is approved/merged I would do the same treatment for the other modules.
=> Documentation: Fix input/output-parameter description for Python community-module

include/networkit/centrality/DynKatzCentrality.hpp, include/networkit/centrality/KadabraBetweenness.hpp, include/networkit/centrality/PermanenceCentrality.hpp, networkit/algebraic.py, networkit/base.pyx, networkit/centrality.pyx
This PR uses findings from #855 and #865 to fix other Python modules (algebraic, base, centrality). Besides fixing non-visible doc-strings for Python-code, C++ doc-strings for these modules are also added.
=> Documentation: Fix missing and non-visible doc-strings for Python modules algebraic, base, centrality

networkit/clique.pyx, networkit/coarsening.pyx, networkit/coloring.py, networkit/community.pyx, networkit/components.pyx, networkit/correlation.pyx, networkit/csbridge.py
This PR is a follow-up and fixes missing/non-visible doc for modules: clique, coarsening, coloring, components, correlation, csbridge (remaining modules beginning with letter 'c').
=>  Documentation: Fix missing/non-visible doc for Python modules beginning with 'c'

include/networkit/centrality/KadabraBetweenness.hpp, include/networkit/generators/quadtree/QuadNode.hpp, include/networkit/generators/quadtree/QuadNodeCartesianEuclid.hpp, include/networkit/generators/quadtree/QuadNodePolarEuclid.hpp, networkit/cpp/coarsening/ClusteringProjector.cpp, networkit/cpp/components/DynConnectedComponents.cpp, networkit/cpp/components/DynWeaklyConnectedComponents.cpp, networkit/cpp/distance/Diameter.cpp, networkit/cpp/io/test/IOBenchmark.cpp, networkit/cpp/viz/MaxentStress.cpp
I spotted several places of our codebase that can be simplified by using appropriate STL algorithms and range-based `for` loops. This PR fixes a few of them, in particular:
- uses `std::max/min_element` and `std::accumulate` where applicable
- uses `std::min/max` where applicable
- changes index-based for-loops with range-based for-loops
- fixes initialization bugs (i.e., `index i = -1` yields +inf, not -1)
=> Refactor: use STL algorithms

include/networkit/graph/KruskalMSF.hpp, include/networkit/graph/SpanningForest.hpp, networkit/cpp/graph/KruskalMSF.cpp, networkit/cpp/graph/SpanningForest.cpp, networkit/graph.pyx, networkit/test/test_graph.py
- `SpanningForest` inherits from `Algorithm`, which removes redundant code.
- `KruskalMSF` for unweighted graphs uses `SpanningForest` (and not the more expensive Kruskal algorithm).
- Add a simple Python test for `SpanningForest`.
=> Fix: Spanning Forest and KruskalMSF

networkit/distance.pyx
This PR fixes documentation for Python module `distance`. This also includes conversion of data types to Python native data types as discussed in #870.
=> Documentation: Fix missing and non-visible doc-strings for Python module distance

include/networkit/graph/Graph.hpp
Fixes a narrowing conversion warning from clang-tidy that appears for every `.cpp` file that uses `Graph`.
=> Fix warning (narrowing conversion)

include/networkit/dynamics/GraphEvent.hpp, networkit/cpp/dynamics/GraphEvent.cpp, networkit/cpp/generators/DynamicHyperbolicGenerator.cpp, networkit/dynamics.pxd, networkit/dynamics.pyx
Currently, `GraphEvent` implements two static functions `equal` and `compare`, which should be replaced with proper comparison operators. This PR
- implements comparison operators for `GraphEvent`
- deprecates `GraphEvent::equal` and `GraphEvent::compare`
- makes `GraphEvent` operators available in Python
=> Refactor: GraphEvent

docs/python_api/dynamics.rst, docs/python_api/embedding.rst, docs/python_api/modules.rst, networkit/dynamic.py, networkit/dynamics.pyx, networkit/embedding.pyx, networkit/engineering.pyx, networkit/flow.pyx
This PR fixes documentation for Python module `dynamic, dynamics, embedding, engineering, flow`. This also includes conversion of data types to Python native data types as discussed in https://github.com/networkit/networkit/pull/870.
I also introduced another change for enum-blocks. Until now all enum-definitions were also part of the doc, but only listed without additional context on how to correctly use them and how they are tied to other functions. Example from `centrality`:
For `GraphEvent` this behavior is changed, so that the enum is listed as a parameter. In addition ` :undoc-members:` from automodule has to be removed, so that the original enum-blocks are gone. Example:
=> Documentation fix for Python-modules: dynamic, dynamics, embedding, engineering, flow

include/networkit/generators/DynamicBarabasiAlbertGenerator.hpp, include/networkit/sparsification/SimmelianScore.hpp, networkit/cpp/generators/DynamicBarabasiAlbertGenerator.cpp, networkit/cpp/generators/DynamicForestFireGenerator.cpp, networkit/cpp/io/DotPartitionWriter.cpp, networkit/cpp/io/SNAPEdgeListPartitionReader.cpp, networkit/cpp/sparsification/SimmelianScore.cpp, networkit/cpp/structures/Cover.cpp
- Replace `std::set` with `std::unordered_set` in places where order is not important
- Remove unused instance of `std::unordered_set` from release mode
=> Refactor: replace set with unordered set

networkit/viz.pyx
While the C++ code supports arbitrary dimensions, this is not easily exposed via Cython currently and require more work. This approach just adds 3D coordinates in addition to the already supported 2D coordinates. As a drive-by it fixes some wrong doc-strings. Complete doc-overhaul will be added as part of the current doc-improvement PR series.
=> Python-API: Support for 3D-coordinates with Maxent-Stress layout.

networkit/cpp/distance/test/DistanceGTest.cpp
Tests for AStar never run due to an uninitialized vector.
=> Bug fix in AStar tests

include/networkit/centrality/DynApproxBetweenness.hpp, include/networkit/distance/DynBFS.hpp, include/networkit/distance/DynDijkstra.hpp, networkit/cpp/centrality/DynApproxBetweenness.cpp, networkit/cpp/centrality/test/DynBetweennessGTest.cpp, networkit/cpp/distance/DynBFS.cpp, networkit/cpp/distance/DynDijkstra.cpp, networkit/cpp/distance/test/DynSSSPGTest.cpp
There is some old `DynApproxBetweenness` that is no longer compatible with the current NetworKit version that is supposed to be integrated into NetworKit. It supports deletion for various types of graphs.
After discussing with @angriman, we decided to use the `PImpl`-pattern and have different implementations for the different cases. There is still a bit of long way to go before this code can be merged into the NetworKit code base. 
The aim of this draft PR is to make my work and the `DynApproxBetweeness` code available to anyone who will takeover from here and discussions about whether using `PImpl` is the best solution going forward.
A brief explanation of the commits:
- bc230e7: Converts the current `DynApproxBetweennness` code to pimpl pattern so that `DynApproxBetweennness.h` can be …
=> Integrate various versions of DynApproxBetweeness code

networkit/sampling.py, networkit/stopwatch.py, networkit/viztasks.py, networkit/workflows.py
This PR deprecates (and fixes) some older Python modules, which are not anymore relevant/needed. This includes: sampling, stopwatch, viztasks, workflows.
=> Deprecate Python modules: sampling, stopwatch, viztasks, workflows

networkit/build.sh
The file still refers to the monolithic Cython-interface and is not referenced anywhere (both doc/codebase).
=> Remove networkit/build.sh

docs/python_api/centrality.rst, networkit/algebraic.py, networkit/base.pyx, networkit/centrality.pyx, networkit/clique.pyx, networkit/coarsening.pyx, networkit/coloring.py, networkit/community.pyx, networkit/components.pyx, networkit/correlation.pyx
This unifies documentation for Python modules beginning with `a` to `c` with the rest (Python types, enums, properties). For modules beginning with `d` to `z` these fixes have already been merged. Also some method-docs are fixed, which were not handled properly in previous doc-fix PRs.
=> Python documentation: unify modules algebraic to csbridge with rest

.github/workflows/ci.yml, .github/workflows/scripts/documentation.sh, .github/workflows/scripts/full.sh, docs/python_api/modules.rst, networkit/csbridge.py, networkit/test/test_graphtools.py, networkit/vizbridges.py, notebooks/Visualization.ipynb
This PR adds the following:
- Deprecation of `csbridge.py` in favor of a more generalized module for visualization widgets.
- New module does support creating 2D plots based on Cytoscape or 3D plots based on Plotly, whereas the calling convention is nearly the same as before for `csbridge.py`.
- Changing variables and function names to camelCase.
- A notebook with examples on how to use the new module + unit-tests for CI.
=> Add new module vizbridges: Create visualization widgets in 2D and 3D with Cytoscape and Plotly.

networkit/graph.pyx
Based on a discussion with @avdgrinten - since it not clear yet how to support arbitrary node attributes, maybe it is a good idea to mark the Python-API for node attributes as experimental. This leaves more flexibility in term of changing the API without the need for deprecation.
=> Python: Marks current node attributes API as experimental.

include/networkit/algebraic/DynamicMatrix.hpp, include/networkit/algebraic/Vector.hpp, include/networkit/base/Algorithm.hpp, networkit/cpp/algebraic/test/AlgebraicSpanningEdgeCentralityGTest.cpp, networkit/cpp/algebraic/test/MatricesGTest.cpp, networkit/cpp/algebraic/test/VectorGTest.cpp
- Rename tests so that they are not filtered out by our GTest filter (see the `Unittests-X.cpp` file).
- Add missing tests for matrices iterators
- Add missing tests for Vector
- Removal of unused default constructor and assignment operators. I am not so sure about this; from the covered lines on coveralls, these functions seem to never be used. I would appreciate any feedback about this.
=> Refactor: Untested Code

.gitmodules
The `ttmath` library [1] is unreachable at the moment. For better reliability, I updated the submodule to a fork of ttmath within the NetworKit organization.
[1] https://gitea.ttmath.org/tomasz.sowa/ttmath
=> Fix Unreachable ttmath Library

.github/workflows/ci.yml, .github/workflows/scripts/documentation.sh
This PR updates CI pipeline:
- Minimum versions: clang 3.9 -> 4.0, Python 3.6 -> 3.7
- Images: windows-2019 -> windows-2022, macos-10.15 -> macos-11
- Latest versions: Python 3.9 -> 3.10, gcc 11.1 -> 11.2, clang-format 11 -> 13
=> Update GHA: new images (windows-2022, macos-11), Python 3.10, Clang 4.0, MSVC 14.31

include/networkit/centrality/LocalSquareClusteringCoefficient.hpp, networkit/centrality.pyx, networkit/cpp/centrality/CMakeLists.txt, networkit/cpp/centrality/LocalSquareClusteringCoefficient.cpp, networkit/cpp/centrality/test/CentralityGTest.cpp, networkit/test/test_centrality.py
This PR adds the `LocalSquareClusteringCoefficient`. It is analogous to the `LocalClusteringCoefficient` but evaluates the proportion of realized squares (rather than triangles). See, e.g. https://arxiv.org/abs/cond-mat/0504241.
=> Add square clustering centrality measure.

networkit/cpp/distance/APSP.cpp, networkit/cpp/distance/test/APSPGTest.cpp, networkit/test/test_algorithms.py, notebooks/Centrality.ipynb
As described in #918, APSP does not support graphs with removed nodes. This PR fixes this issue -- distances from/to removed nodes are set to infinity -- and it is based on the fix written by @tillahoffmann (see https://github.com/tillahoffmann/networkit/commit/d1fe1b2288e9251f812f61afc172a25bde79f8b2).
=> Fix APSP for non-existing nodes

networkit/centrality.pyx, networkit/clique.pyx, networkit/coarsening.pyx, networkit/community.pyx, networkit/components.pyx, networkit/distance.pyx, networkit/dynamics.pxd, networkit/embedding.pyx, networkit/engineering.pyx, networkit/flow.pyx, networkit/generators.pyx, networkit/globals.pyx, networkit/graph.pxd, networkit/graphio.pyx, networkit/graphtools.pyx, networkit/helpers.pxd, networkit/helpers.pyx, networkit/linkprediction.pyx, networkit/matching.pxd, networkit/randomization.pyx, networkit/reachability.pyx, networkit/scd.pxd, networkit/simulation.pyx, networkit/sparsification.pyx, networkit/stats.pyx, networkit/structures.pxd, networkit/test/test_algorithms.py, networkit/traversal.pyx, networkit/viz.pyx
Returning distances (or other lists of values) from `cython` can be a significant part of the computational cost in `networkit`. For example, consider the following snippet that gets all pairs shortest paths.
```python
def target(graph):
apsp = nk.distance.APSP(graph).run()
apsp.getDistances()
%lprun -f target [target(nk.generators.ErdosRenyiGenerator(500, 0.1).generate()) for _ in range(1000)]
```
About a third of the time is spent on *getting* distances rather than *evaluating* the distances.
```
Timer unit: 1e-06 s
Total time: 11.8565 s
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
1                                           def target(graph):
2      1000    7833515.0   7833.5     66.1      apsp = …
```
=> Add option to return distances as numpy arrays.

CITATION.cff
- Replace the `number` key (reserved for library accession numbers) with the `issue` key (for issue numbers)
- Fixes #928
=> Fix #928: Use correct CFF key

networkit/exceptions.py, networkit/helpers.pyx, networkit/simulation.pyx
This PR merges the exception module into helpers, since there is only one custom warning/exception. Instead of deprecation the functionality is directly moved, since I assume this functionality is only used internally.
=> Merge Python module 'exceptions' into 'helpers'

.github/workflows/ci.yml, CMakeLists.txt, setup.py
This PR raises the NetworKit C++ standard to 17. The oldest clang version that supports C++17 is 5.0 and it was released on 7.9.17, so I guess that this PR should not be merged before 7.9.22.
=> Move to C++17

.github/workflows/ci.yml
Recently the coverage-run on GHA had several timeouts due to variatons in the CI runner performance. Therefore the timeout is increased.
=> Increase timeout for coverage build

include/networkit/graph/Graph.hpp, networkit/cpp/graph/test/GraphGTest.cpp
Previously non-existing edge ids were returned as `0` which could be misleading. Now they return as `none` to be clear that the edge id doesn't exist.
This addresses #747
=> Make non-existing edge ids return as none instead of 0

networkit/cpp/generators/test/GeneratorsGTest.cpp
testMocnikGeneratorBasic was testing testMocnikGenerator instead of testMocnikGeneratorBasic for some reason.
=> make testMocnikGeneratorBasic actually test MocnikGeneratorBasic

networkit/cpp/graph/GraphTools.cpp
When we sample more than n/2 nodes, we can avoid `std::fill` if we mark as selected non-pivot nodes.
=> Avoid unnecessary std::fill in sampleNodes

networkit/cpp/centrality/test/CentralityGTest.cpp, networkit/cpp/centrality/test/DynBetweennessGTest.cpp
`DynBetweennessGTest` has a lot of useless/duplicate code. This PR simplifies the tests and sets fixed random seeds to make the tests reproducible.
=> Refactor Tests for Dynamic Betweenness

.github/workflows/ci.yml
Impish (short-term release of Ubuntu) is not available anymore in (some) official repos. Switching to jammy (22.04 LTS) should fix the errors with missing repositories on the pipeline.
=> GHA: Change ubuntu repo for gcc-11 from impish to jammy

License.txt
Updated the license. @hmeyerhenke Not sure, whether legally the involved universites should be named.
=> Update MIT license for 2022.

setup.py
Reason: For builds on non-Windows systems, triggering a build via setup.py leads to a CMake warning for unused env variable.
=> Set NETWORKIT_PYTHON_VERSION env only on win32 systems.

CMakeLists.txt, networkit/cpp/components/ParallelConnectedComponents.cpp, networkit/cpp/components/test/ConnectedComponentsGTest.cpp
this addresses #942 
It was previously just initializing everything to the `none` which caused just for the label `none` to be passed around in the algorithm, not assigning anything. So now all nodes are now assigned to their own partition. As none of the nodes were being assigned it would fail the `assert(component[u] != none);` from `ComponentDecomposition::componentOfNode`.
Also, the partition needed to be compacted at the end because the partition IDs would not be continuous and the number of partitions is not updated. Non-existing node entries also need to be removed from the partition in the case where the Graph node Ids are not continuous so that the number of components is correct, otherwise, they would be seen as single node components(the vectors for those partitions would be …
=> Fix segmentation fault in ParallelConnectedComponents

include/networkit/graph/Graph.hpp, networkit/cpp/graph/Graph.cpp, networkit/cpp/io/DibapGraphReader.cpp, networkit/cpp/io/GMLGraphReader.cpp, networkit/cpp/io/GraphToolBinaryReader.cpp, networkit/cpp/io/KONECTGraphReader.cpp, networkit/cpp/io/METISGraphReader.cpp, networkit/cpp/io/NetworkitBinaryReader.cpp, networkit/graph.pxd, networkit/graph.pyx, notebooks/GraphNotebook.ipynb
This PR add an additional (opt.) parameter to addEdge in C++/Python for checking whether an edge is already present in the graph. The documentation/tutorials are updated accordingly.
Also checked for other places, where a warning about unsupported multi-edges might be missing in the documentation. Maybe we could also use the modified addEdge for reader/writer or converter to ensure a warning is triggered when inserting multi-edges (like in #953).
Another approach would be an additional method like `addEdgeSafe`, where multi-edges are checked first.
=> Modify addEdge to check for multi-edges

networkit/cpp/distance/MultiTargetBFS.cpp, networkit/cpp/distance/MultiTargetDijkstra.cpp, networkit/cpp/distance/test/DistanceGTest.cpp
SPSP crashes if the user passes unreachable targets (the node -> distance map lookup fails for unreachable targets because they are never added to the map). This can easily be fixed by setting to infinity the distance to those targets.
This PR also adds a new test with an unreachable target that fails with the previous implementation of SPSP.
=> Fix crash of SPSP in case of unreachable targets

networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/test/GraphGTest.cpp
=> Initialize edgeID datastructure when constr. graph with indexed edges.

.clang-tidy, .github/workflows/build_wheels.yml, .github/workflows/ci.yml, .github/workflows/scripts/clang_tidy.sh, networkit/cpp/centrality/KadabraBetweenness.cpp, networkit/cpp/distance/DynBFS.cpp
This updates the tooling for llvm-based builds / tests. GCC compiler is not touched, since there are still problems with GCC 12+, which needs to be resolved beforehand.
This PR also solves problems on CI, since OpenMP is compatible with -/+ one major version. For the most recent GHA images, the version deviates by two (as seen on #998).
=> CI: Raise llvm toolkit to v15.0 (clang, clang-format, clang-tidy)

docs/DevGuide.rst, extrafiles/tooling/CppClangFormat.py
Unformatted files can be skipped by adding the line `//no-networkit-format` at the top of cpp files. Since all cpp files are
now formatted, this option is not needed anymore.
=> Remove possibility to ignore unformatted files

networkit/cpp/community/PLP.cpp
- Fix a potential bug in PLP (a variable was updated non-atomically in a parallel loop)
- Replace `std::map` with `std::unordered_map` because the order of the elements is not needed
- Minor stylistic changes
=> Refactor PLP

CMakeLists.txt, include/networkit/centrality/TopCloseness.hpp, include/networkit/centrality/TopHarmonicCloseness.hpp, networkit/centrality.pyx, networkit/cpp/centrality/TopCloseness.cpp, networkit/cpp/centrality/TopHarmonicCloseness.cpp, networkit/cpp/centrality/test/CMakeLists.txt, networkit/cpp/centrality/test/CentralityGTest.cpp, networkit/cpp/centrality/test/TopClosenessGTest.cpp
This PR introduces the following changes:
- Support for passing a list of nodes, restricting top-k calculation to only this nodes (but based on the truth given by graph G).
- Tests for new parameter
- Minor refactor of documentation, bug fixes for both Python + C++ code
- Refactor TopHarmonicCloseness to support multiple consecutive runs
If the number of nodes in the list << number of nodes in the graph, the running time is improved significantly. Example: 
- 200k nodes in graph
- 100 nodes in input list
- speedup 165x (TopCloseness)
- speedup 55x (TopHarmonicCloseness)
~~Currently the PR is still work in progress.~~
=> Refactor TopCloseness, TopHarmonicCloseness

include/networkit/generators/BarabasiAlbertGenerator.hpp, networkit/generators.pyx
The ability to expand a given graph with the Babarasi-Albert generator is already implemented in C++ and in Python as well. But this ability is not reflected in the documentation which mistakes the user into believing that such a thing is not possible. This merge request updates the documentation to reflect the underlying capabilities of the framework.
Contribution Guidelines: 
1. Sorry I could not find a development branch, therefore this pull request is on the master branch.
2. No code has been changed only the documentation, therefore no unit tests have been run on this change.
3. No additional Code in the form of notebooks is provided due to this updating **only** the documentation
Thanks for the great library!
=> Added a missing piece of information to the documentation

Dockerfile, requirements.txt
`sklearn` is deprecated [1], update to `scikit-learn`.
[1] https://scikit-learn.org/stable/modules/generated/sklearn.utils.deprecated.html
=> Update sklearn -> scikit-learn

networkit/cpp/io/NetworkitBinaryWriter.cpp, networkit/cpp/io/test/IOGTest.cpp
This addresses  #963 by changing an array with a map to avoid errors when writing.
=> Fix NetworkitBinaryWriter - writing graphs with deleted nodes

include/networkit/distance/PrunedLandmarkLabeling.hpp, networkit/cpp/distance/CMakeLists.txt, networkit/cpp/distance/PrunedLandmarkLabeling.cpp, networkit/cpp/distance/test/DistanceGTest.cpp, networkit/distance.pyx, networkit/test/test_distance_algorithms.py, notebooks/Distance.ipynb
This PR brings the Pruned Landmark Labeling algorithm by Akiba et al. [1]. The algorithm computes distance labels which are used to answer shortest-path distance queries.
I wrote this code a few years ago and, finally, I found some time to polish it.
[1] https://dl.acm.org/doi/10.1145/2463676.2465315
=> New Algorithm: Pruned Landmark Labeling

networkit/cpp/embedding/Node2Vec.cpp, networkit/cpp/embedding/test/FiniteEmbeddingTest.cpp
This PR adds checks for node2vec (directed, has isolated nodes) in order to avoid segfaults (see #1011). Not included here, but on the roadmap: Adding the support of directed graphs for node2vec.
=> node2vec: Add checks in order to avoid unexpected behavior and segfaults

.github/workflows/build_wheels.yml, .github/workflows/ci.yml
This PR fixes issue #1048. In addition, the timeout for the coverage built is increased and v2-actions from GitHub are exchanged for their v3 counterpart due to deprecation warnings.
Will look into decreasing the coverage build time outside of this PR (some test cases again take several minutes).
=> Update GHA: Fix Python 3.11 wheel build, increase timeout for coverage, modernize GH-actions

networkit/cpp/distance/DynBFS.cpp
`DynBetweennessGTest.testDynApproxBetweenessGeneratedGraph` fails with segfault, see the screenshot below:
I compiled NetworKit on macOS 13.2.1 (M2 chip), llvm Clang 15.0.7 and with these flags:
```
cmake -DNETWORKIT_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DNETWORKIT_WITH_SANITIZERS=address -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_STANDARD=17 ..
```
This happens for two reasons:
- There seems to be a pretty obvious mistake in `DynBFS.cpp`: the `queues` vector has size `maxDistance + 1`
https://github.com/networkit/networkit/blob/333cb9a7e431dfadf016323491dcfd24227112c5/networkit/cpp/distance/DynBFS.cpp#L77 and the heap-buffer-overflow happens at this line
https://github.com/networkit/networkit/blob/333cb9a7e431dfadf016323491dcfd24227112c5/networkit/cpp/distance/DynBFS.cpp#L88 which could …
=> Fix DynBfs

networkit/cpp/centrality/ApproxSpanningEdge.cpp, networkit/cpp/centrality/TopCloseness.cpp, networkit/cpp/distance/test/SSSPGTest.cpp, networkit/cpp/generators/DynamicBarabasiAlbertGenerator.cpp, networkit/cpp/generators/LFRGenerator.cpp, networkit/cpp/generators/quadtree/test/QuadTreeGTest.cpp, networkit/cpp/io/SNAPEdgeListPartitionReader.cpp
- Remove unused variables
- Use `tlx::unused` for variables used only in debug mode
- Use pre-increment instead of post-increment where possible
=> Fix unused variable warnings.

CMakeLists.txt, docs/python_api/base.rst, docs/python_api/dynbase.rst, docs/python_api/modules.rst, include/networkit/centrality/DynBetweennessOneNode.hpp, networkit/base.pxd, networkit/base.pyx, networkit/centrality.pyx, networkit/components.pyx, networkit/distance.pyx, networkit/dynbase.pxd, networkit/dynbase.pyx, networkit/reachability.pyx
This PR adds python bindings for the `DynAlgorithm` class in a new `dynalgorithm.pxd`/`dynalgorithm.pyx` file and updates all existing dynamic algorithms to use this base class.
Previously, all python bindings of dynamic algorithms implement the same `update` and `updateBatch` forwarding code, which is now moved to the `DynAlgorithm` base class.
The setup is a little weird because of Cython limitations. First, a figure of the new class hierarchy, where `MyAlgorithm` is any dynamic algorithm:
```
_CythonParentClass
^              ^
|              |
Algorithm          _CythonSubclassDynAlgorithm
^                     ^
|                     |
MyAlgorithm    -->    DynAlgorithm
```
Explanation:
- Cython (or Python in general) does not allow multiple inheritance of `cdef class`es (also called …
=> Add DynAlgorithm bindings to python

networkit/distance.pyx
this PR splits up #1066 , this fix is necessary to test jaccardDistance in python (currently commented out in #1077)
=> distance.pyx: repairs jaccardDistance

networkit/test/test_independentset.py
this PR should also fix the occuring build fail, caused by testLubyAlgorithm by removing a wrong assertion
=> python test: adds test in test_independentset.py

.github/workflows/build_wheels.yml, .github/workflows/ci.yml, .github/workflows/scripts/documentation.sh, .github/workflows/scripts/full.sh, pyproject.toml
This PR fixes invalid C++ code, which the recently released version of Cython (3.0.0) produces (see: #1106). Until this is fixed, the previously stable 0.29.X version is used.
Furthermore, wheel is added as build requirement in order to create wheels when doing non-editable install via pip.
=> pyproject.toml: Add wheel as requirement and pin stable versions of cython, setuptools.

.github/workflows/ci.yml, .github/workflows/scripts/clang_tidy.sh, networkit/cpp/centrality/ApproxElectricalCloseness.cpp, networkit/cpp/centrality/DynBetweenness.cpp, networkit/cpp/components/StronglyConnectedComponents.cpp, networkit/cpp/generators/DynamicHyperbolicGenerator.cpp, networkit/cpp/generators/HavelHakimiGenerator.cpp, networkit/cpp/generators/HyperbolicGenerator.cpp, networkit/cpp/generators/MocnikGenerator.cpp, networkit/cpp/generators/PubWebGenerator.cpp, networkit/cpp/randomization/CurveballImpl.cpp, networkit/cpp/sparsification/SimmelianScore.cpp
Building NetworKit with:
```
cmake -DNETWORKIT_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_STANDARD=17 -DNETWORKIT_CLANG_TIDY=ON
```
fails because of `modernize-use-emplace`. Shouldn't these error be caught by our CI?
=> Fix clang-tidy errors

include/networkit/algebraic/CSRGeneralMatrix.hpp, include/networkit/algebraic/DenseMatrix.hpp, include/networkit/algebraic/DynamicMatrix.hpp, networkit/cpp/Unittests-X.cpp, networkit/cpp/algebraic/DenseMatrix.cpp, networkit/cpp/algebraic/test/MatricesGTest.cpp
The first commit adds missing matrix functions and tests:
- For CSRMatrix: functions for iterating over all elements of the matrix, including zeros.
- For DenseMatrix: functions to compute the adjacency, Laplacian, and incidence matrix of a graph and a diagonal matrix.
- For DynamcMatrix: functions to iterate over the (non-zero) elements.
In this way, all matrix classes offer the same set of APIs.
The second commit refactors the unit tests for matrices. It defines a typed test suite (see https://google.github.io/googletest/advanced.html#typed-tests) that performs the unit tests on all the matrix types. This is much more convenient than defining a templated unit test (as we were doing before) because:
- Failures much are easier to track: if a test fails, the type is reported in the logs.
- …
=> Refactor Matrices and MatricesGTest

networkit/test/test_centrality.py
this PR fixes a rarely occuring bug, in which the assertions do not work
=> test_centrality.py: fix groupCloseness test

.clang-format
Running clang-format does not work for me because of the duplicate `IncludeCategories`.
=> Fix clang-format configuration file.

include/networkit/auxiliary/StringTools.hpp
`std::string_view` is a non-owning read-only view of a string, and it helps to avoid unnecessary memory allocations [1]. I think we should start using it instead of `const std::string&`. 
[1] https://www.modernescpp.com/index.php/c-17-avoid-copying-with-std-string-view/
=> Use string_view instead of const string&.

networkit/graphio.pyx, networkit/test/test_graphio.py
This PR adds a new `guessFileFormat` function to the `graphio` module (python). This function is used to guess the file format when `graphio.readGraph(path, fileformat)` is called with `fileformat=None` - which is now the default value for the `fileformat` parameter. Guessing may fail and raise an exception (in which case one needs to provide the format manually as before). 
The guessing strategies are quite simple and will probably fail for some cases where the format is actually rather easy to guess, but for now it works for the most common file structures and types (see tests). We can improve this function when new ideas/problems arise.
Direct use:
```py
>>> import networkit as nk
>>> nk.graphio.guessFileFormat("input/airfoil1.graph")
<Format.METIS: 6>
```
With `readGraph`:
```py
>>> …
```
=> graphio: add function to guess file format

include/networkit/geometric/HyperbolicSpace.hpp, networkit/cpp/centrality/test/CentralityGTest.cpp, networkit/cpp/generators/HyperbolicGenerator.cpp, networkit/cpp/geometric/HyperbolicSpace.cpp
The past implementation generated random numbers and sorted them seperately.
I replaced this with an algorithm that directly generates sorted random numbers (Program 1 from this 1980 paper: [Generating Sorted Lists of Random Numbers](https://dl.acm.org/doi/10.1145/355900.355907)).
I tested the performance of this change using the following configuration:
```
HyperbolicGenerator gen{20000000};
auto graph = gen.generate();
```
Here are some numbers:
​ | before | after
--- | --- | ----
Total Runtime | 14.9 s | 12.9 s
Point generation runtime | 3.1 s | 1.3 s
Memory usage should also be a bit lower, because I removed the permutation and copy vectors.
Also note that the `fillPointsSorted` is basically a copy of the `fillPoints` functions. I kept the old `fillPoints` function because it is still …
=> Slightly improve the performance of the HyperbolicGenerator

.github/workflows/build_wheels.yml, pyproject.toml
This PR also adds wheels for Python 3.12 - fixing issues: #1150, #1144.
=> Remove pin for older setuptools, adding support for Python 3.12.

include/networkit/graph/Graph.hpp, networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/test/GraphGTest.cpp
this commit restores the original removeEdge api ( as referenced in #1146 ) and adjusts the tests
=> restore_removeEdge_api

extrafiles/tooling/CppClangFormat.py, extrafiles/tooling/nktooling/__init__.py
Reasons for this PR:
- Other versions of clang-format in general lead to style errors
- For some distributions, "clang-format" also includes binaries/tools with a non-numeric suffix, like `clang-format-diff`. These are now checked.
=> Pin clang-format version to 17 and mitigate ValueErrors

.github/workflows/ci.yml, CMakeLists.txt, include/networkit/generators/ErdosRenyiEnumerator.hpp, include/networkit/graph/Graph.hpp, include/networkit/layout/LayoutAlgorithm.hpp, networkit/cpp/centrality/GroupClosenessGrowShrink.cpp, networkit/cpp/distance/NeighborhoodFunctionHeuristic.cpp, networkit/cpp/generators/test/ErdosRenyiEnumeratorGTest.cpp, networkit/cpp/generators/test/GeneratorsGTest.cpp, networkit/cpp/geometric/test/GeometricGTest.cpp, networkit/cpp/io/test/IOBenchmark.cpp, networkit/cpp/matching/Matching.cpp, networkit/cpp/scd/LocalDegreeDirectedGraph.hpp, networkit/cpp/scd/LocalTightnessExpansion.cpp, networkit/cpp/viz/MaxentStress.cpp, networkit/cpp/viz/test/VizGTest.cpp
Notes: 
- GCC is not updated to 13.X for macOS, since the compiler is currently broken when working with `libomp` on CI (not reproducible locally).
- clang-tidy is not updated to 18.X. This is out of scope for this PR, due to non-minor refactoring.
- The `-permissive` flag is added for MSVC builds, since when building with Visual Studio, the flag is enabled by default. This marks nonconforming code (related to MSVC + a CPP-standard).
=> CI: fix Windows build and update CI + build settings

.github/workflows/scripts/core_sanitizers_coverage.sh, include/networkit/graph/Graph.hpp, networkit/cpp/graph/test/GraphGTest.cpp, networkit/graph.pxd, networkit/graph.pyx, networkit/nxadapter.py, networkit/test/test_graph.py, networkit/test/test_nxadapter.py
Adds support for node and edge attributes to the networkx -> networkit graph conversion function.
Additionally, adds python bindings for the attribute getter functions.
This PR is not complete yet. The code should be finished (imo), but there is a weird error when accessing edge attributes of directed graphs. I think this problem is not related to the new code in this PR, but more investigation is necessary.
=> New feature: convert networkx attributes to networkit attributes

networkit/test/test_vizbridges.py, networkit/vizbridges.py
This PR adds a new (failing) test for the case where an incomplete defaultdict is provided to the `widgetFromGraph` function and fixes the problem. 
The previous implementation used `dict.get()` which always returns `None` if the value is not in the dict - even when a default factory is available (we misread the documentation). Now, we use `[]` to access values, which does use the default factory if available.
=> vizbridges: edge scores with default dict

networkit/cpp/distance/test/DistanceGTest.cpp
The CI fails occasionally because of this test (i.e.: https://github.com/networkit/networkit/actions/runs/8687798112/job/23822052569?pr=1207)
=> Fix GTest: make algebraicDistanceGTest deterministic

networkit/cpp/community/test/LouvainMapEquationGTest.cpp
adresses #1184 to make the test deterministic: basically substituting the random clustering graph generator by non-random graph generator (BA)
=> fix: LouvainMapGTest

include/networkit/graph/Graph.hpp, networkit/cpp/graph/test/AttributeGTest.cpp
fixes #1187 for std::string (note: this implementation still does not support strings that contain `\n`!)
vector types are not supported yet; this will require more complex changes (like adding a serialization library).
Fixing the string bug is higher priority though, because string attributes are available in python as well, while vector types are not.
=> fix string attribute read

networkit/graph.pyx
With numpy>=2, Cython build process does create unknown types error. Changing the variables according to: https://numpy.org/doc/stable/reference/c-api/dtype.html fixes this problem and is also compatible with numpy 1.X.
=> Build: Add compatibility with upcoming numpy 2

include/networkit/numerics/LAMG/Lamg.hpp, include/networkit/numerics/LAMG/LevelHierarchy.hpp, include/networkit/numerics/LAMG/MultiLevelSetup.hpp, include/networkit/numerics/LAMG/SolverLamg.hpp, networkit/cpp/algebraic/test/CMakeLists.txt, networkit/cpp/centrality/test/CMakeLists.txt, networkit/cpp/distance/test/CMakeLists.txt, networkit/cpp/numerics/CMakeLists.txt, networkit/cpp/numerics/LevelHierarchy.cpp, networkit/cpp/numerics/MultiLevelSetup.cpp, networkit/cpp/numerics/SolverLamg.cpp, networkit/cpp/viz/CMakeLists.txt
Various small changes to the LAMG helper classes to improve readability, performance, and allow use in `const` contexts. Also fixes a few problems such that the template `Matrix` can now be any of our matrix classes - and now uses explicit template instantiation to verfiy this.
=> Improve LAMG helper classes

networkit/graph.pyx, networkit/test/test_graph.py
This PR addresses the issue that `addEdge(u,v)` in python behaves differently to c++ (and change the corresponding test). 
- Previously when the parameter `addMissing` has been set to True and either node u or v did not exist in the graph, all not existing nodes from the previous numberOfNodes() to max(u,v) have been added to the graph aswell as u or v. 
- This was not properly documented and furthermore created potentially many unused nodes.
=> python: fix addEdge when adding missing nodes

include/networkit/numerics/ConjugateGradient.hpp, include/networkit/numerics/LAMG/Lamg.hpp, include/networkit/numerics/LAMG/SolverLamg.hpp, include/networkit/numerics/LinearSolver.hpp, networkit/cpp/numerics/CMakeLists.txt, networkit/cpp/numerics/Lamg.cpp, networkit/cpp/numerics/test/CMakeLists.txt, networkit/cpp/numerics/test/LAMGGTest.cpp, networkit/cpp/numerics/test/LAMGSolverGTest.cpp, networkit/cpp/numerics/test/SolverLamgGTest.cpp, networkit/cpp/viz/test/CMakeLists.txt
This PR adds support to the Lamg solver to deal with multi-component systems in parallel.
Related issue: #1167
Todos:
Note that this PR depends on #1210 and #1214 which should be merged first. (currently all commits from #1210 are listed here as well, but this PR is only for changes in LAMG.hpp and tests)
=> Lamg: parallel solve for multiple components

networkit/cpp/distance/DynDijkstra.cpp, networkit/cpp/distance/test/DynSSSPGTest.cpp
This PR addresses the [issue](https://github.com/orgs/networkit/projects/1/views/1?pane=issue&itemId=59028430) whereby the DynDijkstra algorithm did not properly adjust the previous vector that is being used to construct the shortest paths. Furthermore it adds the corresponding test in the already existing DynDijkstra test-suite.
=> cpp: fix bug in DynDijkstra and adjust test

.github/workflows/build_wheels.yml, include/networkit/io/MTXGraphReader.hpp, include/networkit/io/MTXParser.hpp, networkit/cpp/io/CMakeLists.txt, networkit/cpp/io/MTXGraphReader.cpp, networkit/cpp/io/MTXParser.cpp, networkit/cpp/io/test/IOGTest.cpp
This PR finalizes #1132 with the additional tests. Note that the original code has been slightly adjusted, namely the `MTXGraphReader.cpp` now uses `addEdge()` instead of `addPartialEdge()` which resulted in a incomplete Graph data structure in some cases.
=> cpp: adds MTXGraphReader and corresponding tests

networkit/cpp/algebraic/DynamicMatrix.cpp, networkit/cpp/algebraic/test/MatricesGTest.cpp
For two matrices A (n\*m) and B(m\*p), the size of the resulting matrix C=AB is n\*p. The sparse accumulator should have size p - which is `B.numberOfColumns()`
=> fix DynamicMatrix * DynamicMatrix

networkit/base.pxd, networkit/community.pyx, networkit/components.pyx, networkit/distance.pyx, networkit/dynamics.pyx, networkit/dynbase.pxd, networkit/generators.pyx, networkit/globals.pyx, networkit/graph.pxd, networkit/graphio.pyx, networkit/graphtools.pyx, networkit/randomization.pyx, networkit/traversal.pyx, networkit/viz.pyx
this PR changes the cython function signatures, because in version >3.0 of cython the previous signatures result in warnings and will eventually be disallowed
=> cython: change ordering of function signatures (nogil)

include/networkit/graph/Attributes.hpp, include/networkit/graph/Graph.hpp, networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/GraphTools.cpp, networkit/cpp/graph/test/AttributeGTest.cpp, networkit/test/test_graph.py
This PR fixes some copy and move bugs for attributes. Previously, the graph pointer stored in some attribute classes did not change when the graph was copied, and data stored in attributes was not copied.
Changes:
- Attribute classes are now a seperate header (taken from #1222)
- Sanity checks are now debug-mode only (solves #1248)
- There is now a clear 1:1 relation between `Graph` and `AttributeMap`
- `AttributeMap` cannot be copied implicitly; a new graph pointer is required
- removed the graph pointer from AttributeStorage; validity checks are now done in Attribute instead
- added explicit copy assignment and constructor to Graph to use the new AttributeMap copy constructor
- fix some details in the graphTools conversion code
- Graph move operators will update the pointer in …
=> Fix copy operations for attributes

include/networkit/graph/GraphTools.hpp, include/networkit/graph/TopologicalSort.hpp, networkit/cpp/graph/GraphTools.cpp, networkit/cpp/graph/TopologicalSort.cpp, networkit/cpp/graph/test/TopologicalSortGTest.cpp, networkit/graphtools.pyx, networkit/test/test_graphtools.py
Fixed issue #1224 by adding an optional argument to for a continuous node id mapping, i.e. mapping of current node ids to [0,n). 
Replaced raw accesses into vectors by the index operator with calls to `.at()` which performs bounds checks. This fixes an unreported bug which causes undefined behaviour and specifically segmentation faults when node ids are not in the [0,n) interval. The new behaviour is to throw an exception with a descriptive message instead.
If a node id mapping is passed to the algorithm, it maps all node ids through the mapping (and performs bounds checks as in above paragraph). If node ids are not mapped to [0,n), the bounds checks will cause the algorithm to throw an exception with an appropriate message.
Also refactored tests for TopologicalSort and added new tests …
=> Fixes to TopologicalSort

networkit/cpp/generators/RmatGenerator.cpp
This fixes an issue, where a variable is implicitly cast to uint32, leading to wrong results for the expected number of nodes.
=> Fix RMatGenerator for large instances 

.github/workflows/scripts/full.sh
This fixes an issue, where tlx is built per default as debug build. New versions of CMake add `_debug` per default to lib names in this case. In addition tlx submodule is updated to the most recent version.
=> CI: Update tlx version + set CI build to Release for external build

include/networkit/graph/Attributes.hpp, networkit/cpp/graph/test/AttributeGTest.cpp
Direct assignment of attributes to each other (`attr[i] = attr[j]`) previously used the implicitly defined assignment operators for `IndexProxy` which do not modify the attribute value. The new implementation with `requires` clauses also ensure that assignment operators are `deleted` for const attributes (the old implementation implicitly defined them).
=> Fix assignment for Attribute from other Attribute

.github/workflows/build_wheels.yml, .github/workflows/ci.yml, .github/workflows/scripts/coverage.sh, UBSAN.filter, include/networkit/community/LouvainMapEquation.hpp, include/networkit/graph/GraphTools.hpp, include/networkit/graph/TopologicalSort.hpp, networkit/cpp/centrality/test/CentralityGTest.cpp, networkit/cpp/community/LouvainMapEquation.cpp, networkit/cpp/generators/ChungLuGeneratorAlamEtAl.cpp, networkit/cpp/graph/GraphTools.cpp, networkit/cpp/graph/TopologicalSort.cpp
This PR effectively fixes the broken coverage upload. Due to also testing for leaks and continuing on errors, the coverage for the C++ code way empty if a potential address leak is found. Both tests are now split into different runs. This should also speedup the coverage run due to having both leak checks and coverage at the same time.
In addition several potential leaks are fixed. One fix in `random.cc` from libstd is not fixed, since it is intentional. The fix instead is to remove the out-of-bound sanitizer checks for this file by adding a filter.
=> CI: Split coverage and leak build, fix leaks, remove aarch64 wheel build

networkit/simulation.pyx
In networkit/simulation.pyx: We suppress now the warning after import of the pandas package and instead throw an error only when we actually want to use this package. This looks like this: 
Output without pandas when: 
'
>>> from networkit import *
>>> G = readGraph("./input/airfoil1.graph", Format.METIS)
>>> sim = simulation.EpidemicSimulationSEIR(G, 1, 0.1, 1, 0, 0)
>>> sim.getData()
' 
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "networkit/simulation.pyx", line 70, in networkit.simulation.EpidemicSimulationSEIR.getData
raise MissingDependencyError("pandas")
networkit.support.MissingDependencyError: Optional dependency pandas is not installed
##############################################
Output with pandas installed:
Empty DataFrame
Columns: [zero, time, …
=> Issue #938: suppress warning for pandas in networkit/simulation.pyx

include/networkit/community/ParallelLeiden.hpp, networkit/community.pyx
This PR adds a warning to the users about the results of the current implementation of ParallelLeiden in NetworKit. Effectively, the implementation currently does not meet the guarantees of non-disconnected communities as defined by the algorithm. 
In contrast to a previous (closed) PR #1266, where the algorithm was removed, we opted now to a warning in both C++ and Python + further documentation in order not to break existing code. This warning is of temporary nature until the error is fixed. Initial tests based on the findings of Sahu et. al show problematic results for both sequential and thread parallel executions for some kind of networks + combinations of parameter gamma.
=> Add documentation of the reported behavior of ParallelLeiden

include/networkit/graph/Attributes.hpp, networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/test/AttributeGTest.cpp
fixes #1277 and additionally fixes the same issue for `maintainSortedEdges` as well.
=> fix edge attribute indexing bugs when changing edge ids

include/networkit/auxiliary/SignalHandling.hpp, networkit/cpp/auxiliary/SignalHandling.cpp
fixes #1271
- there was a bug where the ownership was never set correctly:`NetworKit::GlobalState::setRootSet(caller)` is the wrong function; it should be `setRoot(caller)`. Because of implicit conversion of pointers to bool we never noticed this bug.
- additionally, I cleaned up the code a bit to make understanding easier and added some documentation.
=> fix signal handler

networkit/__init__.py, pyproject.toml, version.py
This PR raises the version from `11.1` -> `11.1.post1`. 
See issue #1314 for details why the Linux package is broken in the newest release. Since the code itself is ok and this is merely a building environment problem, we do a `post`-release instead of a patch release.
=> Add post-release tag for fixing pypi linux build.

include/networkit/distance/FloydWarshall.hpp, networkit/cpp/distance/CMakeLists.txt, networkit/cpp/distance/FloydWarshall.cpp, networkit/cpp/distance/test/CMakeLists.txt, networkit/cpp/distance/test/FloydWarshallGTest.cpp
This PR introduces the Floyd-Warshall algorithm for computing all-pairs shortest paths in a weighted graph. It supports both directed and undirected graphs, correctly handles negative edge weights, and detects negative cycles. If multiple shortest paths exist with the same distance, the algorithm selects the one with the fewest nodes.
- Computes shortest path distances between all node pairs.  
- Detects negative cycles in the graph.  
- Provides path reconstruction via `getNodesOnShortestPath(source, target)`.  
- Prefers the shortest path with the fewest nodes when multiple exist.  
The algorithm runs in O(n³) time complexity, with n representing the number of nodes, making it suitable for small to medium-sized graphs.
=> Add Floyd-Warshall algorithm

.github/workflows/ci.yml
The change is done since `ubuntu-20.04` is deprecated.
=> CI: Upgrade ubuntu-20.04 for min compiler support build.

networkit/graphio.pyx
**Summary**  
This PR fixes minor typos in `networkit/graphio.pyx` docstrings for `readGraph`, `readGraphs`, and `writeGraph`.  
**Changes**  
- Corrected "Fromat.EdgeList" → "Format.EdgeList"  
**Why**  
The misspelling was reported in #1340 and appeared in multiple docstrings that are rendered in the Python API documentation. This change ensures correct spelling in both the source and generated documentation.  
**Scope**  
Documentation only; no functional changes.  
**Issue**  
Fixes #1340
=> closes (#1340) : docs(graphio): fix typos 'Fromat' → 'Format' 

include/networkit/io/NetworkitBinaryGraph.hpp, include/networkit/io/NetworkitBinaryWriter.hpp, networkit/cpp/io/NetworkitBinaryReader.cpp, networkit/cpp/io/NetworkitBinaryWriter.cpp, networkit/cpp/io/test/IOGTest.cpp
This PR fixes a crash when writing an empty graph (numberOfNodes() == 0) using NetworkitBinaryWriter.
Closes [#909](https://github.com/networkit/networkit/issues/909).
When serializing an empty graph, the internal logic attempted to compute offset values based on the number of chunks. However, if nodes == 0, then chunks == 0, and expressions like (chunks - 1) underflowed due to unsigned arithmetic. This led to corrupted headers and potential segmentation faults during read/write operations.
This PR addresses the issue by:
- Zero-initializing all uint64_t fields of the header using brace initialization
- Explicitly handling the empty graph case at the beginning of NetworkitBinaryWriter::writeData():
=> Fix crash when writing empty graph in NetworkitBinaryWriter

networkit/cpp/auxiliary/test/AuxGTest.cpp, networkit/cpp/auxiliary/test/CMakeLists.txt, networkit/cpp/auxiliary/test/LoggingTimerGTest.cpp
This PR improves test coverage for the `Aux::Timer` and `Aux::LoggingTimer` components.
- **Closed coverage gaps** in the `Timer` and `LoggingTimer` APIs
- **Moved** the existing `testTimer` from `AuxGTest.cpp` into a new file: `LoggingTimerGTest.cpp`
- **Split** the original `testTimer` into multiple smaller test cases
=> Improve LoggingTimer Test Coverage and Structure

networkit/cpp/auxiliary/test/CMakeLists.txt, networkit/cpp/auxiliary/test/SpinLockGTest.cpp
This PR adds a test suite for the internal `Aux::Spinlock` class. No production code was changed.
=> Add unit tests for Aux::Spinlock.

networkit/cpp/graph/test/SpanningGTest.cpp
This PR adds a single test case to cover a previously uncovered line in the KruskalMSF algorithm implementation.
=> Add missing test for KruskalMSF
