networkit/networkit

networkit/_NetworKit.pyx, networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/Graph.h
=> Automatically remove incident edges on removeNode

networkit/cpp/graph/test/GraphGTest.cpp
=> removeNode test adapted for new behaviour

networkit/cpp/scd/GCE.cpp, networkit/cpp/scd/GCE.h, networkit/cpp/scd/test/SelectiveCDGTest.cpp
Reverts kit-parco/networkit#18
=> Revert "Faster GCE, also for weighted graphs"

networkit/_NetworKit.pyx
=> Expose restoreNode to Python

.gitignore, SConstruct
=> Shared library build in SCons

networkit/generators.py
This provides a wrapper class for the BTER implementation FEASTPACK (http://www.sandia.gov/~tgkolda/feastpack/). A previous version of this class was already included in NetworKit but got lost in some merge commit.
=> (Re-)Add the BTER wrapper class

SConstruct
Reverts kit-parco/networkit#58
=> Revert "SConstruct: Improved reading external library paths from build.conf"

networkit/_NetworKit.pyx, networkit/cpp/distance/BFS.cpp, networkit/cpp/distance/BFS.h, networkit/cpp/distance/Dijkstra.cpp, networkit/cpp/distance/Dijkstra.h, networkit/cpp/distance/SSSP.cpp, networkit/cpp/distance/SSSP.h
=> Deprecate SSSP::getStack and replace with getDistanceVector

.travis.yml
=> Enable assertions on Travis

networkit/cpp/centrality/Betweenness.cpp, networkit/cpp/centrality/DynBetweenness.cpp, networkit/cpp/centrality/EstimateBetweenness.cpp, networkit/cpp/distance/test/SSSPGTest.cpp
=> Remove usage of deprecated getStack

networkit/_NetworKit.pyx, networkit/cpp/centrality/Closeness.h
Addresses normalization request in #81.
=> Normalize closeness scores by default

networkit/_NetworKit.pyx, networkit/centrality.py, networkit/cpp/centrality/GroupCloseness.cpp, networkit/cpp/centrality/GroupCloseness.h
Added class for computing group closeness (based on ALENEX18 paper)
=> Group Closeness

networkit/cpp/centrality/GroupCloseness.cpp
=> fixed group closeness

SConstruct
=> Fix tabs in SConstruct

networkit/cpp/auxiliary/Enforce.h
Proper doxygen documentation for enforce methods and helper structs.
=> Documentation for enforcement helpers

networkit/cpp/linkprediction/SameCommunityIndex.h
Added docs to overridden public methods for sake of completeness.
=> Documentation for SameCommunityIndex

networkit/__init__.py
=> Prevent index out of range exception while counting isolated nodes

networkit/cpp/auxiliary/BucketPQ.cpp, networkit/cpp/auxiliary/BucketPQ.h, networkit/cpp/centrality/MahmoodyGroupBetweenness.cpp, networkit/cpp/centrality/MahmoodyGroupBetweenness.h, networkit/cpp/centrality/test/MahmoodyGroupBetweennessGTest.cpp, networkit/cpp/centrality/test/MahmoodyGroupBetweennessGTest.h
This commit contains the MahmoodyGroupBetweenness-feature and updates BucketPQ with a getKey-Method which is used by MahmoodyGroupBetweenness. GTests for MahmoodyGroupBetweenness are also included.
=> MahmoodyGroupBetweenness + Updated BucketPQ

networkit/_NetworKit.pyx
=> Fixed cython file for TopCloseness, TopHarmonicCloseness, GroupCloseness, CommuteTimeDistance

networkit/_NetworKit.pyx
Signed-off-by: Eugenio Angriman <angriman@informatik.uni-koeln.de>
=> Many other inheritance fixes

networkit/_NetworKit.pyx, networkit/cpp/distance/Volume.cpp, networkit/cpp/distance/Volume.h, networkit/cpp/generators/MocnikGenerator.cpp, networkit/cpp/generators/MocnikGenerator.h, networkit/cpp/generators/MocnikGeneratorBasic.cpp, networkit/cpp/generators/MocnikGeneratorBasic.h, networkit/distance.py, networkit/generators.py
Dear maintainer,
As already discussed with Henning, I have created a pull request to add some functionality.  If there should be any questions, please let me know.
I will later add references to my paper (as discussed per mail) when the paper is out.
I did not add me to the list of contributors but you are welcome to do so.
Kind regards,
Franz-Benjamin
=> Pull request: MocnikGenerator, MocnikGeneratorBasic, and volume

Doc/doc/credits.rst, Doc/doc/features.rst, networkit/cpp/distance/Volume.cpp, networkit/cpp/distance/Volume.h, networkit/cpp/generators/MocnikGenerator.cpp, networkit/cpp/generators/MocnikGenerator.h, networkit/cpp/generators/MocnikGeneratorBasic.cpp, networkit/cpp/generators/MocnikGeneratorBasic.h, networkit/cpp/generators/test/GeneratorsBenchmark.cpp, networkit/cpp/generators/test/GeneratorsGTest.cpp
This pull request improves code quality and running time.  I have also improved the (internal) documentation.  You previous comments have been very helpful.  If there are further comments that I should incorporate into the code, I would be happy to receive them.  Thank you!
=> MocnikGenerator: Code quality

networkit/cpp/generators/test/GeneratorsGTest.cpp
Signed-off-by: Eugenio Angriman <eugenio.angriman@informatik.hu-berlin.de>
=> Added missing test for clustered random graph generator

networkit/cpp/centrality/GroupDegree.cpp, networkit/cpp/centrality/GroupDegree.h, networkit/cpp/centrality/test/CentralityGTest.cpp
Signed-off-by: Eugenio Angriman <eugenio.angriman@informatik.hu-berlin.de>
=> Group degree fix

networkit/cpp/centrality/GroupDegree.cpp, networkit/cpp/centrality/GroupDegree.h
Signed-off-by: Eugenio Angriman <eugenio.angriman@informatik.hu-berlin.de>
=> Fixed group degree

.travis.yml, CMakeLists.txt, setup.py
Same changes as in https://github.com/kit-parco/networkit/pull/212, but now resubmitted against Dev.
=> CMake: AppleClang support

.gitignore
Sometimes I find it useful to store vim sessions to a `.vim` file.
=> Added *.vim files to .gitignore for vim sessions

networkit/_NetworKit.pyx, networkit/centrality.py, networkit/cpp/auxiliary/PQVector.h, networkit/cpp/auxiliary/Random.cpp, networkit/cpp/auxiliary/Random.h, networkit/cpp/auxiliary/SortedList.h, networkit/cpp/centrality/CMakeLists.txt, networkit/cpp/centrality/KadabraBetweenness.cpp, networkit/cpp/centrality/KadabraBetweenness.h, networkit/cpp/centrality/test/CentralityGTest.cpp, networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/Graph.h
Implementation of the Kadabra algorithm by Borassi et al.: KADABRA is an ADaptive Algorithm for Betweenness via Random Approximation (2016).
=> Kadabra algorithm for betweenness approximation

networkit/_NetworKit.pyx
Based on #157 by @michitux. Same reasons as in #267.
=> Implement equality of partitions

networkit/_NetworKit.pyx, networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/Graph.h, networkit/cpp/graph/test/GraphGTest.cpp
New parallel methods in the Graph class to get the maximum in/out degree.
=> Max in/out degree

networkit/_NetworKit.pyx, networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/Graph.h, networkit/cpp/graph/test/GraphGTest.cpp
New methods to compute in parallel the maximum weighted degree(in) of a weighted graph.
=> Maximum weighted degree

CMakeLists.txt, networkit.pc
A package config file will be created in the pkgconfig directory.
=> Support for pkg-config files

CMakeLists.txt, networkit.pc
pgk-config also stores the NetworKit version, fix in the networkit.pc file
=> pkg-config version

notebooks/User-Guide.ipynb
New Jupyter Notebook for the NetworKit User Guide.
=> NetworKit User Guide

networkit/cpp/coarsening/ParallelPartitionCoarsening.cpp, networkit/cpp/community/test/CommunityGTest.cpp, networkit/cpp/components/test/BiconnectedComponentsGTest.cpp, networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/Graph.h, networkit/cpp/graph/GraphBuilder.cpp, networkit/cpp/graph/GraphBuilder.h, networkit/cpp/randomization/CurveballImpl.cpp, networkit/cpp/randomization/CurveballImpl.h
This removes the `ouDeg` and `inDeg` vectors from `Graph`. Affected classes have also been updated.
=> Removed degree vectors from Graph

networkit/_NetworKit.pyx
=> Fixed discrepancy in ApproxBetweenness epsilon value

include/networkit/graph/Graph.hpp, networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/test/GraphGTest.cpp
This adds const iterators over the in/out neighbors of a node and the in/out-going edge weights.
=> Iterators over node neighbors and weights

.travis.yml
Specify compiler version in every travis build.
=> More detailed names for travis builds

docs/notebooks.rst, networkit/__init__.py
Fixed broken links to the UserGuide, removed links to missing notebooks.
=> Fix broken links

networkit/cpp/centrality/KadabraBetweenness.cpp
Using unique pointers to avoid memory leaks in KadabraBetweenness. 
Because this is not the first time that code with memory leaks is merged in NetworKit, I'd suggest to add a travis build with memory sanitizers. The same build could also include address sanitizers, which are very helpful to detect memory errors that are not detected by simply selecting the `Debug` build type. What do you think about this?
=> Fixed memory leaks in KadabraBetweenness

.travis.yml, CMakeLists.txt
This adds a new travis build that uses address, leak, and undefined sanitizers.
=> Travis build with sanitizers

.travis.yml
Fix travis build with osx 10.13 and Apple Clang
=> Fix travis Apple build

.travis.yml, CMakeLists.txt, README.md
Support for coverage using coveralls.
=> Support coverage

networkit/cpp/io/GMLGraphReader.cpp, networkit/cpp/io/METISParser.cpp
Fix warnings generated by catching exceptions by value.
=> Catch exceptions by reference

include/networkit/components/BiconnectedComponents.hpp, include/networkit/graph/Graph.hpp, networkit/cpp/components/BiconnectedComponents.cpp, networkit/cpp/components/test/BiconnectedComponentsGTest.cpp, networkit/test/test_algorithms.py
This PR fixes a performance issue of `BiconnectedComponents` raised in #398.
=> Fix performance issue in BiconnectedComponents

networkit/_NetworKit.pyx, notebooks/Community.ipynb
This PR adds a new jupyter-notebook for the `community` module. I made minor changes to the documentation too.
=> Jupyter-notebook for the community module

networkit/_NetworKit.pyx, notebooks/Generators.ipynb
This PR adds a new jupyter-notebook for the `generators` module. I made minor changes to the documentation too.
=> Jupyter-notebook for the generators module

networkit/_NetworKit.pyx, notebooks/Sparsification.ipynb
This PR adds a new jupyter-notebook for the `sparsification` module. I made minor changes to the documentation too.
=> Jupyter-notebook for the sparsification module

include/networkit/flow/EdmondsKarp.hpp, include/networkit/geometric/HyperbolicSpace.hpp, include/networkit/geometric/Point2DWithIndex.hpp, include/networkit/global/ClusteringCoefficient.hpp, include/networkit/layout/LayoutAlgorithm.hpp, include/networkit/matching/LocalMaxMatcher.hpp, include/networkit/matching/Matcher.hpp, include/networkit/matching/Matching.hpp, include/networkit/matching/PathGrowingMatcher.hpp, networkit/cpp/flow/EdmondsKarp.cpp, networkit/cpp/geometric/HyperbolicSpace.cpp, networkit/cpp/matching/LocalMaxMatcher.cpp, networkit/cpp/matching/Matcher.cpp, networkit/cpp/matching/Matching.cpp, networkit/cpp/matching/PathGrowingMatcher.cpp
This PR brings some improvements to the C++ code of the aforementioned modules.
=> Refactor flow, geometric, global, layout matching modules

include/networkit/viz/GraphLayoutAlgorithm.hpp, include/networkit/viz/MaxentStress.hpp, include/networkit/viz/Octree.hpp, include/networkit/viz/PivotMDS.hpp, include/networkit/viz/Point.hpp, include/networkit/viz/PostscriptWriter.hpp, networkit/cpp/viz/MaxentStress.cpp, networkit/cpp/viz/PivotMDS.cpp, networkit/cpp/viz/test/OctreeGTest.cpp
This PR brings some improvements to the C++ code of the viz module.
=> Refactor viz module

.travis.yml
This PR fixes the warnings that are thrown by travis in the .travis.yml file.
=> Fix travis warnings

include/networkit/randomization/Curveball.hpp, include/networkit/randomization/CurveballGlobalTradeGenerator.hpp, include/networkit/randomization/CurveballUniformTradeGenerator.hpp, include/networkit/randomization/DegreePreservingShuffle.hpp, include/networkit/randomization/GlobalCurveball.hpp, include/networkit/randomization/GlobalTradeSequence.hpp, networkit/cpp/randomization/Curveball.cpp, networkit/cpp/randomization/CurveballImpl.cpp, networkit/cpp/randomization/CurveballImpl.hpp, networkit/cpp/randomization/CurveballUniformTradeGenerator.cpp, networkit/cpp/randomization/DegreePreservingShuffle.cpp, networkit/cpp/randomization/GlobalCurveball.cpp
This PR brings some improvements to the C++ code of the randomisation module.
=> Refactor randomization module

CMakeLists.txt
=> Install ttmath-header

include/networkit/graph/Graph.hpp, networkit/GEXFIO.py, networkit/GraphMLIO.py, networkit/_NetworKit.pyx, networkit/algebraic.py, networkit/centrality.py, networkit/coloring.py, networkit/cpp/graph/test/GraphGTest.cpp, networkit/gephi/streaming.py, networkit/nxadapter.py, networkit/partitioning.py, networkit/sparsification.py, networkit/test/test_algorithms.py, networkit/test/test_community.py, networkit/test/test_graph.py, networkit/test/test_graphio.py, networkit/test/test_randomization.py, networkit/viztasks.py, networkit/workflows.py, notebooks/GraphNotebook.ipynb, notebooks/User-Guide.ipynb, scripts/DynamicBetweennessExperiments.py, scripts/DynamicBetweennessExperiments_fixed_batch.py, scripts/DynamicBetweennessExperiments_weighted.py, scripts/SpanningApprox.py
This PR brings new iterators for the nodes and the edges of a graph.
=> Graph iterators

include/networkit/generators/WattsStrogatzGenerator.hpp, networkit/cpp/generators/WattsStrogatzGenerator.cpp, networkit/cpp/generators/test/GeneratorsGTest.cpp, networkit/test/test_generators.py
The previous implementation ended up in an infinite look when certain parameters were passed to the generator (see issue #505 ). This PR changes that and adds C++ and Python tests.
=> Fix Watts-Strogatz generator

include/networkit/centrality/PageRank.hpp, networkit/_NetworKit.pyx, networkit/centrality.py, networkit/cpp/centrality/PageRank.cpp, networkit/cpp/centrality/test/CentralityGTest.cpp, networkit/test/test_algorithms.py, notebooks/Centrality.ipynb
This PR brings two new features to PageRank:
- Possibility to set the maximum number of iterations of the algorithm
- Possibility to choose between the L1 and the L2 norms as stopping criterion of the algorithm
=> Refactor: PageRank

include/networkit/distance/AlgebraicDistance.hpp, networkit/cpp/distance/AlgebraicDistance.cpp, networkit/cpp/viz/MaxentStress.cpp, networkit/cpp/viz/PivotMDS.cpp
Fix implicit integer to float conversion warnings.
=> Fix -Wimplicit-int-float-conversion

include/networkit/auxiliary/SetIntersector.hpp, networkit/cpp/io/MemoryMappedFile.cpp
This fixes compilation with GCC 10.1.0.
=> Add missing standard library includes

.travis.yml, docs/DevGuide.rst
- The documentation build is now deployed against the master branch.
- The DevGuide is updated according to the new development branch.
=> Update .travis.yml and DevGuide to new development branch

README.md
Updates installation documentation for brew, conda and spack.
=> Update readme: package manager documentation (brew, conda, spack)

include/networkit/generators/ErdosRenyiEnumerator.hpp, networkit/cpp/community/AdjustedRandMeasure.cpp, networkit/cpp/community/CoverHubDominance.cpp, networkit/cpp/community/CutClustering.cpp, networkit/cpp/community/GraphStructuralRandMeasure.cpp, networkit/cpp/community/JaccardMeasure.cpp, networkit/cpp/community/NMIDistance.cpp, networkit/cpp/community/NodeStructuralRandMeasure.cpp, networkit/cpp/community/PartitionHubDominance.cpp, networkit/cpp/community/SampledGraphStructuralRandMeasure.cpp, networkit/cpp/community/SampledNodeStructuralRandMeasure.cpp, networkit/cpp/distance/AffectedNodes.cpp, networkit/cpp/distance/HopPlotApproximation.cpp, networkit/cpp/distance/JaccardDistance.cpp, networkit/cpp/edgescores/EdgeScoreLinearizer.cpp, networkit/cpp/edgescores/PrefixJaccardScore.cpp, networkit/cpp/generators/MocnikGenerator.cpp, networkit/cpp/generators/PowerlawDegreeSequence.cpp, networkit/cpp/generators/RmatGenerator.cpp
`cppcoreguideline-narrowing-conversion` fixes for the aforementioned modules.
=> Community, distance, edgescores, generators: cpp coreguideline narrowing conversion

docs/DevGuide.rst
Update the documentation on Cython development according to the new structure.
=> Update Cython section of developer guide

docs/DevGuide.rst
- Update links to mailing list
- Update style guide documentation (`networkit-format`, `clang-tidy`, changes made in previous PRs)
=> Update style guide documentation

CMakeLists.txt
- This is neccessary for older cmake versions
=> Fixes build order for documentation website

include/networkit/distance/APSP.hpp, include/networkit/distance/SPSP.hpp, networkit/cpp/distance/CMakeLists.txt, networkit/cpp/distance/SPSP.cpp, networkit/cpp/distance/test/DistanceGTest.cpp, networkit/distance.pyx, networkit/test/test_algorithms.py, notebooks/Distance.ipynb
This PR implements a `SPSP` algorithm (Some-Pairs Shortest-Paths, but suggestions for better names are welcome) as suggested in #544. The algorithm computes shortest-path distances from a set of user-defined source vertices to all the other vertices in the graph.
As suggested by @fabratu, the implementation has been done in another class instead of within `APSP`.
=> Feature SPSP

include/networkit/graph/GraphTools.hpp, networkit/cpp/graph/GraphTools.cpp, networkit/cpp/graph/test/GraphToolsGTest.cpp, networkit/graphtools.pyx, networkit/test/test_graphtools.py
This PR would add the following:
- Adds support for volume of directed graphs. Implementation following initial thoughts from https://github.com/networkit/networkit/pull/558#issuecomment-632704544
- Adds support for volume of subgraphs. Implementation following initial thoughts from https://github.com/networkit/networkit/pull/558#discussion_r430247248
- Adds unit-tests and python-interface https://github.com/networkit/networkit/pull/558#pullrequestreview-421021520
=> Adds subgraph volume-computation, support for directed graphs

docs/conf.py, extrafiles/sphinx-style/_static/style.css, extrafiles/sphinx-style/_templates/navbar.html
This is in order to align with website-build.
=> Update navbar for documentation build

CHANGES.md, networkit/__init__.py, version.py
- Updated version in `__init.py__` and `version.py`
- Added API-changes in 8.0
=> Version 8.0: Readme + version update

networkit/cpp/io/METISParser.cpp, networkit/cpp/io/MatrixMarketReader.cpp
Fixes additional warnings spotted by clang-analyzer
=> Fix clang-analyzer warnings

extlibs/ttmath/ttmath/ttmathobjects.hpp, include/networkit/geometric/Point2DWithIndex.hpp, include/networkit/numerics/LAMG/LevelHierarchy.hpp, include/networkit/numerics/LAMG/MultiLevelSetup.hpp
Fixes new gcc C++17/20 warnings.
=> Fix minor warnings from GCC in C++17/20 mode

include/networkit/flow/EdmondsKarp.hpp, networkit/cpp/flow/EdmondsKarp.cpp, networkit/cpp/flow/test/EdmondsKarpGTest.cpp, networkit/flow.pyx
`EdmondsKarp` should inherit from `Algorithm`.
=> Edmonds Karp: Refactor to inherit from algorithm

include/networkit/auxiliary/BucketPQ.hpp, include/networkit/auxiliary/PrioQueue.hpp, networkit/cpp/centrality/GroupCloseness.cpp, networkit/cpp/centrality/KPathCentrality.cpp, networkit/cpp/centrality/KadabraBetweenness.cpp, networkit/cpp/distance/AffectedNodes.cpp, networkit/cpp/generators/PowerlawDegreeSequence.cpp, networkit/cpp/generators/RegularRingLatticeGenerator.cpp, networkit/cpp/generators/WattsStrogatzGenerator.cpp, networkit/cpp/io/MatrixMarketReader.cpp
Fix clang-analyzer warnings and other minor issues.
=> Fix warnings

.github/workflows/ci.yml, .github/workflows/scripts/full.sh, setup.py
This is used in https://github.com/Homebrew/homebrew-core/pull/67184
=> setup.py: add --external-tlx option

networkit/GraphMLIO.py
=> Remove setName() usage from GraphMLSAX

include/networkit/graph/GraphTools.hpp, networkit/cpp/centrality/ApproxCloseness.cpp, networkit/cpp/graph/GraphTools.cpp, networkit/cpp/graph/test/GraphToolsGTest.cpp, networkit/cpp/viz/PivotMDS.cpp
=> Fix infinite loop in PivotMDS and approxCloseness when sample size is too large.

include/networkit/matching/Matching.hpp, networkit/matching.pyx
Updating the python documentation. Also includes a small fix for the c++ documentation.
=> Updating the documentation for matching.

include/networkit/centrality/DegreeCentrality.hpp, networkit/centrality.pyx, networkit/cpp/centrality/DegreeCentrality.cpp, networkit/cpp/centrality/test/CentralityGTest.cpp, networkit/test/test_centrality.py
The documentation now has also been updated to reflect its actual running time.
Closes #745
=> Bug Fix: ignoreSelfLoops property of DegreeCentrality now actually ignores self loops

docs/python_api/graphtools.rst, docs/python_api/modules.rst
=> Add missing graphtools module to docs

include/networkit/auxiliary/VectorComparator.hpp, include/networkit/centrality/GroupHarmonicCloseness.hpp, networkit/centrality.pyx, networkit/cpp/centrality/CMakeLists.txt, networkit/cpp/centrality/GroupHarmonicCloseness.cpp, networkit/cpp/centrality/test/CentralityGTest.cpp, networkit/test/test_algorithms.py, notebooks/GroupCentrality.ipynb
This PR brings a new greedy algorithm for group-harmonic maximization. The algorithm is described in the paper by E. Angriman, R. Becker, G. D'Angelo, H. Gilbert, A. van der Grinten, H. Meyerhenke: "Group-Harmonic and Group-Closeness Maximization -- Approximation and Engineering", accepted at ALENEX 2021, arXiv version [here](https://arxiv.org/abs/2010.15435).
=> New algorithm: group harmonic closeness

include/networkit/numerics/LAMG/Lamg.hpp
Fix `-Werror=maybe-uninitialized` raised by gcc 11.1.0.
=> Warning and doc fixes in Lamg

include/networkit/algebraic/algorithms/AlgebraicBFS.hpp, include/networkit/algebraic/algorithms/AlgebraicBellmanFord.hpp, include/networkit/algebraic/algorithms/AlgebraicMatchingCoarsening.hpp, include/networkit/algebraic/algorithms/AlgebraicPageRank.hpp, include/networkit/algebraic/algorithms/AlgebraicSpanningEdgeCentrality.hpp, include/networkit/algebraic/algorithms/AlgebraicTriangleCounting.hpp
As discussed, we should slowly adapt non-compliant files to our coding style. The idea is to format a few files per PR, none of which is being modified by other PRs. This PR formats files in `algebraic/algorithms`
=> clang-format: algebraic/algorithms

include/networkit/centrality/Closeness.hpp, include/networkit/centrality/GedWalk.hpp, include/networkit/distance/AStarGeneral.hpp, include/networkit/distance/IncompleteDijkstra.hpp, networkit/cpp/centrality/Closeness.cpp, networkit/cpp/centrality/GroupClosenessGrowShrinkImpl.cpp, networkit/cpp/centrality/GroupClosenessGrowShrinkImpl.hpp, networkit/cpp/distance/IncompleteDijkstra.cpp
This PR replaces the last instances of custom vector-based comparators with the ones defined in `Aux`.
=> Refactor: use VectorComparator

include/networkit/algebraic/DenseMatrix.hpp, include/networkit/algebraic/DynamicMatrix.hpp, include/networkit/algebraic/GraphBLAS.hpp, include/networkit/algebraic/MatrixTools.hpp, include/networkit/algebraic/Semirings.hpp, include/networkit/algebraic/SparseAccumulator.hpp
Continuation of #803: clang-format headers of `algebraic`
=> clang-format headers of algebraic

include/networkit/auxiliary/BloomFilter.hpp, include/networkit/auxiliary/BucketPQ.hpp, include/networkit/auxiliary/Enforce.hpp, include/networkit/auxiliary/FunctionTraits.hpp, include/networkit/auxiliary/Log.hpp, include/networkit/auxiliary/MissingMath.hpp, include/networkit/auxiliary/Multiprecision.hpp, include/networkit/auxiliary/NumberParsing.hpp, include/networkit/auxiliary/NumericTools.hpp, include/networkit/auxiliary/Parallel.hpp, include/networkit/auxiliary/Parallelism.hpp, include/networkit/auxiliary/PrioQueue.hpp, include/networkit/auxiliary/Random.hpp, include/networkit/auxiliary/SetIntersector.hpp, include/networkit/auxiliary/SignalHandling.hpp, include/networkit/auxiliary/SortedList.hpp, include/networkit/auxiliary/StringBuilder.hpp, include/networkit/auxiliary/StringTools.hpp, include/networkit/auxiliary/TemplateUtils.hpp, include/networkit/auxiliary/Timer.hpp
=> clang-format headers of auxiliary

include/networkit/Globals.hpp, include/networkit/viz/GraphLayoutAlgorithm.hpp, include/networkit/viz/MaxentStress.hpp, include/networkit/viz/Octree.hpp, include/networkit/viz/PivotMDS.hpp
=> clang-format Global and headers of viz

.github/workflows/ci.yml, .github/workflows/scripts/clang_tidy.sh, include/networkit/viz/Octree.hpp, networkit/cpp/independentset/Luby.cpp, networkit/cpp/io/RasterReader.cpp
This also includes a few warning fixes.
=> Update CI to clang 13

include/networkit/base/DynAlgorithm.hpp, include/networkit/clique/MaximalCliques.hpp, include/networkit/coarsening/ClusteringProjector.hpp, include/networkit/coarsening/GraphCoarsening.hpp, include/networkit/coarsening/MatchingCoarsening.hpp, include/networkit/components/BiconnectedComponents.hpp, include/networkit/components/DynConnectedComponents.hpp, include/networkit/components/DynWeaklyConnectedComponents.hpp, include/networkit/components/ParallelConnectedComponents.hpp, include/networkit/components/RandomSpanningForest.hpp
=> clang-format headers of base, clique, coarsening, and components

notebooks/Centrality.ipynb
Here the link to arXive https://arxiv.org/abs/1409.0035
=> Fixed author in citation of `ApproxCloseness`

include/networkit/graph/Graph.hpp, include/networkit/io/NetworkitBinaryGraph.hpp, include/networkit/io/NetworkitBinaryReader.hpp, include/networkit/io/NetworkitBinaryWriter.hpp, networkit/cpp/graph/Graph.cpp, networkit/cpp/io/NetworkitBinaryGraph.md, networkit/cpp/io/NetworkitBinaryReader.cpp, networkit/cpp/io/NetworkitBinaryWriter.cpp, networkit/cpp/io/test/IOGTest.cpp, networkit/graph.pxd, networkit/graph.pyx, networkit/graphio.pyx, networkit/test/test_graph.py
=> NetworkitBinaryGraph is now able to save Edge Indices

include/networkit/community/ParallelLeiden.hpp, networkit/community.pyx, networkit/cpp/community/CMakeLists.txt, networkit/cpp/community/ParallelLeiden.cpp, networkit/cpp/community/test/CommunityGTest.cpp, networkit/test/test_algorithms.py
I implemented a parallel version of the Leiden algorithm for my [bachelor thesis](https://zenodo.org/record/5564953)
This code is basically a stripped version of my [own repository](https://github.com/CxVercility/ParallelLeiden) (since it was cluttered with benchmark code etc) which also contains sequential versions and a second parallel version for both local moving and refinement, though the alternative parallel versions haven't been tested thoroughly so I wouldnt include them.
This was my first C++ project ever and I didnt really put a lot of effort into making the code look nice so Im not expecting this to go through asit is. Feel free to change or add anything you like, if you want only minor changes done i'll be happy to do those as well. 
Greets.
=> Add Parallel Leiden Algorithm

include/networkit/dynamics/DGSStreamParser.hpp, include/networkit/dynamics/DGSWriter.hpp, include/networkit/dynamics/GraphDifference.hpp, include/networkit/dynamics/GraphEvent.hpp, include/networkit/dynamics/GraphEventHandler.hpp, include/networkit/dynamics/GraphEventProxy.hpp, include/networkit/dynamics/GraphUpdater.hpp, include/networkit/edgescores/EdgeScoreAsWeight.hpp, include/networkit/edgescores/EdgeScoreBlender.hpp, include/networkit/edgescores/EdgeScoreLinearizer.hpp, include/networkit/edgescores/EdgeScoreNormalizer.hpp, include/networkit/edgescores/GeometricMeanScore.hpp, include/networkit/edgescores/PrefixJaccardScore.hpp, include/networkit/flow/EdmondsKarp.hpp, include/networkit/geometric/HyperbolicSpace.hpp, include/networkit/geometric/Point2DWithIndex.hpp, include/networkit/global/ClusteringCoefficient.hpp, include/networkit/global/GlobalClusteringCoefficient.hpp, include/networkit/graph/GraphBuilder.hpp, include/networkit/graph/KruskalMSF.hpp, include/networkit/graph/RandomMaximumSpanningForest.hpp, include/networkit/graph/Sampling.hpp, include/networkit/graph/SpanningForest.hpp, include/networkit/graph/UnionMaximumSpanningForest.hpp, include/networkit/graph/test/GraphBuilderBenchmark.hpp
This is a continuation of #803. All changes are automatically generated and do not create conflicts with existing PRs.
=> clang-format headers of dynamics, edgescores, flow, geometric, global, graph

include/networkit/centrality/ApproxSpanningEdge.hpp, networkit/centrality.pyx
Hello,
I believe I spotted a small typo in the documentation.
This isn't much but I thought it would be worth sharing.
Have a good day.
=> Fix a typo

include/networkit/linkprediction/NeighborhoodDistanceIndex.hpp
I broke the formatting of a file while resolving a conflict. This PR re-formats the affected file.
=> Fix unformatted file

networkit/cpp/matching/LocalMaxMatcher.cpp, networkit/cpp/matching/Matcher.cpp
- Remove redundant `MyEdge` struct from `LocalMaxMatcher` (we can use `WeightedEdge` already defined in `Graph`)
- Ensure that `run` is called before `Matcher::getMatching`
- Add missing `hasRun = true` in `LocalMaxMatcher`
=> Refactor: Matching

networkit/cpp/distance/NeighborhoodFunction.cpp, networkit/cpp/distance/NeighborhoodFunctionApproximation.cpp, networkit/cpp/distance/Volume.cpp
As in #869: use STL algorithms where applicable.
=> Refactor: use STL algorithms (2)

docs/python_api/modules.rst, docs/python_api/reachability.rst, docs/python_api/sampling.rst, docs/python_api/scd.rst, docs/python_api/simulation.rst, docs/python_api/stats.rst, docs/python_api/stopwatch.rst, docs/python_api/traversal.rst, docs/python_api/workflows.rst, include/networkit/simulation/EpidemicSimulationSEIR.hpp, networkit/randomization.pyx, networkit/reachability.pyx, networkit/sampling.py, networkit/scd.pyx, networkit/simulation.pyx, networkit/sparsification.pyx, networkit/stats.pyx, networkit/stopwatch.py, networkit/structures.pyx, networkit/traversal.pyx, networkit/viz.pyx, networkit/viztasks.py, networkit/workflows.py
=> Documentation fix for Python-modules: randomization to workflows

include/networkit/auxiliary/Log.hpp, include/networkit/auxiliary/Random.hpp, include/networkit/auxiliary/SignalHandling.hpp, include/networkit/centrality/Centrality.hpp, include/networkit/distance/AllSimplePaths.hpp, include/networkit/graph/GraphBuilder.hpp, include/networkit/graph/GraphTools.hpp, include/networkit/independentset/IndependentSetFinder.hpp, include/networkit/scd/GCE.hpp, include/networkit/scd/PageRankNibble.hpp, networkit/cpp/auxiliary/Log.cpp, networkit/cpp/auxiliary/Random.cpp, networkit/cpp/auxiliary/SignalHandling.cpp, networkit/cpp/graph/GraphTools.cpp, networkit/cpp/independentset/IndependentSetFinder.cpp, networkit/cpp/scd/GCE.cpp, networkit/cpp/scd/PageRankNibble.cpp
Remove unused code and code deprecated in NetworKit `8.1`.
=> Remove deprecated code

include/networkit/algebraic/MatrixTools.hpp, include/networkit/matching/Matcher.hpp, include/networkit/matching/Matching.hpp, include/networkit/matching/PathGrowingMatcher.hpp, include/networkit/numerics/ConjugateGradient.hpp, include/networkit/numerics/GaussSeidelRelaxation.hpp, include/networkit/numerics/LAMG/LAMGSettings.hpp, include/networkit/numerics/LAMG/Lamg.hpp, include/networkit/numerics/LAMG/Level/EliminationStage.hpp, include/networkit/numerics/LAMG/Level/Level.hpp, include/networkit/numerics/LAMG/Level/LevelAggregation.hpp, include/networkit/numerics/LAMG/Level/LevelElimination.hpp, include/networkit/numerics/LAMG/Level/LevelFinest.hpp, include/networkit/numerics/LAMG/LevelHierarchy.hpp, include/networkit/numerics/LAMG/MultiLevelSetup.hpp, include/networkit/numerics/LAMG/SolverLamg.hpp, include/networkit/numerics/LinearSolver.hpp, include/networkit/numerics/Preconditioner/DiagonalPreconditioner.hpp, include/networkit/numerics/Preconditioner/IdentityPreconditioner.hpp, include/networkit/numerics/Smoother.hpp
This is a continuation of #803. Changes do not create conflicts with existing PRs and are automatically generated with the exception of:
- move a few comments on a new line for better readability
- add missing `#include`; this was necessary because changing the order of some `#include`s broke the build
=> Format headers of matching and numerics

networkit/cpp/centrality/DynApproxBetweenness.cpp, networkit/cpp/centrality/test/DynBetweennessGTest.cpp
Also fixes a bug when calculating the vertex diameter.
=> Add directed and weighted cases to DynBetweeness tests

include/networkit/generators/BarabasiAlbertGenerator.hpp, networkit/cpp/generators/BarabasiAlbertGenerator.cpp, networkit/cpp/generators/test/GeneratorsGTest.cpp
=> Remove quadratic Barabasi Albert Generator

docs/python_api/viz.rst, docs/python_api/vizbridges.rst, networkit/viz.pyx
This PR also adds the previously missing `vizbridges`-module.
=> Python doc: Fix missing/wrong strings for viz-module

networkit/cpp/distance/NeighborhoodFunctionHeuristic.cpp
Use node iterator to simplify code that creates a vector of nodes sorted by their degree.
=> Use node iterator to sort nodes by degree

networkit/cpp/GlobalState.cpp, networkit/cpp/Unittests-X.cpp, networkit/cpp/algebraic/DenseMatrix.cpp, networkit/cpp/algebraic/DynamicMatrix.cpp, networkit/cpp/algebraic/Vector.cpp, networkit/cpp/algebraic/test/AlgebraicBFSGTest.cpp, networkit/cpp/algebraic/test/AlgebraicBellmanFordGTest.cpp, networkit/cpp/algebraic/test/AlgebraicMatchingCoarseningGTest.cpp, networkit/cpp/algebraic/test/AlgebraicPageRankGTest.cpp, networkit/cpp/algebraic/test/AlgebraicSpanningEdgeCentralityGTest.cpp, networkit/cpp/algebraic/test/AlgebraicTriangleCountingGTest.cpp, networkit/cpp/algebraic/test/GraphBLASGTest.cpp, networkit/cpp/algebraic/test/MatricesGTest.cpp, networkit/cpp/algebraic/test/VectorGTest.cpp, networkit/cpp/clique/MaximalCliques.cpp, networkit/cpp/clique/test/CliqueGTest.cpp, networkit/cpp/clique/test/MaximalCliquesGTest.cpp, networkit/cpp/networkit.cpp
=> clang-format 'algebraic' and 'clique' sources

networkit/cpp/distance/DynDijkstra.cpp, networkit/cpp/distance/test/DynSSSPGTest.cpp
Fix a bug that occurred when a previously visited node was reached with a lower updated distance than their current distance, which caused sometimes paths to be ignored.
=> Fix Bug in DynDijstrika related to previously visited nodes.

include/networkit/community/GraphClusteringTools.hpp, networkit/community.pyx, networkit/cpp/community/GraphClusteringTools.cpp, networkit/partitioning.py
This PR also adds a second version of `community.getImbalance` for both C++ and Python. Not sure, whether the former definition in the community module should be kept.
=> Deprecate Python module 'partitioning'. Move functionality to 'community'.

networkit/__init__.py, version.py
Also updated the package classifier and credits.
=> Raise version to 10.0. 

networkit/cpp/coarsening/ClusteringProjector.cpp, networkit/cpp/coarsening/GraphCoarsening.cpp, networkit/cpp/coarsening/MatchingCoarsening.cpp, networkit/cpp/coarsening/test/CoarseningBenchmark.cpp, networkit/cpp/components/BiconnectedComponents.cpp, networkit/cpp/components/ParallelConnectedComponents.cpp, networkit/cpp/components/RandomSpanningForest.cpp, networkit/cpp/components/test/BiconnectedComponentsGTest.cpp, networkit/cpp/components/test/ConnectedComponentsGTest.cpp, networkit/cpp/correlation/Assortativity.cpp, networkit/cpp/dynamics/DGSStreamParser.cpp, networkit/cpp/dynamics/DGSWriter.cpp, networkit/cpp/dynamics/GraphDifference.cpp, networkit/cpp/dynamics/GraphEvent.cpp, networkit/cpp/dynamics/GraphEventProxy.cpp, networkit/cpp/dynamics/GraphUpdater.cpp, networkit/cpp/dynamics/test/DynamicsGTest.cpp
This is a continuation of #803.
=> clang-format sources of coarsening, components, correlation, and dynamics

networkit/cpp/edgescores/ChibaNishizekiQuadrangleEdgeScore.cpp, networkit/cpp/edgescores/ChibaNishizekiTriangleEdgeScore.cpp, networkit/cpp/edgescores/EdgeScore.cpp, networkit/cpp/edgescores/EdgeScoreAsWeight.cpp, networkit/cpp/edgescores/EdgeScoreBlender.cpp, networkit/cpp/edgescores/EdgeScoreLinearizer.cpp, networkit/cpp/edgescores/EdgeScoreNormalizer.cpp, networkit/cpp/edgescores/GeometricMeanScore.cpp, networkit/cpp/edgescores/PrefixJaccardScore.cpp, networkit/cpp/edgescores/TriangleEdgeScore.cpp, networkit/cpp/edgescores/test/ChibaNishizekiQuadrangleEdgeScoreGTest.cpp, networkit/cpp/edgescores/test/ChibaNishizekiTriangleEdgeScoreGTest.cpp, networkit/cpp/flow/EdmondsKarp.cpp, networkit/cpp/flow/test/EdmondsKarpGTest.cpp
=> clang-format sources of edgescores, embedding, and flow

networkit/cpp/graph/GraphBuilder.cpp, networkit/cpp/graph/KruskalMSF.cpp, networkit/cpp/graph/RandomMaximumSpanningForest.cpp, networkit/cpp/graph/SpanningForest.cpp, networkit/cpp/graph/UnionMaximumSpanningForest.cpp, networkit/cpp/graph/test/Graph2Benchmark.cpp, networkit/cpp/graph/test/GraphBenchmark.cpp, networkit/cpp/graph/test/GraphBuilderAutoCompleteGTest.cpp, networkit/cpp/graph/test/GraphBuilderBenchmark.cpp, networkit/cpp/graph/test/GraphGTest.cpp, networkit/cpp/graph/test/SpanningGTest.cpp, networkit/cpp/independentset/IndependentSetFinder.cpp, networkit/cpp/independentset/Luby.cpp, networkit/cpp/independentset/test/IndependentSetGTest.cpp
=> Clang format sources of graph and independentset

networkit/cpp/linkprediction/AdamicAdarIndex.cpp, networkit/cpp/linkprediction/AdjustedRandIndex.cpp, networkit/cpp/linkprediction/AlgebraicDistanceIndex.cpp, networkit/cpp/linkprediction/EvaluationMetric.cpp, networkit/cpp/linkprediction/KatzIndex.cpp, networkit/cpp/linkprediction/LinkPredictor.cpp, networkit/cpp/linkprediction/LinkThresholder.cpp, networkit/cpp/linkprediction/MissingLinksFinder.cpp, networkit/cpp/linkprediction/NeighborhoodUtility.cpp, networkit/cpp/linkprediction/PrecisionRecallMetric.cpp, networkit/cpp/linkprediction/PredictionsSorter.cpp, networkit/cpp/linkprediction/ROCMetric.cpp, networkit/cpp/linkprediction/RandomLinkSampler.cpp, networkit/cpp/linkprediction/ResourceAllocationIndex.cpp, networkit/cpp/linkprediction/SameCommunityIndex.cpp, networkit/cpp/linkprediction/test/DistMeasuresGTest.cpp, networkit/cpp/linkprediction/test/LinkPredictionGTest.cpp, networkit/cpp/matching/LocalMaxMatcher.cpp, networkit/cpp/matching/Matcher.cpp, networkit/cpp/matching/Matching.cpp, networkit/cpp/matching/PathGrowingMatcher.cpp, networkit/cpp/matching/test/MatcherGTest.cpp, networkit/cpp/numerics/test/GaussSeidelRelaxationGTest.cpp, networkit/cpp/numerics/test/LAMGGTest.cpp
=> Clang format sources of linkprediction, matching, and numerics

networkit/cpp/overlap/HashingOverlapper.cpp, networkit/cpp/overlap/test/OverlapGTest.cpp, networkit/cpp/randomization/GlobalTradeSequence.hpp, networkit/cpp/simulation/EpidemicSimulationSEIR.cpp, networkit/cpp/sparsification/ChanceCorrectedTriangleScore.cpp, networkit/cpp/sparsification/ForestFireScore.cpp, networkit/cpp/sparsification/LocalDegreeScore.cpp, networkit/cpp/sparsification/LocalSimilarityScore.cpp, networkit/cpp/sparsification/MultiscaleScore.cpp, networkit/cpp/sparsification/RandomEdgeScore.cpp, networkit/cpp/sparsification/RandomNodeEdgeScore.cpp, networkit/cpp/sparsification/SCANStructuralSimilarityScore.cpp, networkit/cpp/sparsification/SimmelianOverlapScore.cpp, networkit/cpp/sparsification/SimmelianScore.cpp, networkit/cpp/sparsification/Sparsifiers.cpp, networkit/cpp/sparsification/test/LocalDegreeGTest.cpp, networkit/cpp/sparsification/test/LocalSimilarityGTest.cpp, networkit/cpp/sparsification/test/MultiscaleBackboneGTest.cpp, networkit/cpp/sparsification/test/SimmelianBackboneGTest.cpp, networkit/cpp/sparsification/test/SparsificationBenchmark.cpp
=> clang-format sources of overlap, randomization, simulation, and sparsification

networkit/cpp/structures/Cover.cpp, networkit/cpp/structures/UnionFind.cpp, networkit/cpp/structures/test/CoverGTest.cpp, networkit/cpp/structures/test/PartitionGTest.cpp, networkit/cpp/structures/test/UnionFindGTest.cpp, networkit/cpp/viz/MaxentStress.cpp, networkit/cpp/viz/PivotMDS.cpp, networkit/cpp/viz/test/MaxentStressGTest.cpp, networkit/cpp/viz/test/OctreeGTest.cpp, networkit/cpp/viz/test/VizGTest.cpp
This completes #803, all cpp files in NetworKit are now clang-formatted
=> Clang-format sources of structures and viz

.github/workflows/build_wheels.yml, .github/workflows/ci.yml
I've created a first draft for a python 3.11 support PR
closes #999
=> Add support for python 3.11

networkit/cpp/graph/KruskalMSF.cpp, networkit/cpp/graph/test/SpanningGTest.cpp
=> SpanningTree: bugfix suggestion and tests

networkit/cpp/community/PLP.cpp
This PR reverts the loop to the version before #983. The other changes (variable initialization) remain.
With the changes from #983 PLP the debug build on Windows does time-out due to infinite loops. Sometimes this also leads to bad allocation errors, likely due to remains of loop datastructure. Note that this cannot be reproduced locally (with the same compiler/environment). If we track the output on CI, we see that different nodes exchange their labels in each run. Since the testing instances are small (n=1k), one update is enough to keep the main loop alive.
Log from CI:
```
2022-11-30T11:58:36.6150800Z 1: ITERATION: 435
2022-11-30T11:58:36.6150978Z 1: Label: 788
2022-11-30T11:58:36.6151267Z 1: Label: 981
2022-11-30T11:58:36.6151590Z 1: Label: 788
2022-11-30T11:58:36.6151831Z 1: …
```
=> PLP: Revert loop to previous version

.github/workflows/scripts/documentation.sh, notebooks/User-Guide.ipynb
Current errors in the web based display of the User Guide are shown here: https://networkit.github.io/dev-docs/notebooks/User-Guide.html#Degree-Distribution
=> Documentation: Fixes rendering and typos of "degree distribution" paragraph from User-Guide notebook

include/networkit/flow/EdmondsKarp.hpp, networkit/cpp/flow/EdmondsKarp.cpp, networkit/cpp/flow/test/EdmondsKarpGTest.cpp
=> Fix EdmondsKarp max flow for directed and min cut source set for both directed/undirected graphs 

networkit/community.pyx
removes reference from vector, fixes the output function
=> community.pyx: fixes getValues function

networkit/test/test_distance.py
Remove commented-out code from `test_distance.py`.
=> Remove unused code in test_distance.py

networkit/cpp/community/test/CommunityGTest.cpp
- adds new function testCoverHubDominance to increase testing coverage
- also adds tests for getValues() in testCoverF1Similarity
=> CommunityGTest.cpp: adds testCoverHubDominance 

networkit/cpp/components/BiconnectedComponents.cpp, networkit/cpp/components/test/BiconnectedComponentsGTest.cpp
=> Fix #1063: BiconnectedComponents bug

include/networkit/graph/Graph.hpp, networkit/graph.pyx
regarding the missing documentation mentioned in #1058
=> Documentation: adds reminder for users in graphDegree functions

networkit/test/test_component.py
mainly to increase testing coverage
=> python tests: adds more tests into test_component.py

networkit/community.pyx
this PR adresses a link that did not work properly
=> docu: fix wikipedia link

networkit/cpp/algebraic/test/MatricesGTest.cpp, networkit/test/test_algebraic.py
this PR splits up #1062 into semantically linked parts
=> Unit testing: adds test_algebraic.py and more tests for MatricesGtest.cpp

networkit/community.pyx
Fix kCoreCommunityDetection. Previous implementation has typo and subgraphFromNodes method needs to be updated.
Issue: https://github.com/networkit/networkit/issues/1070#issuecomment-1604676495
=> Fix kCoreCommunityDetection

networkit/test/test_distance.py
this is #1077 renewed, because of problems. some of the comments remain to be adressed
=> python tests: improves test_distance.py

networkit/test/test_centrality.py
=> python tests: improves test_centrality

networkit/test/test_engineering.py, networkit/test/test_flow.py, networkit/test/test_generators.py
- test_flow should cover all existing functions
- generators is still in progress
- engineering is still in progress
=> python unit tests: adds more tests for flow, generators and engineering

networkit/community.pyx
this PR fixes issue #1100, the corresponding tests will be added in #1075
=> community.pyx: spectralPartitioner fix

networkit/test/test_clique.py, networkit/test/test_community.py
=> python unit tests: adds test_clique and adds functions in test_community

networkit/cpp/graph/test/AttributeTest.cpp, networkit/cpp/graph/test/GraphGTest.cpp, networkit/cpp/graph/test/GraphToolsGTest.cpp, networkit/cpp/graph/test/SpanningGTest.cpp
this PR mainly adds tests for cases that had not been tested before
=> gtests: increase graph related function coverage

networkit/cpp/components/RandomSpanningForest.cpp, networkit/cpp/components/test/ConnectedComponentsGTest.cpp
- also adjusts the algorithm, so that the spanning forest gets properly returned
=> gtests: adds randomSpanningForest test

networkit/cpp/algebraic/DenseMatrix.cpp, networkit/cpp/algebraic/test/MatricesGTest.cpp, networkit/cpp/algebraic/test/VectorGTest.cpp
also changes a tiny copy&paste error in DenseMatrix.cpp
=> gtests: adds algebraic tests

include/networkit/graph/KruskalMSF.hpp, networkit/cpp/graph/KruskalMSF.cpp, networkit/cpp/graph/test/SpanningGTest.cpp
=> Fix #1068: KruskalMST documentation implementation discrepancy

.github/workflows/scripts/core_sanitizers_coverage.sh, docs/notebooks.rst, include/networkit/graph/Graph.hpp, networkit/cpp/distance/HopPlotApproximation.cpp, networkit/graph.pxd, networkit/graph.pyx, networkit/plot.py, notebooks/Plot.ipynb
- This PR is supposed to adress #1098 and also fix the plot.py in general (plenty Plots fail)
- It also adds tests for all possible plot functions (not finished yet)
=> fix: plot.py, also adds corresponding jupyter notebook

include/networkit/graph/Graph.hpp, networkit/cpp/centrality/GroupDegree.cpp, networkit/cpp/graph/Graph.cpp, networkit/cpp/graph/test/AttributeGTest.cpp, networkit/cpp/graph/test/AttributeTest.cpp, networkit/cpp/graph/test/CMakeLists.txt, networkit/cpp/graph/test/GraphGTest.cpp, networkit/graph.pxd, networkit/graph.pyx, networkit/test/test_graph.py, notebooks/GraphNotebook.ipynb
attributes on edges:
* symmetric to attributes on nodes
* with edgeID or (node, node) indexing
* edges MUST be indexed
* C++: 
```
auto ea = g.edgeAttributes().attach<long>("long on edges");           
auto UV = [&](node u, node v){ return g.edgeId(u,v); };
auto e13 = UV(1,3);
ea[UV(1,3)] = 27L; // edgeid
ea(1,3) = 28L; // node pair per op()
std::cout<<ea[e13]<<"\n"; // 28
```
* Python: 
```
ea = G.attachEdgeAttribute('int on edges', int)
ea[0]=4 //edgid 0 
ea[0,1]=5 // edge 0->1
```
=> Introduce `EdgeAttributes` (C++, Python)

networkit/cpp/linkprediction/test/LinkPredictionGTest.cpp
updated version of PR #1128, because of some merging issues
=> gtests: adds linkprediction test

networkit/cpp/generators/test/ErdosRenyiEnumeratorGTest.cpp
adjusted the tests, because when called with many threads the assertions failed
=> fix ErdosRenyiEnumeratorGTest

include/networkit/centrality/ComplexPaths.hpp, networkit/centrality.pyx, networkit/cpp/centrality/CMakeLists.txt, networkit/cpp/centrality/ComplexPaths.cpp, networkit/cpp/centrality/test/CentralityGTest.cpp, networkit/test/test_centrality.py
complex paths as new centrality algorithm
tests are still missing
=> Complex paths

include/networkit/independentset/Luby.hpp, networkit/cpp/independentset/Luby.cpp, networkit/cpp/independentset/test/IndependentSetGTest.cpp
re-upload from #1126, also adressed the review comments
=> cpp: make lubys algorithm deterministic

networkit/cpp/distance/test/DistanceGTest.cpp
addressing #1168 and commenting test a little further
=> gtests: fix adamicAdarTest

networkit/generators.pyx, networkit/test/test_generators.py
Also adding a new test for unchecked Python code. Fixes issue #1195.
=> Fix PowerlawSequence generator (Python)

.github/workflows/ci.yml, .github/workflows/scripts/core_sanitizers_coverage.sh, .github/workflows/scripts/full.sh, networkit/test/test_vizbridges.py, networkit/vizbridges.py
Known problem: 2D with Plotly does not work yet. Needs investigation on how to fix this.
=> new feature: visualization supports edge coloring

notebooks/Dynamics.ipynb
This PR improves the dynamics notebook by clarifying some details and generally revising the text. Also changes code to camelCase and correct formatting.
=> improve dynamics notebook

include/networkit/generators/RmatGenerator.hpp, networkit/cpp/generators/RmatGenerator.cpp, networkit/cpp/generators/test/GeneratorsGTest.cpp
re-open #1164 from different fork
=> improves rmat generator + adds tests

include/networkit/graph/GraphBuilder.hpp, networkit/cpp/generators/ChungLuGenerator.cpp, networkit/cpp/generators/ClusteredRandomGraphGenerator.cpp, networkit/cpp/generators/ErdosRenyiGenerator.cpp, networkit/cpp/generators/HyperbolicGenerator.cpp, networkit/cpp/graph/GraphBuilder.cpp, networkit/cpp/graph/test/GraphBuilderAutoCompleteGTest.cpp, networkit/cpp/io/ThrillGraphBinaryReader.cpp, networkit/cpp/sparsification/GlobalThresholdFilter.cpp, networkit/test/test_graphio.py
=> introduces new parallel graph builder and deprecates old one

networkit/community.pyx, networkit/test/test_community.py
adresses #1217 and adds the corresponding test
=> python: fix overlapping_nmi_distance + add test

include/networkit/algebraic/CSRGeneralMatrix.hpp, include/networkit/algebraic/DenseMatrix.hpp, include/networkit/algebraic/DynamicMatrix.hpp, include/networkit/algebraic/MatrixTools.hpp, networkit/cpp/algebraic/DenseMatrix.cpp, networkit/cpp/algebraic/DynamicMatrix.cpp, networkit/cpp/algebraic/test/MatricesGTest.cpp
adresses usability improvements adressed in https://github.com/orgs/networkit/projects/1/views/1?pane=issue&itemId=62136231 for the algebraic module and adds corresponding tests
=> c++: adds usability related matrix operators and tests

networkit/vizbridges.py, notebooks/Visualization.ipynb
This feature was requested by @bernlu, we may add node attribute visualization later on aswell.
=> vizbridges: adds edge attribute visualization

.github/workflows/ci.yml, README.md, networkit/graph.pyx, pyproject.toml
re-upload of #1234 where the commits have been split
=> graph.pyx: adjust datatypes to be compatible with numpy2.0

include/networkit/generators/ChungLuGeneratorAlamEtAl.hpp, networkit/cpp/generators/CMakeLists.txt, networkit/cpp/generators/ChungLuGeneratorAlamEtAl.cpp, networkit/cpp/generators/test/GeneratorsGTest.cpp
re-upload of #1166 from different fork
=> adds chungLuAlamEtAl generator + tests

include/networkit/centrality/DynBetweennessOneNode.hpp, networkit/cpp/centrality/DynBetweennessOneNode.cpp, networkit/cpp/centrality/test/DynBetweennessGTest.cpp
This PR addresses the issue mentioned [in this discussion](https://github.com/networkit/networkit/discussions/990). Furthermore, it adds the corresponding GTest to ensure proper integration.
=> cpp: fixDynBetweennessOneNode for weighted graphs

include/networkit/algebraic/CSRGeneralMatrix.hpp, include/networkit/centrality/ApproxGroupBetweenness.hpp, include/networkit/centrality/GroupDegree.hpp, include/networkit/centrality/KadabraBetweenness.hpp, include/networkit/distance/AStarGeneral.hpp, include/networkit/distance/STSP.hpp, include/networkit/graph/Graph.hpp, include/networkit/matching/BSuitorMatcher.hpp, networkit/cpp/centrality/GedWalk.cpp, networkit/cpp/centrality/GroupCloseness.cpp, networkit/cpp/centrality/TopHarmonicCloseness.cpp, networkit/cpp/graph/Graph.cpp, networkit/cpp/matching/BSuitorMatcher.cpp
Ranges are a new C++20 feature: https://en.cppreference.com/w/cpp/ranges. This PR replaces some range-base functions with their `std::ranges` counterpart, for example:
```cpp
std::vector<node> someNodes = {1, 2, 3};
// Before:
std::fill(someNodes.begin(), someNodes.end(), 0);
// After:
std::ranges::fill(someNodes, 0);
```
The remaining range-base functions can be replaced with `std::ranges` in future PRs.
=> Use std::range functions.

.github/workflows/ci.yml, .github/workflows/scripts/documentation.sh, .github/workflows/scripts/full.sh
Fix effectively fixes current errors on CI.
=> CI: Add anywidget before doing notebook tests.

setup.py
This PR removes the compiler detection from setup.py. Instead of relying on manual search for a compatible compiler, instead the default case is now to rely on CMake detection schemes. It is still possible to pass a custom compiler to `pip install` via setting either `CXX` or `NETWORKIT_CXX_COMPILER`.
=> Remove compiler detection from setup.py.

include/networkit/flow/Dinic.hpp, networkit/cpp/flow/CMakeLists.txt, networkit/cpp/flow/Dinic.cpp, networkit/cpp/flow/test/CMakeLists.txt, networkit/cpp/flow/test/DinicGTest.cpp
This PR adds a new Dinic class that implements Dinic’s blocking‐flow algorithm for calculating maximum flow in directed, weighted graphs. Given a source and target node, it constructs a residual graph from edge capacities (edgeweight) and computes the maximum transferable flow between them.
=> Dinic algorithm

networkit/graphtools.pyx, pyproject.toml
=> Removes Cython version pinning and deprecated semantics
